ansys/pyfluent

examples/00-fluent/README.txt
examples/00-fluent/exhaust_system.py
examples/README.txt
src/ansys/fluent/core/utils/logging.py

I had added these with generic descriptions a while back and thought they can be clarified now.

Tidy up descriptions a little bit

---

.github/workflows/ci.yml
.github/workflows/nightly-doc-build.yml
doc/Makefile
doc/make.bat

Packages and documentation are not uploaded for 23.1 backend. I've just disabled the verbose logging during doc build - will check how much API information is exposed from logs.

Support 22.2 and 23.1 backends

---

src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_lite.py

Removed settings API warning from following files - 
1. session.py
2. session_solver.py
3. session_solver_lite.py

Removed settings API warning

---

src/ansys/fluent/core/_version.py

Bump version 0.11.dev1

---

.github/workflows/nightly-test-run.yml
Makefile

Added a CI job to run all unittests nightly. We can now reduce the number of tests run with PRs.

Add CI for nightly test run

---

tests/test_solvermode/test_controls.py
tests/test_solvermode/test_general.py
tests/test_solvermode/test_initialization.py
tests/test_solvermode/test_materials.py
tests/test_solvermode/test_methods.py
tests/test_solvermode/test_models.py
tests/test_solvermode/test_named_expressions.py
tests/util/fixture_fluent.py

New tests added and increased the coverage in old tests.

New tests added

---

src/ansys/fluent/core/meshing/workflow.py
tests/util/meshing_workflow.py

Fixes for meshing workflow tests (tests/test_meshing_workflow.py)

fix mwf tests

---

.github/workflows/ci.yml
.github/workflows/nightly-test-run.yml
src/ansys/fluent/core/_version.py

Bump version 0.12.dev0 in main

Bump version 0.12.dev0

---

codegen/datamodelgen.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py

preferences

---

tests/test_solvermode/test_controls.py
tests/test_solvermode/test_initialization.py

The 2 failing tests in Nightly Test Run are fixed:
1. test_initialization.py
2. test_controls.py

Fixed the failing tests in nightly test run

---

src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py

Now we can assign settings in following ways.
```setup.models.energy.set_state(enabled=True, viscous_dissipation=False)```
```setup.models.energy(enabled=True, viscous_dissipation=False)```

User friendly settings assignments

---

tests/test_casereader.py

Added case file to example-data repo.
Enabled test for mixer-ran case file.

Enabled the test for mixer-ran case file

---

tests/test_preferences.py

Added tests for preferences

---

src/ansys/fluent/core/solver/flobject.py

Corresponding Fluent PR 343462

Fix flobject for pyconsole

---

doc/source/user_guide/launching_ansys_fluent.rst
doc/styles/Vocab/ANSYS/accept.txt

Added a new section in the user guide to cover scheduler and distributed parallel support.

Add section for scheduler support doc

---

src/ansys/fluent/core/launcher/launcher.py

The existence check and name check has been simplified to existence check only to avoid unnecessary errors.

Removed the error prone fluent.exe check

---

.github/workflows/nightly-test-run.yml
doc/source/conf.py

Corresponding Fluent PR 346379

Disable numpydoc validation for settings API module

---

Makefile
src/ansys/fluent/core/launcher/fluent_container.py
tests/conftest.py

to identify if a test is not cleanly stopping the launched container. Command to check the label:
```
docker inspect --format='{{.Config.Labels.test_name}}' <container-id>
```

Label test name to docker container

---

src/ansys/fluent/core/solver/flobject.py

Corresponding Fluent PR 347967
Please check the Fluent side PR for details about the change.

Fix the user-creatable? issue.

---

Makefile
codegen/fix_doc.py
codegen/settingsgen.py
tests/test_fix_doc.py

This will fix the 23.1 nightly doc build

Fix 23.1 doc build

---

src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/services/scheme_eval.py
tests/test_scheme_eval.py
tests/test_scheme_eval_222.py
tests/test_scheme_eval_231.py
tests/test_session.py

Fluent side changes and ansys-api-fluent package upgrade should happen before merging this.

Fix SchemePointer bug

---

src/ansys/fluent/core/utils/setup_for_fluent.py

@seanpearsonuk, please have a look at this. Thank you

solvermode available only in solver session - setup_for_fluent

---

src/ansys/fluent/core/_version.py

Creating a dev release w.r.t. the changes in the FieldData (regarding path-lines).

Bump version to 0.12.dev3

---

tests/test_solvermode/test_general.py

Need to first fix the Fluent side bug 734010 before we can activate this.

Disable read_journal test

---

src/ansys/fluent/core/services/scheme_eval.py
tests/test_scheme_eval_231.py

This will fix the nightly doc failure in the parametric repo.

Fix an issue with list with single item

---

src/ansys/fluent/core/_version.py

Releasing new dev version for setup.py change and to use the scheme_eval fix in parametric repo.

Bump version 0.12.dev4

---

src/ansys/fluent/core/_version.py

Required for Pyfluent visulaization.

Bump version to 0.12.dev5

---

src/ansys/fluent/core/services/datamodel_se.py

Fix noise issue in workflow grpc calls

---

src/ansys/fluent/core/_version.py

This dev release will contain all the latest changes in the structure of transcript. journal invoking, etc. for running the dependent repos like UI.

Bump version v0.12.dev6

---

src/ansys/fluent/core/services/field_data.py
tests/test_field_data.py

fix for long-standing bug
getting surface ids via grpc as if just int but its List[int]

fix for surf ids

---

.ci/compare_flobject.py
.github/workflows/nightly-doc-build.yml
codegen/tuigen.py
src/ansys/fluent/core/launcher/launcher.py

1. Fix for `start_instance` argument which fixes the issue with `server_info_filepath` argument.
2. Some changes I forgot to commit with the 23.2 CI PR.

Fix for start_instance argument and some missing changes from 232 CI PR

---

src/ansys/fluent/core/services/datamodel_se.py
tests/test_datamodel_server/test_client.py

Renamed `get_attrib_value` to `get_attr`.

Renamed "get_attrb_value" to "get_attr"

---

src/ansys/fluent/core/_version.py

Release tag v0.12.dev8

---

src/ansys/fluent/core/launcher/launcher.py
tests/test_session.py
tests/test_topy.py

Added basic test for `topy`.
Refactored code in `launcher.py`

Added test for topy

---

src/ansys/fluent/core/meta.py

Update the meta.py to include dependencies, like command arguments via inspection and its class.

Update UI dependencies.

---

src/ansys/fluent/core/_version.py

This is required for the related changes in the UI repo to work.

Bump version to v0.12.dev10

---

Makefile
tests/test_field_data.py
tests/test_session.py

This PR fixes the nightly test run which was hanging.

Fix nightly test run.

---

src/ansys/fluent/core/meta.py

meta.py was updated in accordance to the data-model structure created in the ui-repo, and this PR contains some fixes to the Command class for accessing objects and parents correctly, etc.
This task is being performed according to the description provided in: https://github.com/pyansys/pyansys-ui/issues/110

Clean up meta.py

---

.github/workflows/ci.yml
Makefile
README.rst
codecov.yml

Upload pyfluent code coverage in codecov website, like already being done by pymapdl and other projects.

Upload test coverage report to codecov website.

---

src/ansys/fluent/core/meta.py
src/ansys/fluent/core/post_objects/post_object_definitions.py

This contains updates specific to visualization repo.

Updates for viz repo.

---

.github/workflows/nightly-test-run.yml

Upload nightly test coverage results to codecov website.

Upload nightly test coverage results to codecov.

---

src/ansys/fluent/core/services/field_data.py

Resolved interference of `FieldMethod` infrastructure with `help().`
`------------------------------------------------------------------------------------------------------------------------`

FieldMethod infrastructure help

---

src/ansys/fluent/core/_version.py

This release contains the fixes affecting the visualization repo.

Bump version to v0.12.dev12

---

.github/workflows/ci.yml
README.rst

Implementing pre-commit.ci

---

setup.py
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/meta.py
src/ansys/fluent/core/post_objects/post_object_definitions.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py

Changes for dash UI. 
- Added Create/Delete method for container
- Added missing functionalities in settings.py

UI changes.

---

src/ansys/fluent/core/_version.py

This release contains changes for the  UI repo.

Bump version to v0.13.dev1

---

src/ansys/fluent/core/utils/setup_for_fluent.py

Fix pyconsole meshing script

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.rst
doc/source/getting_started/faqs.rst
doc/styles/Vocab/ANSYS/accept.txt

Ran the README, CONTRIBUTING and CODE_OF_CONDUCT guides through Vale and adjusted them a bit.

Fixed up some more things with Vale

---

src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_solver.py
test.py
tests/test_session.py

Usage:
```
pyfluent.USE_LIGHT_IO = True
solver = pyfluent.launch_fluent()
solver.read_case(file_name="elbow.cas.h5")
```
1. Requires some fixes in server side as `solver._root.set_state(solver._root.get_state())` doesn't work from PyFluent in general
2. `solver.file.read` and `solver.file.read_case` to be replaced with `solver.read_case`

Read case using light IO mode

---

src/ansys/fluent/core/services/field_data.py

`-------------------------------------------------------------------------------`
`-------------------------------------------------------------------------------`

FieldData help() update

---

src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/solver/flobject.py
tests/test_settings_api.py

Support wildcard path

---

README.rst

Fix Broken Links to Viz/Parametric Doc

---

src/ansys/fluent/core/utils/dump_session_data.py

This contains changes which will fix the UI repo.

Update dump data reader to handle multiple field names.

---

src/ansys/fluent/core/_version.py

This contains latest fixes and updates for the UI and visualizations repos.

Bump version to 0.13.dev3

---

setup.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py
src/ansys/fluent/core/streaming_services/datamodel_streaming.py
src/ansys/fluent/core/workflow.py
tests/test_datamodel_service.py

ansys-api-fluent PR - https://github.com/ansys/ansys-api-fluent/pull/30

Add command-executed event and diff-state option

---

tests/test_icing_session.py

This test just checks for the correct working of the solver-icing session.

Added a simple test for icing session.

---

.pre-commit-config.yaml
src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/launcher/fluent_container.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/utils/networking.py
tests/test_session.py

Added vpn network fix from main

Bump version 0.12.5

---

src/ansys/fluent/core/services/datamodel_se.py
tests/test_datamodel_service.py

Expose get_object_names() in meshing mode similar to that in pyconsole.

Added get_object_names() to meshing workflow.

---

src/ansys/fluent/core/utils/dump_session_data.py

This fixes a bug in the UI repo for displaying multiple surfaces.

Fix surface dump data reader.

---

doc/source/api/general/case_reader.rst
doc/styles/Vocab/ANSYS/accept.txt
src/ansys/fluent/core/filereader/case_file.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_icing.py
src/ansys/fluent/core/session_solver_lite.py
tests/test_rp_vars.py

1. 
`---------------------------------------------------------------`
2. 
`---------------------------------------------------------------`
3.

Resolved Doc issues

---

src/ansys/fluent/core/_version.py

Creating dev release for each repos, will create public release after that

Bump version 0.13.dev5

---

src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/services/streaming.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py
src/ansys/fluent/core/streaming_services/datamodel_streaming.py
src/ansys/fluent/core/streaming_services/events_streaming.py
src/ansys/fluent/core/streaming_services/field_data_streaming.py
src/ansys/fluent/core/streaming_services/monitor_streaming.py
src/ansys/fluent/core/streaming_services/streaming.py
src/ansys/fluent/core/streaming_services/transcript_streaming.py

Multiple streams can be started with a different id.

Multiple stream fix

---

src/ansys/fluent/core/services/settings.py
tests/test_settings_api.py

Wildcard was raising key-error. That has been fixed. A test case has been added for the same.

Fixed bug in wildcard path and added unit test.

---

src/ansys/fluent/core/_version.py

Bump version to v0.14.dev1

---

.github/workflows/ci.yml

feat: generate wheelhouse for PyFluent

---

src/ansys/fluent/core/launcher/fluent_launcher_options.json
src/ansys/fluent/core/launcher/launcher.py
tests/test_launcher.py

Add gpu: bool argument to launch_fluent()

Add gpu in launch_fluent.

---

src/ansys/fluent/core/_version.py
src/ansys/fluent/core/filereader/case_file.py
tests/test_casereader.py

I'll push the 0.13.1 tag after merging this PR.

Bump version 0.13.1

---

tests/test_fluent_fixes.py

Incorporated check of https://github.com/pyansys/pyfluent/issues/1364
Created `tests/test_fluent_fixes.py` to track fluent fixes for reference in future.

Incorporate check of #1364

---

.github/workflows/ci.yml
.github/workflows/nightly-dev-doc-build.yml
.github/workflows/release-doc-build.yml

maint: change pyansys/actions

---

.ci/pull_fluent_image.sh
.github/workflows/ci.yml
.github/workflows/nightly-doc-build.yml
codegen/tuigen.py
doc/source/conf.py
src/ansys/fluent/core/launcher/fluent_container.py
tests/test_settings_api.py

I think version patching would not be required. I'll run [release-doc-build](https://github.com/ansys/pyfluent/blob/main/.github/workflows/release-doc-build.yml) CI on release/0.12 branch after merge.

Fix multi-version documentation

---

codegen/settingsgen.py
src/ansys/fluent/core/session_solver.pyi
tests/integration/test_optislang/test_optislang_integration.py
tests/test_solvermode/test_boundaries.py

Fixes parameter level issue and type-hint for commands:

Fix static typing info for settings classes

---

.gitignore

Git ignore cleanup fluent files.

---

src/ansys/fluent/core/_version.py

Contains dependencies for the UI repo.

Bump version to v0.15.dev1

---

src/ansys/fluent/core/examples/downloads.py
tests/test_svars.py
tests/util/solver_workflow.py

Added test for SVARs

---

tests/test_fluent_fixes.py

Fix for https://github.com/ansys/pyfluent/actions/runs/5262910114/jobs/9512544052

Fix test_fluent_fixes.py

---

doc/settings_rstgen.py
pyproject.toml

- Generate settings API using 23.2 by default
- Ignore 23.2 generated code when running black

A few clean ups

---

doc/source/conf.py

This will fix the warnings like https://github.com/ansys/pyfluent/actions/runs/5290247509/jobs/9574182712?pr=1691#step:14:991

Fix undefined label error for python:bltin-boolean-values

---

doc/source/api/general/sessions/Session/fluent_connection.rst
doc/source/user_guide/launching_ansys_fluent.rst
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/meshing/meshing.py
src/ansys/fluent/core/scheduler/machine_list.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_icing.py

connect_to_fluent in user-guide

---

src/ansys/fluent/core/solver/flobject.py

Removed settings API arguments method.

Remove settings API arguments method

---

src/ansys/fluent/core/streaming_services/streaming.py

This contains a fix in the streaming service to render the graphics as expected in the UI repo.

Fix streaming to fix the UI repo.

---

doc/source/api/solver/fielddata.rst

Added `solver.solution.initialization.hybrid_initialize()` step.
otherwise we get,
```
>>> field_data = solver.field_data
>>> field_data.is_data_valid()                                                                            
False
```

Add initialize step in Field Data docs

---

doc/source/api/solver/fielddata.rst
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/session.py

Updated signature of `FieldData` class and used `scheme_eval`  in `get_vector_field_data`
Updated docs.

Vector field data method fix and doc updates

---

src/ansys/fluent/core/utils/networking.py

Resolves https://github.com/ansys/pyfluent/issues/1856
This change should not cause any issues connecting with remote/standalone/container Fluent.

Fixing security concern

---

src/ansys/fluent/core/_version.py

Contains latest changes that affects the UI and Visualization repo.

Bump version to 0.17.dev2

---

src/ansys/fluent/core/filereader/case_file.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/launcher/watchdog.py
src/ansys/fluent/core/meshing/watertight.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/solver/flobject.py
src/ansys/fluent/core/utils/data_transfer.py
src/ansys/fluent/core/workflow.py
tests/test_casereader.py

Resolved several instances of except BaseException

Instances of BaseException to be replaced with Exception.

---

doc/.vale.ini

eliminates unreasonable limitation on writing correct sentences

change vale config

---

src/ansys/fluent/core/_version.py

To include the [casereader fix](1899) in dev package

Bump 0.17.dev3

---

src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/services/interceptors.py

Closes https://github.com/ansys/pyfluent/issues/1885

Code documentation for ErrorState and ErrorStateInterceptor

---

src/ansys/fluent/core/_version.py
tests/parametric/test_parametric_workflow.py
tests/test_flobject.py
tests/test_reduction.py
tests/test_solvermode/test_boundaries.py
tests/test_solvermode/test_initialization.py

Addressing the failing tests in https://github.com/ansys/pyfluent/actions/runs/6020381003/job/16331606474#step:22:3080

Fix nightly tests and bump version 0.18.dev0

---

src/ansys/fluent/core/session.py

Using the same method from Fluent's Python console

Fix execute_tui

---

doc/source/user_guide/materials.rst

Added an example to the docs showing how to create new materials using the settings API, as an alternative to using the TUI.

Example of creating new materials using settings API

---

src/ansys/fluent/core/solver/flobject.py
tests/parametric/test_parametric_workflow.py
tests/test_fluent_fixes.py
tests/test_solvermode/test_boundaries.py
tests/test_solvermode/test_initialization.py
tests/test_solvermode/test_methods.py
tests/test_solvermode/test_named_expressions.py

1. Sync flobject.py from Fluent.
2. parametric_studies.rename is now fixed in Fluent.
3. Fix some nightly test failures.

Miscellaneous changes

---

codegen/tuigen.py
doc/source/getting_started/installation.rst
doc/source/user_guide/launching_ansys_fluent.rst

Closes https://github.com/ansys/pyfluent/issues/2030

Updating deprecated logging references

---

.github/workflows/codeql.yml

Should fix https://github.com/ansys/pyfluent/issues/2041

Adding CodeQL config YAML

---

doc/source/user_guide/tui_commands.rst

Document TUI command construction using Python journaling

---

src/ansys/fluent/core/_version.py

This contains the changes in meta.py to reflect in the UI repo.

Bump version to 0.18.dev1

---

src/ansys/fluent/core/_version.py

To fix issues with the visualization repo.

Bump version to v0.18.dev4

---

tests/test_batch_ops.py

The batch_ops test is now working on Linux, probably after the grpc version upgrade on server-side.

Unskip batch_ops test

---

doc/source/conf.py
src/ansys/fluent/core/launcher/watchdog.py
src/ansys/fluent/core/post_objects/post_object_definitions.py
src/ansys/fluent/core/post_objects/post_objects_container.py
src/ansys/fluent/core/services/batch_ops.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/services/datamodel_tui.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/services/health_check.py
src/ansys/fluent/core/services/interceptors.py
src/ansys/fluent/core/services/meshing_queries.py
src/ansys/fluent/core/services/monitor.py
src/ansys/fluent/core/services/reduction.py
src/ansys/fluent/core/services/scheme_eval.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/services/streaming.py
src/ansys/fluent/core/services/svar.py
src/ansys/fluent/core/services/transcript.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/solver/function/reduction.py
src/ansys/fluent/core/utils/networking.py
src/ansys/fluent/core/workflow.py

* Capitalizing acronyms and abbreviations

Capitalize acronyms and abbreviations

---

tests/test_cad_to_post_wtm.py

Fixed incorrectly assigned variable.

Correctly assigned velocity inlet.

---

src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py

Fix read-only? attr name

---

.github/workflows/nightly-dev-doc-build.yml
.github/workflows/release-doc-build.yml

fix: decompress artifact for doc indexing

---

.github/workflows/release-doc-build.yml

will merge after [release doc build](https://github.com/ansys/pyfluent/actions/runs/6548755650) is successful

Disable meilisearch for 0.18 release

---

src/ansys/fluent/core/services/api_upgrade.py
src/ansys/fluent/core/services/batch_ops.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/services/datamodel_tui.py
src/ansys/fluent/core/services/health_check.py
src/ansys/fluent/core/services/interceptors.py
src/ansys/fluent/core/services/scheme_eval.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/services/transcript.py

Found [pytype](https://google.github.io/pytype/) is quite useful to generate the stubs for missing type annotations.

Add type annotations for some modules under services

---

src/ansys/fluent/core/_version.py

Creating a dev release to use the latest code in pyfluent-reader repo

Bump version 0.19.dev1

---

doc/source/api/solver/index.rst

Fix SVAR doc

---

.github/workflows/nightly-dev-doc-build.yml
.github/workflows/release-doc-build.yml
doc/source/conf.py

For https://github.com/ansys/pyfluent/issues/2093
Reverting to the previous search function setup we had, while the new search function is ironed out (for now only dev docs, if this works as expected will do the same for stable version)
We just need to revert the commit from this PR when we want to try the new version again

Reverting documentation search function

---

src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver.pyi
tests/test_launcher.py
tests/test_meshing_workflow.py
tests/test_rp_vars.py
tests/test_session.py
tests/test_settings_api.py
tests/test_svars.py
tests/test_tui_api.py
tests/util/solver_workflow.py

Enabling the skipped tests which are passing in the latest version.

Enable some skipped tests

---

tests/test_settings_api.py

The test is failing in nightly

Move the wildcard test to 24.1 as it depends on 24.1 API

---

src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_icing.py
src/ansys/fluent/core/utils/data_transfer.py
src/ansys/fluent/core/utils/file_transfer_service.py

Refactor Seamless File Handling

---

.github/workflows/codeql.yml

Closes https://github.com/ansys/pyfluent/issues/2191, will prevent this issue from happening in future release branches

Fix to CodeQL for future release branches

---

src/ansys/fluent/core/services/datamodel_se.py
tests/test_datamodel_service.py

Fix generic datamodel when generated datamodel classes are not available

Fix generic datamodel

---

.github/workflows/ci.yml
src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py

Added a python_path function to format a __getattribute__ runtime error to python syntax.

Pythonic Syntax for __getattribute__ Error.

---

tests/conftest.py
tests/test_fluent_version.py
tests/test_launcher.py

Quick idea that I had while reviewing PR #2262, showcases how these new additions can be helpful
All of these tests should now be automatically maintained/updated as new releases come out, without requiring special attention 
Can be merged before or after PR #2262: if merged before will become part of that PR, if merged after will automatically be redirected to `main`

Suggestion for #2262

---

.github/workflows/ci.yml

Added styles from: https://actions.docs.ansys.com/version/stable/style-actions/index.html
Added **commit style action**
Added **branch name style action**

feat: More Styles Added

---

src/ansys/fluent/core/_version.py

Patch release to update PyPi tag.

build: Bump version to 0.19.1 (patch release)

---

src/ansys/fluent/core/services/datamodel_se.py

Updated the signature of some newly added datamodel methods like "rename", "get_object_names", "delete_child_objects" and "delete_all_child_objects". This is done to be consistent with PyConsole side implementation of these methods.

refactor: Restructure datamodel methods.

---

src/ansys/fluent/core/solver/flobject.py

This PR can be merged once server-side changes are in place.

refactor: Make flobject consistent with server.

---

doc/source/user_guide/launching_ansys_fluent.rst
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/launcher/slurm_launcher.py

docs: Document additional slurm options (#2373)

---

doc/source/getting_started/faqs.rst
src/ansys/fluent/core/session_meshing.pyi
src/ansys/fluent/core/session_pure_meshing.pyi
src/ansys/fluent/core/session_solver.pyi

Update the interface files with 24.1 Fluent API so that 24.1 API is available in static intellisense (vscode/pycharm).

build: intellisense support for 24.1 Fluent API

---

src/ansys/fluent/core/launcher/container_launcher.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/launcher/launcher_utils.py
src/ansys/fluent/core/launcher/pim_launcher.py
src/ansys/fluent/core/launcher/slurm_launcher.py
src/ansys/fluent/core/launcher/standalone_launcher.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_icing.py
tests/test_launcher.py

This contains some refactoring of the launcher code as well as a bug fix for launching meshing mode correctly in stand-alone mode.

refactor: Fix pyfluent launcher.

---

doc/source/getting_started/faqs.rst
src/ansys/fluent/core/session_meshing.pyi
src/ansys/fluent/core/session_pure_meshing.pyi
src/ansys/fluent/core/session_solver.pyi

Update the interface files with 24.1 Fluent API so that 24.1 API is available in static intellisense (vscode/pycharm).

build: intellisense support for 24.1 Fluent API (#2386)

---

src/ansys/fluent/core/_version.py

build: Bump version to 0.19.2

---

tests/test_flobject.py
tests/test_meshing_workflow.py

A minor version check to attend to a settings-api change.

refactor: Fix/nightly test latest

---

doc/source/api/solver/settings.rst

Automate settings root hyperlink update and make it clickable.

docs: settings root link

---

src/ansys/fluent/core/meta.py

Fix for https://github.com/ansys/pyfluent-visualization/issues/359

fix: Graphics issue

---

Makefile
tests/conftest.py

For some randomly failing tests in CI we have added a tag to re-run the failed tests again.

build: fix random test failures in ci by re-runnung them.

---

doc/source/api/solver/settings.rst

Merging #2400 into release/0.19

docs: settings root link (#2400)

---

src/ansys/fluent/core/_version.py

For including the pyfluent package in Ansys Python distribution.

build: Bump version 0.20.dev1

---

src/ansys/fluent/core/workflow.py
tests/test_meshing_workflow.py
tests/test_new_meshing_workflow.py
tests/test_pure_mesh_vs_mesh_workflow.py

Arguments access in meshing workflow is made snake case now.
For example:
```
>>> watertight.create_surface_mesh.CFDSurfaceMeshControls.MaxSize.set_state()
```
is now
```
>>> watertight.create_surface_mesh.cfd_surface_mesh_controls.max_size.set_state()
```
For more details please look into the updated docs and tests.

feat: Snake case workflow arguments access.

---

src/ansys/fluent/core/_version.py
src/ansys/fluent/core/launcher/standalone_launcher.py
src/ansys/fluent/core/solver/flobject.py

1. Removed PimFileTransferService from standalone launcher.
2. Updated _do_before_execute and _do_after_execute methods.
3. Updated remote_file_handler property.
Verified that script provided by @millerj97 is working fine now.

refactor: read/write fail after switching to solver mode

---

doc/settings_rstgen.py
doc/source/api/solver/settings.rst

Merge https://github.com/ansys/pyfluent/pull/2468 into release/0.19

docs: settings root hyperlink latest

---

.github/styles/config/vocabularies/ANSYS/accept.txt
codegen/settingsgen.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/solver/flobject.py

feat: support inout file purpose

---

src/ansys/fluent/core/filereader/case_file.py
src/ansys/fluent/core/rpvars.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/services/solution_variables.py
src/ansys/fluent/core/solver/error_message.py
src/ansys/fluent/core/solver/flobject.py
tests/test_casereader.py
tests/test_flobject.py
tests/test_settings_reader.py

Improve error handling message.

refactor: Fix error handling msg in flobject.

---

src/ansys/fluent/core/_version.py
tests/test_settings_api.py

Creating a new pre-release package incorporating the latest changes to integrate with Ansys CPython distribution.

build: Bump version 0.20.dev5

---

tests/test_settings_api.py

This is failing in the latest image

test: Fix test_wildcard

---

src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/utils/file_transfer_service.py

Closes https://github.com/ansys/pyfluent/issues/2507 and https://github.com/ansys/pyfluent/issues/2513
1. Updated docstring of `create_launcher` function.
2. Updated session level `upload` and `download` methods.
3. Updated docstring of `PimFileTransferService` class.

refactor: Update create_launcher and upload/download methods

---

src/ansys/fluent/core/_version.py

build: Bump version to 0.20.dev6

---

src/ansys/fluent/core/_version.py
tests/test_settings_api.py

To include the latest aliasing fixes, required in parametric unittests.

build: Bump version 0.20.dev7

---

tests/test_flobject.py

Simply add a test based on what was reported in Fluent. It passes here.

test: test issue reported in Fluent console

---

src/ansys/fluent/core/session_pure_meshing.py

couple of local variables appearing in dir(meshing) has been addressed.

refactor: Fix dir over meshing.

---

src/ansys/fluent/core/workflow.py
tests/test_new_meshing_workflow.py

Some bug fixes related to the enhanced meshing workflow interface.

fix: update enhanced meshing interface

---

src/ansys/fluent/core/workflow.py

Arg settings were not reflecting to gui.

fix: Bug in arg setting for Enhanced Meshing Workflow.

---

pyproject.toml
src/ansys/fluent/core/_version.py

Contains all bug fixes of the enhanced meshing workflow and some restructuring of the session attributes.

build: Bump version to 0.20.dev9

---

.github/workflows/ci.yml
pyproject.toml
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/solver/flobject.py
tests/test_settings_api.py

Bumping a new version within same PR as we need the fix in Fluent soon.

fix: Avoid unstable API warning while executing commands.

---

tests/test_new_meshing_workflow.py
tests/test_settings_api.py

Latest update from settings-api. This fix needs to be pulled by all PRs to fix the test runs.

fix: setting api test.

---

tests/test_new_meshing_workflow.py

Fix a 2D Meshing test which is causing the Nightly test run to fail.

fix: 2d Meshing test.

---

codegen/settingsgen.py
pyproject.toml
tests/test_type_stub.py

This will fix the intellisense issue in vscode while using the settings API.

fix: settings api typehints

---

tests/test_new_meshing_workflow.py
tests/util/meshing_workflow.py

Added test to check that the enhanced meshing workflow behaves correctly for independent fluent sessions.

test: Add tests to check independent sessions in enhanced meshing workflow.

---

Makefile
doc/Makefile
pyproject.toml
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/file_session.py
src/ansys/fluent/core/services/field_data.py
tests/test_new_meshing_workflow.py
tests/test_settings_api.py

Releasing a patch version with the fix for boundary_value default issue which is a class-3 in Fluent.

build: Bump version 0.20.1

---

src/ansys/fluent/core/utils/dictionary_operations.py
tests/test_utils.py

Add testing for and adjust new function.

test: test dict op

---

src/ansys/fluent/core/utils/dictionary_operations.py
src/ansys/fluent/core/workflow.py
tests/test_new_meshing_workflow.py
tests/test_utils.py

Earlier initializing the pre-defined workflows like "watertight" was taking approximately 50 seconds. Now this timing has been reduced to take only approximately 4 seconds. This is by reducing number of server calls and using cached data.

refactor: Update Enhanced Meshing workflow to cache data faster.

---

doc/source/user_guide/launching_ansys_fluent.rst
src/ansys/fluent/core/fluent_connection.py

The names are taken from [Fluent documentation](https://ansyshelp.ansys.com/account/secured?returnurl=/Views/Secured/corp/v241/en/flu_lm/flu_sge_usingman.html).

docs: mention SGE support

---

doc/rstgen.py

closes https://github.com/ansys/pyfluent/issues/2763
Fix menu name and reference.

fix: menu name and title fix

---

src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py

closes https://github.com/ansys/pyfluent/issues/2778
1. Updated attribute check in settings exception block.

fix: settings allowed values check

---

pyproject.toml

Update pandas with the version available for fluent.

build: Update pandas version.

---

doc/rstgen.py

closes https://github.com/ansys/pyfluent/issues/2824
Incorrect - 
Corrected -

docs: datamodel index docs update

---

src/ansys/fluent/core/systemcoupling.py

Evaluating fix, to be merged with #2812

fix: proper path for system coupling test

---

.github/workflows/ci.yml
Makefile
pyproject.toml

1. Delete poetry.lock before installing doc dependencies in poetry environment. It seems poetry.lock from previous run can persist (?).
2. Use sphinx-build from poetry environment.

fix: fix doc build [skip tests]

---

pyproject.toml
src/ansys/fluent/core/_version.py

Contains updates w.r.t. the latest 25.1 fluent image and enhanced meshing workflow fixes.

build: Bump version to v0.21.dev1

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.22.dev0

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to 0.21.0

---

.github/workflows/ci.yml
doc/source/api/general/index.rst

closes https://github.com/ansys/pyfluent/issues/2971
**1. Fix case reader doc**
`----------------------------------------------------------------------------------------`
**2. Fix data reader doc**

docs: Fix case and data file reader doc [skip tests]

---

src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/session_solver_icing.py

Some minor styling issues have been resolved in the docstrings.

docs: Update format of session docstrings.

---

pyproject.toml
src/ansys/fluent/core/_version.py

Version wasn't correctly updated in the last PR.

build: Bump version 0.21.2

---

src/ansys/fluent/core/services/api_upgrade.py

closes https://github.com/ansys/pyfluent/issues/3013
**Now**
```
The following solver settings object method could also be used to execute the above command:
<solver_session>.settings.file.read_case(file_name = r"D:\Repos\pyfluent\mixing_elbow.cas.h5")
```
**Earlier**
```
The following solver settings object method could also be used to execute the above command:
<solver_session>.file.read_case(file_name = r"D:\Repos\pyfluent\mixing_elbow.cas.h5")
```

fix: Update api_upgrade message

---

doc/source/api/general/fielddata.rst
doc/source/api/general/file_session.rst
src/ansys/fluent/core/post_objects/post_helper.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/utils/deprecate.py
tests/test_field_data.py
tests/test_file_session.py

This contains the updated tests and docs for the refactored field_data interface.
Please let me know if I have missed and docs or tests that needs updating as well. 
Thank you.

refactor: Update tests and docs for updated field data interface

---

src/ansys/fluent/core/workflow.py

Tested both in PyFluent and PyConsole.

fix: Classic Meshing Workflow.

---

.github/workflows/doc-build-release.yml

Merging the recent changes in the nightly doc CI onto the release doc CI.
I'm running the release doc CI on this branch to check whether this fixes the current issue.

fix: release doc CI [skip tests]

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to 0.23.dev0

---

src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/session.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/streaming_services/events_streaming.py
tests/test_events_manager.py
tests/test_session.py

Separate meshing and solver events.

feat: mesh-events

---

.github/workflows/ci.yml
doc/settings_rstgen.py
src/ansys/fluent/core/codegen/settingsgen.py
src/ansys/fluent/core/codegen/tuigen.py
src/ansys/fluent/core/launcher/fluent_container.py
src/ansys/fluent/core/utils/fluent_version.py
tests/test_flobject.py

The hash-mismatch issue is coming from #3107, where the static-info has been modified while generating the settings classes. In this PR, I'm computing the hash from static-info before generating the settings classes.

fix: Fix hash mismatch issue

---

doc/source/user_guide/session/launching_ansys_fluent.rst

Fix for item numbering in one RST file as well as qualifying server file instructions.

docs: fix numbering [skip tests]

---

src/ansys/fluent/core/services/scheme_eval.py
src/ansys/fluent/core/services/settings.py
src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py
tests/test_settings_api.py

This will require Fluent image update + passing nightly dev build

fix: wildcard level set_state

---

.github/workflows/ci.yml
src/ansys/fluent/core/meshing/meshing_workflow.py
src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_pure_meshing.py
src/ansys/fluent/core/workflow.py
tests/test_new_meshing_workflow.py

```Python
>>> current_workflow = meshing.current_workflow()
```
For accessing a workflow while connecting to an already running session.

feat: Add 'current_workflow()' to enhanced meshing workflow.

---

src/ansys/fluent/core/services/api_upgrade.py
tests/test_tui_api.py

<solver_session>.settings should get generated automatically for versions >= 25.1

fix: Api upgrade message.

---

src/ansys/fluent/core/codegen/data/meshing_utilities_examples.py
src/ansys/fluent/core/codegen/datamodelgen.py
tests/test_meshing_utilities.py

closes https://github.com/ansys/pyfluent/issues/3177
Update meshing utilities docstrings

fix: Update meshing utilities docstrings

---

pyproject.toml
src/ansys/fluent/core/_version.py

Release all latest bug fixes. This is a dev release for testing by the dev team before creating a stable minor release to be provided to the build team.

build: Bump version to v0.23.dev1

---

pyproject.toml
src/ansys/fluent/core/_version.py
tests/test_search.py

build: Bump version to v0.22.1

---

doc/api_rstgen.py

closes https://github.com/ansys/pyfluent/issues/3218
Add Settings root in API reference.

fix: Settings root in API reference

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.25.dev1

---

doc/api_rstgen.py
pyproject.toml
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/post_objects/post_helper.py

build: Bump version to v0.24.2

---

doc/source/user_guide/file_transfer.rst
src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/utils/file_transfer_service.py
tests/test_file_transfer_service.py
tests/test_launcher_remote.py

closes https://github.com/ansys/pyfluent/issues/3078, https://github.com/ansys/pyfluent/issues/2910
1. Updated user guide section.
2. Updated docstrings by adding examples.
3. Increased test coverage.
4. Added test for `server_cwd` in `LocalFileTransferStrategy`.

docs: Update file transfer docs

---

tests/parametric/test_local_parametric_run.py

closes https://github.com/ansys/pyfluent/issues/3139

fix: test_local_parametric_run

---

src/ansys/fluent/core/workflow.py
tests/test_new_meshing_workflow.py

Fix issue with compound child task insertion in meshing workflow. This is a change in the internal implementation and the user interface and tests are not to be affected.

fix: Implementation of Compound Child.

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.25.0

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.26.dev0

---

tests/test_session.py

**Test behavior of some exceptions.**
read case with non-existent path -> Throws error
iterate with no case -> Throws error
- Does not throw for surface mesh.
post-process with no data
- mesh does not throw when case is not read, but gives a server side error.
- other graphics objects throw after case read if data not available.
write case for some impractical scenario if it can be set up as such  -> Throws error

test: test general exception behavior.

---

src/ansys/fluent/core/workflow.py
tests/test_new_meshing_workflow.py

Update tests to run in nightly CI.

test: Update enhanced meshing workflow tests.

---

tests/test_flobject.py

Update path with latest changes: <session> to <session>.settings

refactor: Update flobject test w.r.t. updated path.

---

src/ansys/fluent/core/launcher/standalone_launcher.py

Fix the UIMode comparison for linux systems in stand-alone mode.

fix: ui_mode comparison in non-windows system.

---

src/ansys/fluent/core/services/solution_variables.py

Fix issue with hitting the system recursion limit for 'get_data' in "SolutionVariableData".

fix: recursion issue with svar 'get_data'.

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.26.0

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.27.dev0

---

src/ansys/fluent/core/services/datamodel_tui.py
tests/test_tui_api.py

Remove 'exit' from tui as we have a well documented exit method from session.

refactor: Remove 'exit' from tui.

---

src/ansys/fluent/core/services/datamodel_se.py
tests/test_datamodel_service.py

Add missing named object container methods.

fix: add missing methods

---

tests/test_meshing_utilities.py

closes https://github.com/ansys/pyfluent/issues/3348
Update `test_meshing_utilities`

fix: Update test_meshing_utilities

---

src/ansys/fluent/core/utils/file_transfer_service.py
tests/test_file_transfer_service.py

closes https://github.com/ansys/pyfluent/issues/3352
Update `upload` and `download` methods in `LocalFileTransferStrategy`.

fix: Update LocalFileTransferStrategy

---

src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/solver/settings_builtin_bases.py
src/ansys/fluent/core/solver/settings_builtin_data.py
tests/test_builtin_settings.py

Add the remaining built-in settings from the results, parameters nodes of Fluent's outline view.

feat: Add the remaining built-in settings

---

src/ansys/fluent/core/streaming_services/events_streaming.py

fix: Remove unimplemented iteration started event

---

.github/workflows/ci.yml
pyproject.toml
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/meshing/meshing_workflow.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/session_base_meshing.py
src/ansys/fluent/core/session_solver.py
src/ansys/fluent/core/streaming_services/events_streaming.py
src/ansys/fluent/core/utils/file_transfer_service.py
src/ansys/fluent/core/workflow.py
tests/test_creatable.py
tests/test_datamodel_service.py
tests/test_file_transfer_service.py
tests/test_meshing_utilities.py
tests/test_meshing_workflow.py
tests/test_new_meshing_workflow.py
tests/test_type_stub.py

Bump version to v0.26.1
List of commits:
git cherry-pick bc5ce13a312d4ac768aaafef52a12345ec6150c2  (https://github.com/ansys/pyfluent/pull/3323)   SP
git cherry-pick b0da2ea4c81d7e6b5ee76869cbd1b5ca7c74094b  (https://github.com/ansys/pyfluent/pull/3343)   MK
git cherry-pick 0ff01698d8f411a9e3563d6617dae9118b275be9  (https://github.com/ansys/pyfluent/pull/3321)   PM
git cherry-pick e324019da5cb9a5200e04a49509a8dacec4ebdf9  (https://github.com/ansys/pyfluent/pull/3349)   MK
git cherry-pick 196c985ee5b5246ca008df7cdbcfeb8bd7beb579  (https://github.com/ansys/pyfluent/pull/3353)   HP
git cherry-pick 24a62b538f9b7d8b3787b3ef21fb73b2f8c13f2b  (https://github.com/ansys/pyfluent/pull/3332)   PM
git cherry-pick 3a281e9591d80669584ddc5f1727297ecd866b43  (https://github.com/ansys/pyfluent/pull/3367) …

build: Bump version to v0.26.1

---

pyproject.toml
src/ansys/fluent/core/services/datamodel_se.py
tests/test_new_meshing_workflow.py

Recursively update dictionary.

feat: Recursive 'update_dict'.

---

.github/workflows/ci.yml

ci: simplify doc-style action call

---

tests/test_launcher_remote.py

closes https://github.com/ansys/pyfluent/issues/3406
Use monkeypatch to set global variable

fix: Use monkeypatch to set global variable

---

doc/source/user_guide/solver_settings/index.rst
doc/source/user_guide/solver_settings/set_up/boundary_conditions.rst
doc/source/user_guide/solver_settings/set_up/materials.rst
doc/source/user_guide/solver_settings/set_up/models/battery.rst
doc/source/user_guide/solver_settings/set_up/models/dpm.rst
doc/source/user_guide/solver_settings/set_up/models/energy.rst
doc/source/user_guide/solver_settings/set_up/models/radiation.rst
doc/source/user_guide/solver_settings/set_up/models/species.rst
doc/source/user_guide/solver_settings/set_up/models/viscous.rst

closes https://github.com/ansys/pyfluent/issues/3416
Updated docs for direct settings object format.

docs: direct settings object format

---

CONTRIBUTORS.md

closes https://github.com/ansys/pyfluent/issues/3358

chore: Fix CONTRIBUTORS.md

---

src/ansys/fluent/core/_version.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/launcher/slurm_launcher.py
src/ansys/fluent/core/launcher/standalone_launcher.py
tests/conftest.py
tests/test_field_data.py
tests/test_flobject.py
tests/test_launcher.py
tests/test_reduction.py
tests/test_search.py

1. Enable some tests which have been fixed during 25.1.
2. Fix some standalone tests.

test: enable some skipped tests

---

doc/source/api/index.rst
doc/source/conf.py
src/ansys/fluent/core/data_model_cache.py
src/ansys/fluent/core/exceptions.py
src/ansys/fluent/core/file_session.py
src/ansys/fluent/core/filereader/lispy.py
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/launcher/error_handler.py
src/ansys/fluent/core/launcher/process_launch_string.py
src/ansys/fluent/core/launcher/slurm_launcher.py
src/ansys/fluent/core/parametric.py
src/ansys/fluent/core/post_objects/post_helper.py
src/ansys/fluent/core/rpvars.py
src/ansys/fluent/core/services/__init__.py
src/ansys/fluent/core/services/api_upgrade.py
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/services/datamodel_tui.py
src/ansys/fluent/core/services/reduction.py
src/ansys/fluent/core/services/solution_variables.py
src/ansys/fluent/core/session_solver_lite.py
src/ansys/fluent/core/solver/flobject.py
src/ansys/fluent/core/solver/flunits.py
src/ansys/fluent/core/streaming_services/field_data_streaming.py
src/ansys/fluent/core/systemcoupling.py
src/ansys/fluent/core/utils/dump_session_data.py
src/ansys/fluent/core/utils/file_transfer_service.py
src/ansys/fluent/core/utils/fluent_version.py
src/ansys/fluent/core/workflow.py

Fixing most warnings which are coming from Python source. There are some more remaining which are coming from .rst files.

docs: Fix some warnings seen during documentation build

---

.github/workflows/ci.yml
Makefile
devel/update_pyfluent_in_fluent.md
devel/update_settings_builtin_data.py
doc/settings_rstgen.py
src/ansys/fluent/core/codegen/allapigen.py
src/ansys/fluent/core/codegen/builtin_settingsgen.py
src/ansys/fluent/core/solver/settings_builtin_data.py
src/ansys/fluent/core/utils/fluent_version.py
tests/test_fluent_version.py

The CI change is kept disabled till the 25.2 image is available.

feat: Changes to support Fluent 25.2 dev

---

doc/source/user_guide/legacy/rpvars.rst
src/ansys/fluent/core/rpvars.py

closes https://github.com/ansys/pyfluent/issues/3471

docs: RPvars doc

---

.pre-commit-config.yaml
doc/settings_rstgen.py
src/ansys/fluent/core/scheduler/machine_list.py
src/ansys/fluent/core/services/deprecated_field_data.py
src/ansys/fluent/core/services/field_data.py
tests/test_casereader.py
tests/test_field_data.py
tests/test_flobject.py
tests/test_launcher.py
tests/test_preferences.py
tests/test_settings_api.py

Fix mutable defaults and missing asserts in code using [flake8-bugbear](https://pypi.org/project/flake8-bugbear).

fix: Fix mutable defaults and missing asserts in code

---

src/ansys/fluent/core/codegen/walk_api.py

Add a tool to walk static API classes, already being used for analysing the API through separate code.

feat: Walk API classes

---

src/ansys/fluent/core/post_objects/post_helper.py

Update the delete syntax to get rid of the prompts in visualization.

refactor: Update delete syntax for surfaces.

---

doc/source/user_guide/fields/field_data.rst
tests/test_field_data.py

Update docs and test for field data streaming.

docs: Update docs and test for field data streaming.

---

src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/services/datamodel_tui.py
src/ansys/fluent/core/solver/flobject.py
src/ansys/fluent/core/streaming_services/events_streaming.py
tests/test_datamodel_api.py
tests/test_datamodel_service.py
tests/test_flobject.py
tests/test_mapped_api.py

Corresponding Fluent PR - 549333

fix: some issues in datamodel API tests

---

doc/source/cheatsheet/cheat_sheet.qmd
doc/source/user_guide/fields/field_info.rst

docs: Update field_info docs.

---

src/ansys/fluent/core/post_objects/post_helper.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/session_solver.py

This fixes an issue newly introduced in viz repo due to including "quantity_name" in field info.

fix: field_info for viz.

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.28.0

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.29.dev0

---

tests/test_settings_api.py

As this is an quite important test to keep passing, I'm disabling only the failing code.

test: Enable aliasing test

---

pyproject.toml
src/ansys/fluent/core/_version.py
src/ansys/fluent/core/services/app_utilities.py

build: Bump version to v0.28.1

---

src/ansys/fluent/core/launcher/fluent_container.py
src/ansys/fluent/core/services/datamodel_se.py
tests/test_datamodel_api.py
tests/test_datamodel_service.py

Corresponding Fluent PR - 549351

feat: Send mapped option as grpc metadata

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.29.dev1

---

doc/source/cheatsheet/cheat_sheet.qmd
doc/source/user_guide/solver_settings/set_up/boundary_conditions.rst
doc/source/user_guide/solver_settings/set_up/materials.rst
doc/source/user_guide/solver_settings/set_up/models/battery.rst
doc/source/user_guide/solver_settings/set_up/models/dpm.rst
doc/source/user_guide/solver_settings/set_up/models/energy.rst
doc/source/user_guide/solver_settings/set_up/models/radiation.rst
doc/source/user_guide/solver_settings/set_up/models/species.rst
doc/source/user_guide/solver_settings/set_up/models/viscous.rst
doc/source/user_guide/solver_settings/solution.rst

closes https://github.com/ansys/pyfluent/issues/3651

docs: Update cheatsheet and built-in settings docs [skip-tests]

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.29.dev3

---

src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/services/field_data.py

closes https://github.com/ansys/pyfluent/issues/3664
Get float data for single precision.

fix: Get float mesh data for single precision

---

src/ansys/fluent/core/launcher/fluent_container.py
src/ansys/fluent/core/launcher/launcher.py
src/ansys/fluent/core/utils/deprecate.py
tests/test_launcher.py

closes https://github.com/ansys/pyfluent/issues/3623

fix: Remove `-gu` from command

---

.github/workflows/ci.yml
.github/workflows/test-run-old-versions-weekly.yml
.github/workflows/test-run-wo-codegen-weekly.yml
doc/changelog.d/3683.maintenance.md

closes https://github.com/ansys/pyfluent/issues/3000

chore: Unpin twine version

---

doc/changelog.d/3679.documentation.md
doc/source/user_guide/session/launching_ansys_fluent.rst

closes https://github.com/ansys/pyfluent/issues/2002
As title says

docs: Document how to launch a PIM session

---

doc/changelog.d/3681.miscellaneous.md
src/ansys/fluent/core/streaming_services/monitor_streaming.py

closes https://github.com/ansys/pyfluent/issues/2221

refactor: Update type of parameter

---

doc/changelog.d/3689.documentation.md
doc/source/user_guide/file_transfer.rst

closes https://github.com/ansys/pyfluent/issues/3688

docs: Update file transfer docs for PIM [skip tests]

---

doc/changelog.d/3686.miscellaneous.md
examples/00-fluent/brake.py
examples/00-fluent/lunar_lander_thermal.py
examples/00-fluent/species_transport.py
src/ansys/fluent/core/filereader/case_file.py

closes https://github.com/ansys/pyfluent/issues/2307
example-data PR - https://github.com/ansys/example-data/pull/328

refactor: Update mesh file format

---

doc/changelog.d/3698.documentation.md
doc/source/user_guide/session/launching_ansys_fluent.rst

closes https://github.com/ansys/pyfluent/issues/3126

docs: Update launcher docs [skip tests]

---

doc/changelog.d/3703.documentation.md
src/ansys/fluent/core/codegen/settingsgen.py

closes https://github.com/ansys/pyfluent/issues/3434
**Earlier**
**Now**

docs: Remove parameters section for settings commands [skip tests]

---

doc/changelog.d/3708.documentation.md
doc/source/user_guide/solver_settings/index.rst
src/ansys/fluent/core/services/field_data.py

closes https://github.com/ansys/pyfluent/issues/3706, https://github.com/ansys/pyfluent/issues/3707

docs: Update built-in settings doc and fix doc warnings [skip tests]

---

.github/workflows/ci.yml
doc/changelog.d/3718.fixed.md
doc/source/contributing/index.rst
tests/test_search.py

closes https://github.com/ansys/pyfluent/issues/3717

fix: Update token and contributing doc [skip tests]

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.30.dev0

---

.pre-commit-config.yaml
doc/changelog.d/3726.documentation.md
doc/source/user_guide/fields/field_data.rst
doc/source/user_guide/fields/field_info.rst
doc/source/user_guide/fields/reduction.rst
doc/source/user_guide/fields/solution_data.rst
doc/source/user_guide/file_transfer.rst
doc/source/user_guide/meshing/new_meshing_workflows.rst
doc/source/user_guide/session/launching_ansys_fluent.rst
doc/source/user_guide/transfer_data.rst
src/ansys/fluent/core/utils/file_transfer_service.py

closes https://github.com/ansys/pyfluent/issues/3725

docs: Update launch_fluent snippets [skip tests]

---

.github/labels.yml
doc/changelog.d/3741.maintenance.md

closes https://github.com/ansys/pyfluent/issues/3740

ci: Fix labels [skip tests]

---

doc/changelog.d/3749.miscellaneous.md
src/ansys/fluent/core/post_objects/meta.py

__collection -> _collection for MutableMappings for python 3.13.

refactor: __collection -> _collection for MutableMappings.

---

doc/changelog.d/3757.miscellaneous.md
src/ansys/fluent/core/post_objects/meta.py

Update PyLocalContainer to update _collection.

refactor: Update PyLocalContainer to update _collection.

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.30.dev1

---

pyproject.toml
src/ansys/fluent/core/_version.py

build: Bump version to v0.30.dev2

---

doc/changelog.d/3756.documentation.md
doc/source/contributing/index.rst
doc/styles/config/vocabularies/ANSYS/accept.txt

closes https://github.com/ansys/pyfluent/issues/3755

docs: Update local doc build instructions [skip tests]

---

doc/changelog.d/3770.fixed.md
src/ansys/fluent/core/services/datamodel_se.py
src/ansys/fluent/core/session_meshing.py
src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py
tests/test_meshingmode/test_meshing_launch.py

1197165, 1187804, and getting appropriate error message when user tries to access a wrong settings object.

fix: Minor issues in PyConsole.

---

doc/changelog.d/3776.miscellaneous.md
src/ansys/fluent/core/workflow.py

Remove 'rename' from Enhanced Meshing Workflow top level.
1117231.

refactor: Remove 'rename' from Enhanced Meshing Workflow top level.

---

doc/changelog.d/3780.fixed.md
src/ansys/fluent/core/solver/flobject.py
tests/test_settings_api.py

fix: Fix for nested alias

---

doc/changelog.d/3788.documentation.md
doc/source/user_guide/solver_settings/solver_settings_contents.rst

docs: add solver to example usage command

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.30.dev4

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.30.0

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.31.dev0

---

doc/changelog.d/3824.test.md
src/ansys/fluent/core/solver/flobject.py
tests/test_session.py
tests/test_settings_api.py

Augmenting the test `test_general_exception_behaviour_in_session` with error messages so that we can verify that Fluent error messages are recovered in PyFluent.

test: Test that Fluent error message is recovered in PyFluent

---

doc/changelog.d/3827.added.md
doc/source/user_guide/fields/field_data.rst
src/ansys/fluent/core/services/field_data.py
tests/test_field_data.py

Object based field data access. 
Unifying the interface for transaction based query and direct query.

feat: Object based field data access (unifying the interface).

---

doc/changelog.d/3830.fixed.md
src/ansys/fluent/core/codegen/settingsgen.py
src/ansys/fluent/core/solver/flobject.py
src/ansys/fluent/core/solver/settings_builtin_bases.py
tests/test_codegen.py
tests/test_flobject.py
tests/test_type_stub.py

Fluent bug id - 1224046, will create patch release.

fix: Make version attr private to avoid conflict with child setting with same name.

---

.github/workflows/doc-build-dev-nightly.yml
.github/workflows/execute-examples-weekly.yml
doc/changelog.d/3854.maintenance.md
tests/integration/test_optislang/test_optislang_integration.py
tests/parametric/test_parametric_workflow.py
tests/test_flobject.py
tests/test_reduction.py

closes https://github.com/ansys/pyfluent/issues/3856
1. Updated nightly doc build workflow.
2. Updated examples weekly workflow.
3. Skipped failing tests to update docker image

chore: Update nightly doc build workflow [skip tests]

---

doc/changelog.d/3842.fixed.md
doc/source/api/api_contents.rst
doc/source/user_guide/session/launching_ansys_fluent.rst
src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/launcher/watchdog.py
src/ansys/fluent/core/logger.py
src/ansys/fluent/core/report.py
tests/test_datamodel_service.py

closes https://github.com/ansys/pyfluent/issues/3835
Automate ansys-tools-report.

fix: Get dependency version [skip tests]

---

doc/changelog.d/3874.documentation.md
doc/source/cheatsheet/cheat_sheet.qmd
doc/source/user_guide/meshing/new_meshing_workflows.rst

Update enhanced meshing workflow docs.
Removed duplications and erroneous as well as old usages.

docs: Update enhanced meshing workflow docs.

---

doc/changelog.d/3874.documentation.md
doc/source/cheatsheet/cheat_sheet.qmd
doc/source/user_guide/meshing/new_meshing_workflows.rst

Update docs in the stable release.

build: Release updated doc for v0.30

---

doc/changelog.d/3881.test.md
tests/test_session.py

Correct an issue in testing exception behaviour.

test: Update test.

---

.github/workflows/ci.yml

closes https://github.com/ansys/pyfluent/issues/3898
Fix CI status checks.

ci: Fix status check

---

doc/changelog.d/3893.test.md
tests/integration/test_optislang/test_optislang_integration.py
tests/parametric/test_parametric_workflow.py
tests/test_flobject.py
tests/test_reduction.py

Nightly run with this branch: https://github.com/ansys/pyfluent/actions/runs/14248443110/job/39935185915

test: Enable the tests which are now passing in nightly

---

.github/workflows/ci.yml

closes https://github.com/ansys/pyfluent/issues/3922
Resolve urllib3 unknown license

fix: Resolve urllib3 unknown license [skip tests]

---

doc/changelog.d/3930.miscellaneous.md
tests/test_new_meshing_workflow.py

Update enhanced meshing wf tests w.r.t. docs.

refactor: Update enhanced meshing wf tests w.r.t. docs.

---

doc/changelog.d/3937.fixed.md
tests/test_file_transfer_service.py

@hpohekar This fixes the permission issue locally for me (running docker from within wsl)

fix: Create directory within the current user's home

---

doc/changelog.d/3935.fixed.md
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/services/interceptors.py
src/ansys/fluent/core/session_solver.py
tests/test_session.py

This PR fixes exit scenarios mentioned in the linked issue.
The PR changes make sure the background threads launching Fluent sessions have completed execution before exiting the main session/thread.

fix: Fix for the exit scenario while launching in lightweight mode

---

doc/changelog.d/3941.fixed.md
src/ansys/fluent/core/launcher/fluent_container.py
tests/test_session.py

closes https://github.com/ansys/pyfluent/issues/3942
Update `mount_source` for container file transfer service. This change fixes code style job and local pre-commit hook.

fix: Update mount_source for container FTS [skip tests]

---

doc/changelog.d/3939.fixed.md
doc/changelog.d/3951.fixed.md
src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/filereader/case_file.py
src/ansys/fluent/core/filereader/data_file.py
src/ansys/fluent/core/filereader/pre_processor.py
tests/test_casereader.py
tests/test_reduction.py

Integrate https://github.com/ansys/pyfluent/pull/3951 in 0.30 release

build: Bump version 0.30.4

---

examples/00-fluent/mixing_tank_workflow.py

Adjusted the image dimension for the Mixing Tank Example.

Added the scale attribute to adjust image size.

---

.github/workflows/test-podman-compose.yml
.gitignore
src/ansys/fluent/core/docker/docker_compose.py
src/ansys/fluent/core/launcher/fluent_container.py

closes https://github.com/ansys/pyfluent/issues/4012
Fix Podman workflow.
https://github.com/ansys/pyfluent/actions/runs/14969088008/job/42045701435

ci: Fix Podman workflow

---

doc/changelog.d/4033.added.md
src/ansys/fluent/core/file_session.py
src/ansys/fluent/core/filereader/data_file.py
src/ansys/fluent/core/services/field_data.py
src/ansys/fluent/core/variable_strategies/svar.py
tests/test_file_session.py
tests/test_physical_quantities.py

Extend use of VariableCatalog to include:
- additional pathline field for field data
- off line data files
#4032

feat: Extend use of VariableCatalog

---

doc/changelog.d/4031.test.md
tests/test_new_meshing_workflow.py

Update couple of tests with respect to changes in the exposure level flags to developer.
This has to be merged into the release v0.30 with a patch as well.

test: Update test w.r.t. recent exposure flag changes in data-model.

---

devel/field_level_help/field_level_help.csv
doc/changelog.d/4029.maintenance.md

chore: Fix datatype in field_level_help.csv [skip tests]

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.32.dev1

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.32.0

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.33.dev0

---

doc/changelog.d/4116.miscellaneous.md
src/ansys/fluent/core/codegen/print_fluent_version.py
src/ansys/fluent/core/fluent_connection.py
src/ansys/fluent/core/services/app_utilities.py
src/ansys/fluent/core/services/datamodel_se.py
tests/test_session.py

closes https://github.com/ansys/pyfluent/issues/3885, https://github.com/ansys/pyfluent/issues/3873
1. Update app utilities dict interface.
2. Update datamodelgen integer list.
Tests passed - https://github.com/ansys/pyfluent/actions/runs/15488582185

refactor: Update app utilities dict interface

---

doc/changelog.d/4123.documentation.md
examples/00-fluent/exhaust_system_settings_api.py
examples/00-fluent/external_compressible_flow.py
examples/00-fluent/modeling_cavitation.py

All examples executed successfully.
https://github.com/ansys/pyfluent/actions/runs/15553425335/job/43788444453

docs: Correct a typo [skip tests]

---

.github/workflows/ci.yml
.github/workflows/doc-build-dev-nightly.yml
.github/workflows/doc-build-release.yml
.github/workflows/execute-examples-weekly.yml
.github/workflows/force-update-stable-Fluent-image-version.yml
.github/workflows/test-fluent-journals.yml
.github/workflows/test-run-custom.yml
.github/workflows/test-run-dev-version-nightly.yml
.github/workflows/test-run-nightly.yml
.github/workflows/test-run-old-versions-weekly.yml
.github/workflows/test-run-solvermode-weekly.yml
.github/workflows/test-run-wo-codegen-weekly.yml
Makefile

Remove all unused images, stopped containers, unused networks, build cache and dangling volumes.

ci: Test docker system prune

---

doc/changelog.d/4146.fixed.md
src/ansys/fluent/core/session.py

Fix backward compatibility of health_check.

fix: Backward compatibility of health_check

---

.github/workflows/ci.yml
.github/workflows/doc-build-dev-nightly.yml
.github/workflows/doc-build-release.yml
.github/workflows/execute-examples-weekly.yml
.github/workflows/force-update-stable-Fluent-image-version.yml
.github/workflows/test-fluent-journals.yml
.github/workflows/test-podman-compose.yml
.github/workflows/test-run-custom.yml
.github/workflows/test-run-dev-version-nightly.yml
.github/workflows/test-run-nightly.yml
.github/workflows/test-run-old-versions-weekly.yml
.github/workflows/test-run-solvermode-weekly.yml
.github/workflows/test-run-wo-codegen-weekly.yml
doc/changelog.d/4152.maintenance.md

closes https://github.com/ansys/pyfluent/issues/4151
Resolve unpinned tag security warnings.

ci: Resolve unpinned tag security warnings [skip tests]

---

doc/changelog.d/4166.fixed.md
src/ansys/fluent/core/__init__.py
src/ansys/fluent/core/codegen/builtin_settingsgen.py
src/ansys/fluent/core/solver/flobject.py
tests/test_flobject.py
tests/test_search.py
tests/test_settings_api.py
tests/test_utils.py

Patching https://github.com/ansys/pyfluent/issues/4165's fix to 0.32 release as suggested by Ryan.

build: Bump version 0.32.2

---

.github/workflows/ci.yml
doc/changelog.d/4164.added.md
src/ansys/fluent/core/codegen/builtin_settingsgen.py
src/ansys/fluent/core/solver/__init__.py
src/ansys/fluent/core/solver/settings_builtin_bases.py
src/ansys/fluent/core/solver/settings_builtin_data.py
src/ansys/fluent/core/utils/context_managers.py
tests/test_builtin_settings.py

Add built-in commands at solver level:
```
import ansys.fluent.core as pf
pf.solver.ReadCase(...)
pf.solver.Initialize()
```
TODO: update doc examples

feat: Add builtin commands

---

.github/workflows/ci.yml
.github/workflows/force-update-stable-Fluent-image-version.yml
.github/workflows/test-run-dev-version-nightly.yml
doc/changelog.d/4200.maintenance.md

ci: Delete remove docker image step [skip tests]

---

doc/changelog.d/4201.maintenance.md
tests/test_fluent_fixes.py
tests/test_solver_monitors.py

Add timeout loop in the following tests:
1. test_solver_monitors
2. test_monitors_list_set_data_637_974_1744_2188
Workflow - https://github.com/ansys/pyfluent/actions/runs/15780686928/job/44485332936

ci: Fix nightly dev test run workflow

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.33.0

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.34.dev0

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.34.0

---

doc/changelog.d/4352.documentation.md
doc/source/user_guide/fields/field_vs_svars_data.rst
doc/source/user_guide/fields/fields_contents.rst
doc/source/user_guide/user_guide_contents.rst

This documentation is intended to help users understand when to use each API, avoid common pitfalls, and make informed decisions when accessing field or solution variable data in PyFluent.

docs: Overview and Decision Guide for Field Data vs Solution Variable Data APIs [skip tests]

---

doc/changelog.d/4355.fixed.md
tests/test_session.py

Remove string check of error message.

fix: Remove string check of error message.

---

doc/changelog.d/4362.documentation.md
doc/source/user_guide/legacy/scheme.rst

Fix an erroneous entry in scheme_eval docs.

docs: Fix scheme_eval docs [skip tests]

---

.github/workflows/ci.yml
doc/changelog.d/4373.dependencies.md

Fix release CI to use nightly dev tests again.

build: Fix release CI to use nightly dev tests again.

---

codegen/allapigen.py
doc/changelog.d/4390.fixed.md

fix: Turn on automatic transcript while running codegen

---

doc/changelog.d/4436.fixed.md
examples/00-fluent/single_battery_cell_workflow.py

Disabled the UI mode for the github run

fix: diabled single battery cell simulation ui option

---

doc/changelog.d/4447.maintenance.md
src/ansys/fluent/core/services/__init__.py
src/ansys/fluent/core/session.py

Move Field data streaming to service creator.

chore: Move Field data streaming to service creator.

---

src/ansys/fluent/core/__init__.py

build: Bump version to v0.35.0

---

.github/workflows/ci.yml
doc/changelog.d/4473.maintenance.md
src/ansys/fluent/core/__init__.py

Do not run release testing for dev release.

ci: Do not run release testing for dev release [skip tests]

---

src/ansys/fluent/core/__init__.py

build: Bump version to 0.36.dev0

---

CODEOWNERS
doc/changelog.d/4479.maintenance.md

Add mayankansys to codeowners.

chore: Update CODEOWNERS [skip tests]

---

doc/changelog.d/4520.documentation.md
doc/source/index.rst

**Context:**
Prior to this change, there was no documentation outlining a specific known limitation in the PyFluent codebase. This absence could lead to confusion or misinterpretation by users encountering the limitation, as they lacked clear guidance on the issue.
**Change Summary:**
This update introduces a new documentation entry that explicitly outlines a known limitation within PyFluent. The change involves:
Adding a section in the documentation that describes the limitation in detail.
Providing context and potential workarounds or considerations for users affected by this limitation.
**Rationale:**
By documenting the known limitation, users are better informed about potential constraints they might encounter. This proactive approach helps manage user expectations and provides …

docs: Document a known limitation [skip tests]
