ansys/pyfluent

src/ansys/fluent/core/solver/flobject.py
Removed code duplications in command, query and get_cls.
=> Fix/refactoring flobject.py

codegen/settingsgen.py, src/ansys/fluent/core/services/settings.py, src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py
- Remove deprecated GetObjStaticInfo
- Update GetStaticInfo to include include-child-named-objects and
list-size for fixed sized lists
- Add mixins to create named objects based on user_creatable attribute.
https://tfs.ansys.com:8443/tfs/ANSYS_Development/Portfolio/_workitems/edit/682052
=> static-info enhancement

.github/workflows/ci.yml, codegen/tuigen.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/services/datamodel_tui.py, src/ansys/fluent/core/services/error_handler.py
For 23.1, `GetStaticInfo` rpc will be used for tuigen. I've also reduced the codegen frequency in CI. For 22.2, we shall always restore the generated code from cache (changes are not in the current PR).
=> Use static info for tuigen

doc/Makefile, doc/make.bat, doc/source/conf.py, requirements/requirements_doc.txt
We needed a small code change to update Sphinx, so did it manually here.
You can see this in the automatic build that ran earlier: https://github.com/pyansys/pyfluent/pull/662
=> Update to latest Sphinx version

.github/workflows/ci.yml, Makefile
Only the 22.2 artifacts have been uploaded. ~One concern could be that the CI log is showing all settings API filenames (we should hide any 23.1 solver details).~
=> Run tests and doc build for 23.1 docker

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, Makefile
Elijah reported a couple doc build failures this afternoon:
https://github.com/pyansys/pyfluent/pull/680/checks
https://github.com/pyansys/pyfluent/pull/664/checks
The problem seemed to be that the 'ansys.fluent.core.settings' package was not properly installed into the Python environment at the build step 'Install again after codegen'.  At that point we've already installed the package during the previous step labelled 'Install PyFluent', but without the generated code, and pip does not seem to overwrite it with the updated wheel.   Setting up `make install` to force re-installation does the trick.
I thought what we had agreed about the 23.1 doc builds was that we should just be building it once a day in the nightly doc pipeline, so added it there and removed it from the PR pipeline. …
=> Remove 23.1 doc builds from PR CI/CD pipeline

.github/workflows/tag-iteration-ends.yml
Creating a tag in pyfluent repo on iteration-end dates of Fluent development.
=> Add CI job to tag iteration ends

src/ansys/fluent/core/launcher/launcher.py
Reading cases with large no. of zones from PyFluent consumes too much time/memory as flserver datamodel is enabled in Fluent. Setting the env. var. `APP_LAUNCHED_FROM_CLIENT` (added for lbapp/gpuapp) in Fluent disables the flserver datamodel.
=> Disable flserver datamodel in Fluent

codegen/tuigen.py, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/launcher.py, tests/test_launcher.py, tests/test_launcher_remote.py
Users / Developers will have option to either provide the fluent.exe file path or set the Ansys version manually.
Sample use case:
```
1. 
>>> pyfluent.set_ansys_version(version=pyfluent.FluentVersion.version_23R1)
>>> meshing = pyfluent.launch_fluent(precision="double", processor_count=2, mode="meshing")
2.
>>> pyfluent.set_fluent_path("---path---\fluent.exe")  # provide path in form of string or pathlib.Path
>>> solver = pyfluent.launch_fluent(precision="double", processor_count=2, mode="solver")
```
3.
In a certain case where both "set_ansys_version()" and "set_fluent_path()" are used together, then the path set to fluent.exe will have precedence.
=> Provide users option to set fluent version

src/ansys/fluent/core/meshing/workflow.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session.py, tests/test_pure_mesh_vs_mesh_workflow.py, tests/test_session.py
- update `__dir__` in a few places because some elements are missing where they are attributes of other attributes. The original PR uses `__getattr__` in those places which leaves things missing from `dir()` results. 
- remove some redundant code in meshing/workflow.py
- - add \_\_call\_\_ in MeshingWorkflow class
=> update dir, remove some redundant code

src/ansys/fluent/core/session.py
session._datamodel_service_se() should be available to support backward compatibility.
=> _datamodel_service_se made available

Makefile, pytest.ini, tests/conftest.py, tests/test_solvermode/test_boundaries.py, tests/util/fixture_fluent.py
In this PR we are adding options:
1. To run all unmarked tests along with integration markers during CI job
2. Skip tests based on image tag
We can delete PR #690 once it is merged.
=> Added option to run integration tests along with unmarked tests

examples/00-fluent/mixing_elbow_settings_api.py
I tried creating 2 different scripts for 22.2 and 23.1, but I couldn't find a way to filter them within conf.py (filename_pattern/ignore_pattern in sphinx_gallery_conf are not working).
=> Fix settings API examples for 23.1

README.rst, doc/source/getting_started/index.rst
Git url installation doesn't install the generated API files, nor user will have a way to generate those locally. PyFluent will still work without those generated files but intellisense won't be available in IDEs
=> Remove installation instruction from git url

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, CONTRIBUTING.md, README.rst
After setting up the redirect repos for:
* https://fluentdocs.pyansys.com --> https://fluent.docs.pyansys.com
* https://dev.fluentdocs.pyansys.com --> https://dev.fluent.docs.pyansys.com
It was also necessary to adapt the workflows to the adequate CNAMEs. This should solve the issue.
=> CNAME changed for doc locations

.github/workflows/ci.yml
This is to fix the current hang. Unitests will be run in self-hosted runner. Release build, if needed, will be prepared in github runner.
=> Separate test and build jobs

.github/workflows/ci.yml, Makefile, pytest.ini, tests/test_cad_to_post_ftm.py, tests/test_cad_to_post_wtm.py, tests/test_meshing_workflow.py, tests/test_pure_mesh_vs_mesh_workflow.py
Moving the tests which are running meshing or solver workflows under nightly CI
=> Mark tests between nightly CI and PR runs

.github/workflows/ci.yml, .gitignore, .pre-commit-config.yaml, codegen/datamodelgen.py, codegen/print_fluent_version.py, codegen/settingsgen.py, codegen/tuigen.py, doc/settings_rstgen.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_base_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/utils/fluent_version.py
The string "_222" or "_231" has been appended to the generated API file/directory names. API modules are loaded based on version of the connected Fluent session.
=> Segregate generated files into Fluent-version-specific directories

src/ansys/fluent/core/meshing/workflow.py, tests/test_meshing_workflow.py, tests/test_pure_mesh_vs_mesh_workflow.py, tests/util/meshing_workflow.py
If not properly wrapping TaskObject type itself in the new workflow wrapper then we can get the new CommandArguments functionality via that route as opposed to calling the new task method.
=> fix for meshingworkflow class

requirements/requirements_tests.txt, tests/test_fluent_session.py
Replaced python sdk usage with docker cli in test_fluent_session.py.
=> Replaced python sdk usage with docker cli

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/session.py, tests/test_session.py
The following code was failing:
```
session = pyfluent.launch_fluent()
session.solver.root
```
This seems to be broken after merging the segregration of generated code.
=> Fix root access with old-style session

tests/test_launcher.py
Fix the "test_manual_fluent_version_setting()" to reset the version of fluent after the test.
=> resets the global version variable after test

.github/workflows/ci.yml, .github/workflows/nightly-test-run.yml, Makefile, codegen/tuigen.py, pytest.ini, src/ansys/fluent/core/launcher/fluent_container.py, tests/conftest.py, tests/test_meshing_workflow.py, tests/test_session.py, tests/test_solvermode/test_boundaries.py
This will remove the usage of `FLUET_IMAGE_TAG` env. var. from pytest so that users can run them easily.
=> Add markers for 22.2 or 23.1 tests

tests/test_launcher_remote.py
Please ignore this PR. Creating this only to check the CI behavior for "test_launcher_remote.py"
=> Fix failing test - launch_fluent_remote.py

src/ansys/fluent/core/scheduler/__init__.py, src/ansys/fluent/core/scheduler/machine_list.py, tests/test_scheduler.py
Testing this on SLURM, these small changes to MachineList make the arguments construction a bit more straightforward.  I've added support for `len()` and indexing operation.  The function to build the parallel arguments is added to the main package and is tested.
From here one would need to call these functions in launch_fluent.  I'll try this next.
=> Turn machine lists into Fluent parallel options

doc/source/api/core/solver/settings.rst
root.setup.boundary_conditions.velocity['inlet1'].vmag.constant = 14
changed to - 
root.setup.boundary_conditions.velocity_inlet['inlet1'].vmag.constant = 14
=> Settings example velocity_inlet update

src/ansys/fluent/core/scheduler/load_machines.py, tests/test_scheduler.py
The function will now assume that if no parallel environment is configured then you want to run on the current machine with a single core.
=> Ensure load_machines returns MachineList in all cases

src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/logging.py, tests/test_creatable.py
Single PR to combine 4 flobject.py updates. I have created this branch by merging all changes from the other branches together. I have also diffed it with the latest Fluent version which is also in PR.
=> Feat flobj combined

src/ansys/fluent/core/launcher/fluent_launcher_options.json, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/scheduler/__init__.py, src/ansys/fluent/core/scheduler/load_machines.py
- `processor_count` is removed from the options .json since it's handled by the scheduler module.  Scheduler machine allocations are clamped to this value if it is provided to `launch_fluent` and is _less_ than the total allocated cores.
- `load_machines` always returns a `MachineList` object now.  Previously returned a vanilla list object in some cases which made testing a bit inconvenient.
- If `-tN` or `-cnf=<list>` are provided as `addtional_arguments` to `launch_fluent` then `load_machines` is skipped, allowing for library users to over-ride the automatic treatment.
- Fixed a bug in the scheduler unit tests.  CCP_NODES was not cleaned up in the environment which can lead to subsequent test failures.
=> Activate Job Scheduler in launch_fluent

.ci/compare_flobject.py, .github/workflows/compare-flobject.yml, Makefile
Sample output ([from a test CI run](https://github.com/pyansys/pyfluent/actions/runs/3103707183/jobs/5027335865#step:6:42)):
```
--- fluent_flobject.py	2022-09-13 17:00:29.000000000 +0000
+++ src/ansys/fluent/core/solver/flobject.py	2022-09-22 07:50:55.709520981 +0000
@@ -[14](https://github.com/pyansys/pyfluent/actions/runs/3103707183/jobs/5027335865#step:6:15)5,7 +145,7 @@
"""Get the requested attribute for the object."""
attrs = self.get_attrs([attr])
attrs = attrs.get("attrs", attrs)
-        if attr != "active?" and attrs.get("active?", True) is False:
+        if attr != "active?" and attrs and attrs.get("active?", True) is False:
raise RuntimeError("Object is not active")
return attrs[attr] if attrs else None
File …
```
=> Add nightly CI to compare flobject

tests/test_pro/test_pro_cht.py, tests/test_pro/test_pro_post.py, tests/test_pro/test_pro_settings_pbcs.py, tests/test_pro/test_pro_species.py, tests/test_pro/test_pro_turbulence.py, tests/test_solvermode/test_boundaries.py, tests/util/solver.py
@seanpearsonuk , @mkundu1 , @akulshre-qa , perhaps we can use this branch to fix all the failing nightly test runs?
=> Fix/Nightly test run for 23.1

.pre-commit-config.yaml, doc/settings_rstgen.py, doc/source/api/core/solver/index.rst, doc/source/api/core/solver/schemeeval.rst, src/ansys/fluent/core/services/scheme_eval.py
=> SchemeEval doc

src/ansys/fluent/core/utils/setup_for_fluent.py
`globals["meshing"] = session` is changed to `globals["meshing"] = session.meshing`
=> Updated meshing globals

src/ansys/fluent/core/scheduler/__init__.py
It seems there is trouble starting Fluent on Windows HPC if we pass `-cnf=M:4` when the job is run on machine `M`.   The options builder attempted to filter for this situation already but it was not working because the job scheduler returns upper case host names and the Python `socket` module's `gethostame()` call returns a lower case name.
=> Deal with upper case host names on Windows HPC.

codegen/settingsgen.py, src/ansys/fluent/core/solver/flobject.py
=> Fix 22.2 doc build

src/ansys/fluent/core/launcher/launcher.py
The following pull request aims to provide an option to specify current working directory so Fluent will get launched from the same.
Please check for the following enhancement request
https://github.com/pyansys/pyfluent/issues/969
=> Added current working directory option for launch_fluent API.

.clang-format, .pre-commit-config.yaml
Since we moved the grpc protobuf files out of the core repo we don't need the clang-format stuff running.
=> Not needed since protobuf files were refactored out

doc/source/api/core/meshing/index.rst, doc/source/user_guide/boundary_conditions.rst, doc/source/user_guide/general_settings.rst, doc/source/user_guide/index.rst, doc/source/user_guide/materials.rst, doc/source/user_guide/meshing_workflows.rst, doc/source/user_guide/models.rst, doc/source/user_guide/solution.rst, doc/source/user_guide/solver_settings.rst, doc/source/user_guide/tui_commands.rst, examples/00-fluent/exhaust_system.py, examples/00-fluent/mixing_elbow.py
- Switch from setState to set_state in the meshing workflows documentation
- Run many of the Python code examples through black so they are formatted like the library code
- Use `{}` consistently through the meshing workflow examples
- A little bit of rewrapping of certain paragraphs at 80 columns
=> Some doc cleanups based on feedback from ACE team

.github/workflows/ci.yml, codegen/settingsgen.py, src/ansys/fluent/core/services/settings.py, src/ansys/fluent/core/solver/flobject.py
Corresponsing Fluent PR - 352729
ansys-api-fluent PR - [16](https://github.com/ansys/ansys-api-fluent/pull/16)
=> Execute query in PyFluent

.gitignore
Make it more generic so all the versions are captured.
=> Ignore all the generated API files from all fluent versions

src/ansys/fluent/core/launcher/launcher.py, tests/test_launcher.py
=> Added check for -g and -gu for windows platform

tests/test_session.py
Use random named temporary file to store data from "test_start_transcript_file_write" in test_session.py. This will fix this particular test in the nightly test run.
=> Fix nightly test run.

.github/workflows/ci.yml, Makefile, pyproject.toml
Test coverage html files have been zipped before uploading for the github CI run. This saves a lot of time by not requiring to upload large size files. Along with that a new marker for running tests in only 23.2 has been developed as well.
For now, if we mark a test with "fluent_222" -> it runs only in 22R2, "fluent_231" -> both in 23R1 and 23R2 and "fluent_232" -> only in 23R2.
=> Improve CI run (include marker for 23.2 + zip coverage results).

src/ansys/fluent/core/launcher/launcher.py
Automated scm to py journal creation.
`solver = pf.launch_fluent(mode="solver", topy="myjournal.jou", show_gui=True)`
output file = `myjournal.py`
`---------------------------------------------------------------------------------------------------------------------------------------`
`solver = pf.launch_fluent(mode="solver", topy="myjournal.scm", show_gui=True)`
output file = `myjournal.py`
`---------------------------------------------------------------------------------------------------------------------------------------`
`solver = pf.launch_fluent(mode="solver", topy=["my_jou_1.jou", "my_jou_2.jou"], show_gui=True)`
output file = `my_jou_1_my_jou_2.py`
`------------------------------------------------------------------------------------------------------------------------------------- …
=> Automated scm to py journal creation

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, Makefile, doc/source/conf.py, requirements/requirements_doc.txt
Fix #1132 by:
* Updating to ansys-sphinx-theme==0.8.0
* Enabling version switcher in `doc/source/conf.py` file
* Updating development and stable doc deployment jobs in CI
* The CNAME and .nojekyll file injection through Makefile got removed as this is already being done in pyansys/actions/doc-deploy-*
=> DOC: enable multi-version documentation

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, src/ansys/fluent/core/services/scheme_eval.py, tests/test_scheme_eval_222.py, tests/test_scheme_eval_231.py
We should deploy docs for Fluent 22.2 version as it is currently available to customers.
=> Deploy doc for 22.2

.github/workflows/nightly-doc-build.yml
As per the action logs, https://github.com/pyansys/pyfluent/actions/runs/3710172176/workflow, a syntax error was introduced in #1199. This pull-request fixes the YML file controlling the nightly build workflow.
=> FIX: nigthly build syntax

src/ansys/fluent/core/_version.py
This release is required to get the dependent changes in the UI repo to run seamlessly.
=> Bump version to v0.12.dev9

.ci/compare_flobject.py, .github/workflows/compare-flobject.yml
Now it shows the difference: https://github.com/pyansys/pyfluent/actions/runs/3841749621/jobs/6542324019#step:6:21
=> Fix the CI that compares flobject between server and client

doc/source/conf.py
This should had an icon in the [documentation](https://fluent.docs.pyansys.com/) on the top right corner.
When clicking on this icon, users should be directed to the [discussions](https://github.com/pyansys/pyfluent/discussions).
=> Add an icon in the doc for the pyfluent discussions.

.github/workflows/nightly-test-run.yml, Makefile, pyproject.toml, tests/conftest.py
This will fix the issue in running tests with some Fluent versions.
=> Fluent version markers

doc/source/contributing.rst
Fixed the broken links in the Contributing Page. Now, they redirect to their corresponding webpages.
=> Fixed links in the Contributing Page

.github/workflows/ci.yml, src/ansys/fluent/core/_version.py
Merging @alikasim72's PR #1273 changes to fix the release documentation. 
I accidentally pushed the v0.12.2 tag before updating the version in code, so I've incremented once more.
=> Bump version v0.12.3

README.rst
=> Point to the proper location for PyFluent Results

README.rst, codegen/allapigen.py, codegen/tuigen.py, doc/source/api/launcher.rst, doc/source/getting_started/faqs.rst, doc/source/getting_started/installation.rst, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/utils/setup_for_fluent.py, tests/test_launcher.py, tests/test_launcher_remote.py
From #1262:
We now have the following 3 options to specify Fluent launch path from PyFluent:
1. default - via AWP_ROOT env vars
2. user override - via the product_version param in launch_fluent
3. developer override - via PYFLUENT_FLUENT_ROOT env var
Other options are redundant and have been removed.
=> Remove set_ansys_version and set_fluent_exe_path methods

doc/source/conf.py
Fixes #1290 by adding the `https` prefix in the `json_url` parameter for the multi-version dropdown menu.
Note this fixes `dev` one the nightly docs are deployed. However, for `12.3`, this changes need to be cherry-picked.
=> FIX: missing https prefix in json_url parameter

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/utils/fldoc.py
=> Format lists within pydoc

.pre-commit-config.yaml
We are experiencing this failure in most of the PRs.
=> Updated isort version to avoid pre-commit.ci failure.

tests/test_session.py
The test `test_start_transcript_file_write` is randomly failing probably due to server to holding the file while the client tries to read it. Change to check for file modification instead of file content.
=> Check for file modification in test

requirements/requirements_doc.txt
Downgrade Sphinx to 5.3.0 to fix the built documentation (and by effect fix the multi-version switcher) and prevent ansys-sphinx-theme from breaking.
=> downgrade sphinx

codegen/data/fluent_gui_help.xml, src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py, tests/test_session.py
Fluent bugs 774607, 774755, 774903
For all these defects, `is_active()` returns a list from Fluent for which we need to cast to boolean type in PyFluent. There are many such occurrences in Fluent code, it is probably not possible to find and change the Fluent code everywhere.
=> Fix is_active checks

src/ansys/fluent/core/launcher/fluent_launcher_options.json, src/ansys/fluent/core/launcher/launcher.py
We split things up inside launch_fluent to invoke the API after the server is launched.
=> Split reading case from launch fluent process.

doc/source/conf.py
It is possible to turn off the expandable navigation entirely by setting the collapse_navigation config option to `True`:
```py
html_theme_options = {
"collapse_navigation": True
}
```
This tends to help improve documentation build times.
See: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/navigation.html
=> Turn off the expandable navigation 

setup.py, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/services/batch_ops.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/services/datamodel_tui.py, src/ansys/fluent/core/services/field_data.py, src/ansys/fluent/core/services/health_check.py, src/ansys/fluent/core/services/interceptors.py, src/ansys/fluent/core/services/monitor.py, src/ansys/fluent/core/services/scheme_eval.py, src/ansys/fluent/core/services/settings.py, tests/test_batch_ops.py
Example usage:
```
solver = pyfluent.launch_fluent()
with pyfluent.BatchOps(solver):
solver.tui.file.read_case("elbow.cas.h5")
solver.solution.initialization.hybrid_initialize()
```
Above 2 will be executed through a single grpc call. Only methods with batchable option in proto files are supported.
Proto file batch execution is in https://github.com/ansys/ansys-api-fluent/pull/24
I'll add unittests.
=> Execute rpcs in batch

src/ansys/fluent/core/fluent_connection.py
Stop all the streaming services before exiting the active channel on which fluent is running. This was the issue for 'pyfluent' hanging during exit immediately after initialization as reported by @mkundu1 .
=> Stop streaming services before exiting channel.

src/ansys/fluent/core/filereader/case.py, tests/test_casereader.py
If the config-vars gets a key-error, we return the closest matching names along with the error message.
=> Suggest closest matching names for config-vars error.

.github/workflows/ci.yml, tests/test_session.py
We should remove any 23.2 API files from package, github cache etc. In this PR, I've removed the 23.2 files from the package artifact. The 23.2 build is prepared and unittested under a separate job which doesn't use github cache. 
I'm preparing an internal repo [pyfluent-dev](https://github.com/pyansys/pyfluent-dev) from where we will internally release a package with the 23.2 files.
=> Remove 23.2 API files from package/cache

src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py, src/ansys/fluent/core/workflow.py, tests/test_datamodel_service.py
Example:
`subscription1 = meshing.workflow.add_on_child_created("TaskObject", lambda obj: print(obj.path))`
The datamodel event streaming service is activated by default. Each callback registration will subscribe the corresponding event to the server and add the callback function to `datamodel_event_streaming.py::DatamodelEvents` instance. The callback function gets executed when a matching event is streamed from server. The event is matched using a string tag which is computed in the server during the event subscription. The callback registration returns a `datamodel_se.py::EventSubscription` instance. `subscription1.unsubscribe()` will unsubscribe the event in server and remove the callback function from `DatamodelEvents` instance.
=> Datamodel event callback registration

.github/workflows/nightly-dev-doc-build.yml
I think this is why the `dev` link is broken, the `doc/_build/html` part of the path is messing up finding the index.html.
=> Remove path from zipped doc archive

.github/workflows/nightly-dev-doc-build.yml
Zip up the html doc from the build area.
=> Doc can't have the doc/_build/html path

.github/workflows/ci.yml
Use the tagged zip file name and strip doc/_build/html path as that cannot go into the github pages branch.
=> Fix up release doc pipeilne

.github/workflows/test-run-wo-codegen.yml
As in our code we support all pyfluent workflows even when the API files aren't generated through codegen, I'm adding this CI to keep testing the generic code we have for when the API files aren't present. The CI will be run every Monday and Thursday.
=> Add CI to run unittests without codegen

src/ansys/fluent/core/utils/dump_session_data.py
Added functionality to read dump session data. This is required in the UI repo to get the field data.
=> Add method to read dump session data.

src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/workflow.py
Primarily to be consistent with PyConsole, we expose is_read_only for objects, not just parameters. This has been reported erroneously as a Fluent bug - hence no linked issue here right now.
=> readonly objects method

src/ansys/fluent/core/streaming_services/transcript_streaming.py
We were getting a null string from server in transcript which was not handled.
=> Handle null string in transcript.

codegen/datamodelgen.py, codegen/tuigen.py, doc/source/api/general/case_reader.rst, doc/source/api/general/data_transfer.rst, doc/source/api/general/sessions/Meshing/index.rst, doc/source/api/general/sessions/Meshing/session_base_meshing.rst, doc/source/api/general/sessions/Meshing/session_meshing.rst, doc/source/api/general/sessions/Meshing/session_pure_meshing.rst, doc/source/api/general/sessions/Session/fluent_connection.rst, doc/source/api/general/sessions/Session/index.rst, doc/source/api/general/sessions/Session/session.rst, doc/source/api/general/sessions/Solver/index.rst, doc/source/api/general/sessions/Solver/session_solver.rst, doc/source/api/general/sessions/Solver/session_solver_icing.rst, doc/source/api/general/sessions/Solver/session_solver_lite.rst, doc/source/api/general/sessions/index.rst, doc/source/api/general/utils/index.rst, doc/styles/Vocab/ANSYS/accept.txt, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/filereader/case.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_base_meshing.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/session_solver_icing.py, tests/test_session.py
1. Resolved  https://github.com/pyansys/pyfluent/issues/1484 **n.b. this has since been updated to `CaseFile` following conflict resolution**
`----------------------------------------------------------------------------`
2. Resolved  https://github.com/pyansys/pyfluent/issues/1465
`----------------------------------------------------------------------------`
3.  Resolved  https://github.com/pyansys/pyfluent/issues/1457
`----------------------------------------------------------------------------`
4. Resolved  https://github.com/pyansys/pyfluent/issues/1453
`----------------------------------------------------------------------------`
5. Resolved  https://github.com/pyansys/pyfluent/issues/1456
`----------------------------------------------------------------------------`
6. Resolved …
=> Resolved doc issues

src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/streaming_services/transcript_streaming.py, tests/test_fluent_session.py
transcript.start()  # write to stdout only
transcript.start(file_path="a.trn")  # write to file only
transcript.start(file_path="a.trn", write_to_stdout=True)  # write to both file and stdout
=> Fix transcript behavior.

README.rst, doc/source/contributing.rst, doc/source/index.rst, setup.py
In doing a search of the repo, I found two more occurrences of pyansys.supoprt@ansys.com in pyfluent\src\ansys_fluent_core.egg-info\PKG-INFO, lines 7 and 61. However, I didn't know if these email addresses would somehow get updated to pyansys.core@ansys.com when the changes I made within the other repo files were updated. Please advise.
=> Edit support email address

tests/test_flobject.py, tests/test_settings_api.py
There is a recent change in Fluent to hide case-settings in settings API before case is read. We need to update pyfluent unittests for that.
=> Fix failing CI run due to settings api update.

tests/test_flobject.py
This tests the availability / behavior of accessor methods like: is_active, is_read_only, min, max, default_value and allowed_values, on settings objects of all types.
=> Added test for accessor methods in flobject.py

src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
```
>>> [x for x in solver.setup.boundary_conditions.velocity_inlet]          
['inlet2', 'inlet1']
>>> [x for x in solver.setup.boundary_conditions.velocity_inlet['\*let*']]
TypeError: 'WildcardPath' object is not iterable
```
The above behavior is fixed.
Similar changes have been applied on the PyConsole side as well.
=> Fix bug in wildcard - flobject.py

README.rst, doc/source/getting_started/faqs.rst, doc/source/getting_started/installation.rst, setup.py
=> Update python version

src/ansys/fluent/core/launcher/launcher.py
Minor change. While testing different Fluent releases, I got this error message:
However, Fluent version 24.1 does exist in my machine, so I got confused for a second there. I believe what the original dev meant is that it is not yet supported by pyfluent.
With the proposed changes, the message now reads:
Additional thought probably for a different PR: do we need to block the execution of more recent versions than the latest fully supported Fluent release? Shouldn't more recent versions (always? usually?) work fine from now on? Perhaps just a warning that the recent/dev version is untested and subject to potential issues?
=> Slight rewording change for version check

.github/workflows/nightly-dev-doc-build.yml, .github/workflows/release-doc-build.yml, doc/source/conf.py
This pull-request fixes the latest issues with the multi-version documentation by:
- Updating to the latest pyansys/actions@v4
- Updating the location of the `versions.json` file
These changes allow to have a `stable` URL for the latest stable documentation.
=> FIX: multi-version documentation

.ci/pull_fluent_image.sh, .github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, .pre-commit-config.yaml, Makefile, codegen/tuigen.py, doc/source/conf.py, requirements/requirements_doc.txt, src/ansys/fluent/core/_version.py, src/ansys/fluent/core/launcher/fluent_container.py, tests/test_pure_mesh_vs_mesh_workflow.py
The changes from release/0.11.1 which originally added the multi-version support were not merged into release/0.11 - merging those changes first. There is no [pypi package](https://pypi.org/project/ansys-fluent-core/#history) for 0.11.1, I'll push that too.
=> Fix multi-version documentation

README.rst
Improving the documentation in `README.rst` of the `AWP_ROOT` env variable required to run it on Linux, as the required env variable is not set automatically, with examples. 
Also took this opportunity to streamline and move the Windows env var documentation from the 'Launching fluent' heading to the 'Dependencies' heading, together with the Linux documentation.
edit: also removed the link to the FAQs "for more information about Fluent location", as I didn't find anything there that adds to the readme for this
=> Improving Linux usage documentation

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/examples/downloads.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/launcher/launcher.py
Resolves issue https://github.com/ansys/pyfluent/issues/1588 for pyfluent
Changes the point of creation of the data and examples paths from when pyfluent is first imported, to when the example files are downloaded.
In addition, before these changes Windows was saving to `%LocalAppData%\ansys_fluent_core\ansys_fluent_core\example`, after these changes it will save to `%LocalAppData%\Ansys\ansys_fluent_core\example`. The root directory `%LocalAppData%\Ansys` is already created when installing Ansys Fluent releases on Windows.
These changes do not influence the default data paths on Linux, only changes them on Windows.
To make things easier for CI/testing or other purposes in the future, we could make `__init__.py` check for an existing env variable for the data paths, like I noticed …
=> Update to Windows data path name, and change to when examples folder is created

src/ansys/fluent/core/launcher/launcher.py, tests/test_launcher_remote.py
"launch_remote_fluent" does not use the "get_ansys_version()" as a corrected behavior. Instead, we use the product version provided as launch argument. If product version is not set, we use the version "latest".
=> Fix product version in launch remote fluent.

src/ansys/fluent/core/_version.py
Need this patch release to fix pyfluent-visualization and pyfluent-parametric nightly doc build which is failing because it is looking for the docker image in old pyansys org link.
=> Bump version 0.14.dev2

.github/workflows/ci.yml
This change is causing a failure in the package release. I don't see the link is changed in any other repo.
=> Fix azure pypi link

doc/settings_rstgen.py
Exposed base class in settings doc.
=> Expose base class in settings doc

.github/workflows/ci.yml, tests/test_session.py
`tests/test_streaming_services.py::test_transcript` has been randomly failing on github test runners, likely due to it being a server-side stress test, and this has been blocking PRs
Examples where it first failed, then passed on re-run without any changes:
https://github.com/ansys/pyfluent/actions/runs/5082325343/jobs/9131963505?pr=1640
https://github.com/ansys/pyfluent/actions/runs/5082183987/jobs/9131631586?pr=1639
https://github.com/ansys/pyfluent/actions/runs/5016027626/jobs/8992408253
As @mkundu1 suggested, one possible way to deal with this is to use a better runner, and that is what this PR is doing by changing it to a self-hosted pyfluent runner
If it continues randomly failing we will have to rework this test
CC: @prmukherj 
update: `tests/test_session.py::test_journal_creation` …
=> Attempt to fix tests that are randomly failing

src/ansys/fluent/core/launcher/launcher.py, tests/test_launcher_remote.py
Follow-up to #1604 for the fix for #1591 This is just a small adjustment, I was out so I missed the review, but thank you for the quick fix @prmukherj
When the user does not explicitly request for a version, then `None` should be used. `latest` is not a standard name for a version so it will likely not be available. Leaving `None` will let the backend choose. I will add a note on this in the `pypim` documentation, at the moment it's only explain in the `.proto` I believe.
=> Remote launcher: don't provide any product version by default

tests/test_session.py
For `tests/test_session.py::test_journal_creation`
<details> <summary>Example logs where it had failed recently</summary>
https://github.com/ansys/pyfluent/actions/runs/5091062246/attempts/1
https://github.com/ansys/pyfluent/actions/runs/5082325343/jobs/9132695993
https://github.com/ansys/pyfluent/actions/runs/5082965763/jobs/9133417557?pr=1641
https://github.com/ansys/pyfluent/actions/runs/5133184035/jobs/9235563372
https://github.com/ansys/pyfluent/actions/runs/5134366673/jobs/9239139341?pr=1656
</details>
Managed to reproduce the issue locally: my understanding is that the Fluent v232 process inside the docker container image, when editing journal files, sometimes only changes the size of the file without changing the modification time for whatever reason. 
I previously tried adding …
=> "Actually" fixing journal creation test, hopefully for the last time

src/ansys/fluent/core/launcher/launcher.py
This is useful while launching the Fluent docker container from PyFluent in Windows host for development purpose. We cannot mount a Windows path within the Linux container.
=> Set container mount path from env var

.github/workflows/ci.yml
This will potentially fix failures of some resource-intensive tests in github.
=> Use self-hosted runners for all unittests

doc/source/user_guide/index.rst, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/logging.py, tests/test_svars.py
Related to https://github.com/ansys/pyfluent/issues/1679
Alternate way to initialize logging, cleaning up `__init__.py` a little bit.
=> Alternate way to initialize logging

.github/workflows/ci.yml, tests/test_streaming_services.py
Based on `test_transcripts` changes by @mkundu1 from https://github.com/ansys/pyfluent/pull/1701, but instead branched from feat/watchdog to make use of the watchdog functionality, with an additional  `time.sleep()` as a potential fix
Currently testing this fix, running repeated tests locally and on github runners
The objective is to make this test take as little time as possible, while not failing
Update: has passed 100 tests with no failures, while failing approx. 2 out of every 20 tests before (on my local machine, apparently failed a lot more often on GitHub)
Update 2: also, considering we are now identifying and fixing what has been causing tests to fail, we should be able to go back to running as many tests as we can on GitHub runners, rather than self-hosted, to speed up our CI …
=> reverting #1677 and attempting test_transcripts fix

.github/workflows/ci.yml, codegen/tuigen.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/watchdog.py, src/ansys/fluent/core/logging.py, src/ansys/fluent/core/session.py, tests/test_fluent_session.py, tests/test_streaming_services.py
Update: zero stray containers left on the GitHub CI runners after going through all tests multiple times (before would leave around 2 to 15 stray Fluent containers each run)
By default, Watchdog will only be started when Fluent is launched with `show_gui=False`, or with `start_watchdog=True`
For debugging, set `PYFLUENT_LOGGING=DEBUG` (for PyFluent) and `PYFLUENT_WATCHDOG_DEBUG=ON` (for the Watchdog)
Common situations that leave lots of stray Fluent processes behind include: 
- When running PyFluent tests that open and close many Fluent connections in quick succession (e.g. our CI runs on GitHub)
- Cancelling GitHub CI runs (automatically when for example a new commit is made while previous tests were running, or manually when cancelling workflows)
- When closing the window or terminal …
=> Watchdog to deal with Fluent stray processes

doc/source/_templates/noindex-base.rst, doc/source/_templates/noindex-class.rst, doc/source/_templates/noindex-module.rst, doc/source/api/solver/events.rst, doc/source/api/solver/fielddata.rst, doc/source/api/solver/fieldinfo.rst, doc/source/api/solver/monitors.rst, doc/source/api/solver/schemeeval.rst, src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/logging.py, src/ansys/fluent/core/services/health_check.py, src/ansys/fluent/core/services/meshing_queries.py, src/ansys/fluent/core/services/streaming.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_base_meshing.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/session_solver_icing.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/function/reduction.py, src/ansys/fluent/core/workflow.py
1. Fixing most of the
`SS02: Summary does not start with a capital letter`
`SS03: Summary does not end with a period`
`RT02: The first line of the Returns section should contain only the type, unless multiple values are being returned`
`GL07: Sections are in the wrong order`.
Among the remaining ones, most are due to missing docstrings:
175 `GL08: The object does not have a docstring` warnings and 24 `SS01: No summary found` warnings
2. Fix warnings due to duplicate indices like `pyfluent\src\ansys\fluent\core\services\field_data.py:docstring of ansys.fluent.core.services.field_data.FieldData:1: WARNING: duplicate object description of ansys.fluent.core.services.field_data.FieldData, other instance in api/general/services/field_data, use :noindex: for one of them`
=> Fix some issues in the existing docstrings

.github/workflows/nightly-dev-doc-build.yml, codegen/datamodelgen.py, codegen/tuigen.py
[Current list of warnings](https://github.com/ansys/pyfluent/actions/runs/5351692657/jobs/9705814458) in the full documentation build with these changes - mostly the missing docstrings in PyFluent source.
There are some already existing issues related to the indices, I'll try to address them in #1710
=> Fix warnings due to duplicate indices in TUI and datamodel doc

doc/source/api/general/rpvars.rst, doc/source/conf.py, src/ansys/fluent/core/rpvars.py
Closes https://github.com/ansys/pyfluent/issues/1631 and https://github.com/ansys/pyfluent/issues/1714
Currently, in [API reference](https://fluent.docs.pyansys.com/version/stable/api/index.html), clicking on General -> `rpvars` takes us to [this almost empty page ](https://fluent.docs.pyansys.com/version/stable/api/general/rpvars.html), clicking on `rpvars` again takes us to [another almost empty page](https://fluent.docs.pyansys.com/version/stable/api/general/_autosummary/ansys.fluent.core.rpvars.html#module-ansys.fluent.core.rpvars), and clicking once again on `RPVars` finally takes us to the [documentation page](https://fluent.docs.pyansys.com/version/stable/api/general/_autosummary/ansys.fluent.core.rpvars.RPVars.html#ansys.fluent.core.rpvars.RPVars). 
Changed it so that the first …
=> fix rpvars doc

doc/source/api/general/quantity.rst, doc/source/api/meshing/index.rst, doc/source/api/solver/index.rst, doc/source/api/solver/settings.rst, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/quantity/dimensions.py, src/ansys/fluent/core/quantity/quantity.py, src/ansys/fluent/core/quantity/quantity_map.py, src/ansys/fluent/core/quantity/units_table.py, src/ansys/fluent/core/solver/flobject.py
Closes https://github.com/ansys/pyfluent/issues/1634, also related to https://github.com/ansys/pyfluent/issues/1690
`doc\source\api\solver\settings.rst` has new links specific for `settings_231` files, which will need to be manually (unless we automate this) updated for `settings_232` once we update the doc deployment version in the GitHub workflows.
=> Additional fixes for docs version v231

src/ansys/fluent/core/_version.py
Creating a dev release to include 23.2 API files in the package, will be followed by a public release.
=> Bump version 0.16.dev2

tests/test_fluent_session.py
Fixing logic in `test_does_not_exit_fluent_by_default_when_connected_to_running_fluent`. 
When running without `PYFLUENT_TIMEOUT_FORCE_EXIT`, this test was leaving Fluent zombies every single run, due to a small logic error: `cleanup_on_exit=False` is the opposite of what we want on `session1` (and also disables the Watchdog for that run, guaranteeing zombies). 
With this change, the test is also closer to its stated intent: testing the *default* behavior of both `launch_fluent` (which is `cleanup_on_exit=True`) as well as `connect_to_fluent` (which is `cleanup_on_exit=False`)
=> test_does_not_exit_fluent_by_default_when_connected_to_running_fluent

codegen/tuigen.py, src/ansys/fluent/core/launcher/watchdog.py
Adding exception catch to Watchdog module that writes to a `pyfluent_watchdog.err` file if it catches anything, and additional logging calls
Edit: regardless of diagnosing the user issue, I think these changes should be merged into main, as they may be helpful in the future, going to mark this PR ready for review. 
The changes to `watchdog.py` file are hard to understand on GitHub, but are mainly just tabbing everything to the right to add a `try except` block to log any exceptions:
https://github.com/ansys/pyfluent/blob/df18ceee7e14cc9a72fc2cfd566ada4c12be47f7/src/ansys/fluent/core/launcher/watchdog.py#L298-L300
=> Minor watchdog improvements (helping user diagnose issue)

src/ansys/fluent/core/session_solver_icing.py
get_fluent_version() can be accessed from 'Solver'
Thank You @seanpearsonuk, for mentioning the specific commit that was causing this issue :).
=> Remove redundant 'get_fluent_version()'

src/ansys/fluent/core/launcher/launcher.py, tests/test_launcher.py
Fixes https://github.com/ansys/pyfluent/issues/1769
Removing support for `launch_fluent(server_info_filepath=...)` as it does not make much sense to support it considering that the file will be deleted by Fluent when it exits, regardless of what we do in PyFluent.
Raising `ValueError` exceptions if arguments are provided in unsupported combinations. Might've missed a few but I think I at least got the most important ones, please let me know (or directly commit) if you notice any missed combinations.
=> Revising fluent launch arguments

src/ansys/fluent/core/launcher/launcher.py
Fixes https://github.com/ansys/pyfluent/issues/1790, which is the test failure reason for PR https://github.com/ansys/pyfluent/pull/1789
=> Lowering Exception to a warning when invalid arguments are specified for launch_fluent

src/ansys/fluent/core/examples/downloads.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/utils/data_transfer.py, tests/test_casereader.py, tests/test_fluent_session.py, tests/test_launcher.py, tests/test_session.py, tests/test_streaming_services.py, tests/test_tui_api.py
Better default support for Fluent Docker containers on Windows, fixes https://github.com/ansys/pyfluent/issues/1793 and https://github.com/ansys/pyfluent/issues/1798
Fixing and updating tests as well for v241
With these changes, we should be able to run all (most?) tests on Windows and they should all work properly, same as in Linux, by just running `pytest`, e.g. `pytest -v -m "dev and fluent_241"`. Note that the only test that needs to have Docker containers set up on the system is `tests/test_launcher.py::test_container_launcher`, everything else will run on whatever the system is currently set up to run by default (i.e., local standalone Fluent or Docker container Fluent image).
Other changes:
- Reworked `utils.data_transfer` so that it better supports containers
- Added new test …
=> Better default support for Fluent Docker containers on Windows

src/ansys/fluent/core/filereader/lispy.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/watchdog.py, src/ansys/fluent/core/services/interceptors.py, tests/util/fixture_fluent.py
Replacing all string formatting in f-string format.
=> Replace redundant string formatting

.github/workflows/ci.yml, .github/workflows/run-custom-tests.yml, tests/parametric/test_parametric_workflow.py
Test run result - https://github.com/ansys/pyfluent/actions/runs/5559483041
=> Enable parametric test for 24.1

doc/source/api/meshing/index.rst
Fix for https://github.com/ansys/pyfluent/issues/1796
=> Removing deprecated meshing.meshing documentation

src/ansys/fluent/core/solver/flobject.py
Added latest remove dunders changes.
=> Update flobject.py (remove dunders changes)

src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/services/datamodel_tui.py, src/ansys/fluent/core/services/interceptors.py
Minor suggestion to have debug logs that are much easier to work with, and not overwhelmed by gRPC calls that pass millions of characters or with multiple line breaks each time. Partially addresses https://github.com/ansys/pyfluent/issues/1800 from the logging point of view (but I don't know if passing such gigantic gRPC calls so often is intentional or desired). 
<details><summary> Before </summary>
Fluent root settings API call
```
2023-07-19 16:39:20,210 pyfluent.networking   DEBUG    GRPC_TRACE: rpc = /ansys.api.fluent.v0.settings.Settings/GetStaticInfo, request = {'root': 'fluent'}
2023-07-19 16:39:22,301 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'info': ... <2.2 MILLION CHARACTERS> ... }
```
TUI call
```
2023-07-19 16:39:10,286 pyfluent.tui          DEBUG    TUI …
```
=> Reworking gRPC and TUI debug logging

Makefile, tests/test_streaming_services.py
Closes https://github.com/ansys/pyfluent/issues/1802, will test a few times to see if it is now stable with recent changes and `tty=False`
Run 1: https://github.com/ansys/pyfluent/actions/runs/5622916297/job/15236570566 - passed
Run 2: https://github.com/ansys/pyfluent/actions/runs/5623577620/ - passed
Run 3 Custom: https://github.com/ansys/pyfluent/actions/runs/5623587862 - passed
Run 4 Custom:  https://github.com/ansys/pyfluent/actions/runs/5623868338 - passed
Run 5 Custom: https://github.com/ansys/pyfluent/actions/runs/5624340868 - passed
=> Re-enabling test_transcript

examples/README.txt
Changes
---------
Closes #1788 
- Adds link to [pyfluent-examples](https://github.com/ansys/pyfluent-examples) repo within pyfluent docs.
=> feat: pyfluent-examples doc link

src/ansys/fluent/core/examples/__init__.py, src/ansys/fluent/core/examples/downloads.py, tests/integration/test_optislang/test_optislang_integration.py, tests/test_rp_vars.py, tests/test_uploader.py
Added `path` function to check existence of valid file name.
```
>>> import ansys.fluent.core as pyfluent                                                  
>>> from ansys.fluent.core import examples
>>> filepath = examples.path("elbow_param.cas.h5")
Traceback (most recent call last):                                                       
File "<stdin>", line 1, in <module>                                                    
File "D:\Repos\pyfluent\src\ansys\fluent\core\examples\downloads.py", line 141, in path
raise FileNotFoundError(f"{filename} does not exist.")                               
FileNotFoundError: elbow_param.cas.h5 does not exist.                                    
>>> case_filename = examples.download_file("elbow_param.cas.h5", "pyfluent/mixing_elbow")
Checking if …
```
=> PyFluent Example File Path

pyproject.toml, tests/conftest.py, tests/parametric/test_parametric_workflow.py, tests/test_meshingmode/test_meshing_launch.py, tests/test_solvermode/test_boundaries.py, tests/test_solvermode/test_calculationactivities.py, tests/test_solvermode/test_controls.py, tests/test_solvermode/test_general.py, tests/test_solvermode/test_initialization.py, tests/test_solvermode/test_materials.py, tests/test_solvermode/test_methods.py, tests/test_solvermode/test_models.py, tests/test_solvermode/test_named_expressions.py, tests/test_solvermode/test_post_vector.py
This will fix 23.1 nightly failure - https://github.com/ansys/pyfluent/actions/runs/5676374753/job/15383014718#step:24:1229
=> Move the Fluent API tests to run with 24.1 Fluent version

src/ansys/fluent/core/examples/__init__.py, src/ansys/fluent/core/examples/downloads.py
Implemented suggestions given by @mkundu1 and @raph-luc 
```
>>> from ansys.fluent.core import examples                      
>>> filepath = examples.path("elbow_param.cas.h5")
File "D:\Repos\pyfluent\src\ansys\fluent\core\examples\downloads.py", line 144, in path
raise FileNotFoundError(f"{filename} does not exist.")
FileNotFoundError: elbow_param.cas.h5 does not exist.
>>> path = examples.download_file("elbow_param.cas.h5", "pyfluent/mixing_elbow")
Checking if specified file already exists...
File does not exist. Downloading specified file...
Download successful. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\elbow_param.cas.h5
>>> path …
```
=> Example file path update

tests/test_flobject.py, tests/test_settings_api.py
lst.sort() sorts the original lst, the function doesn't return anything.
sorted(lst) returns a sorted copy of the original lst.
In a few tests in test_flobject.py and test_settings_api.py, lst.sort() is used to compare lists.
=> sort() to sorted()

.github/workflows/ci.yml, .github/workflows/run-custom-tests.yml, Makefile, tests/conftest.py, tests/integration/test_optislang/test_optislang_integration.py, tests/parametric/test_parametric_workflow.py, tests/test_batch_ops.py, tests/test_creatable.py, tests/test_flobject.py, tests/test_fluent_fixes.py, tests/test_fluent_session.py, tests/test_fluent_version_marker.py, tests/test_meshingmode/test_meshing_launch.py, tests/test_reduction.py, tests/test_rp_vars.py, tests/test_settings_api.py, tests/test_solvermode/test_boundaries.py, tests/test_solvermode/test_calculationactivities.py, tests/test_solvermode/test_controls.py, tests/test_solvermode/test_general.py, tests/test_solvermode/test_initialization.py, tests/test_solvermode/test_materials.py, tests/test_solvermode/test_methods.py, tests/test_solvermode/test_models.py, tests/test_solvermode/test_named_expressions.py, tests/test_solvermode/test_post_vector.py
I have identified some tests to move to nightly based on the fact that the client-side code covered by these tests is very minimal and stable (exercising settings API, flobject.py or stable APIs like the batch operation, reduction services). These are basically testing the server-side APIs.
Additional thoughts:
1. The tests for fielddata and svars services are also calling settings API. But as these services have been developed recently and contain some wrapper code on the client side, I haven't moved them to the nightly, but let me know whether we should move them too.
2. Another idea is to run the settings API tests with Fluent <=23.2 during PRs but run them with Fluent 24.1 nightly. But I think settings API tests with Fluent 23.2 won't be impacted by PyFluent changes except for changes …
=> Mark some tests to nightly

.github/workflows/nightly-dev-doc-build.yml, .github/workflows/release-doc-build.yml
As discussed with Roberto and Jorge, this will avoid generating the actions_github_pages_* folders on self-hosted runners which is causing disk space to run out.
I'll make this change in other repos after testing.
=> Deploy documentation from github runner

src/ansys/fluent/core/quantity/_constants.py, src/ansys/fluent/core/quantity/quantity.py, src/ansys/fluent/core/quantity/tables.py, tests/test_units/test_quantity.py
Copy of more PyUnits changes
This is one more bug fix. In fact it's number 7 here: https://github.com/ansys/pyunits/issues/25.
This one is subtler and more debatable than the others, We have added two tests (see test_quantity.py). The already-passing test is where we explicitly convert to e.g., `delta_C`. But if we have a temperature-difference-like quantity, it is also not correct to convert that quality away. 
Note that none of this is rigorous but it is the best we can do within the current framework. The issue is that we can label a whole quantity as either Temperature or Temperature Difference if it contains a component of that type. But what if it contains both? We are unable to handle that situation correctly due to this coarse-grained labelling. 
EDIT:
Added more tests -  the …
=> bug fixes as in PyUnits

setup.py, src/ansys/fluent/core/services/health_check.py, src/ansys/fluent/core/utils/networking.py, tests/test_session.py
Using the standard package to get health_pb2 and health_pb2_grpc will avoid clashing with other libraries using the standard package.
=> Use standard grpc-health-checking package

doc/source/api/general/index.rst, doc/source/api/general/logging.rst, doc/source/user_guide/index.rst, src/ansys/fluent/core/logging.py
Closes #1935 
Mainly improvements to the documentation of the logging module, and moving logging docs to a separate page, following the same standard already being used for other `api/general` documentation pages.
In addition, reworked `doc/source/api/general/index.rst` so that all 3 sections have the same order and aren't as confusing to navigate (ordering was scrambled before):
=> Logging and misc documentation improvements

codegen/allapigen.py, codegen/datamodelgen.py, codegen/print_fluent_version.py, codegen/settingsgen.py, codegen/tuigen.py, src/ansys/fluent/core/utils/search.py
If we install pyfluent with `pip install ansys-fluent-core` now, we don't get the generated API files for unreleased Fluent version 24.1. This PR adds an option in codegen to patch an existing pyfluent installation. E.g., if pyfluent is installed in a virtual environment `D:\ANSYSDev\env`, we can run codegen from another pyfluent git area (make sure `AWP_ROOT241` env var is set)
```
python codegen\allapigen.py --pyfluent-path=D:\ANSYSDev\env\Lib\site-packages
```
to add the 24.1 API files in the pyfluent installation in the virtual environment.
=> Add option to patch existing installation with codegen

.github/workflows/ci.yml, src/ansys/fluent/core/_version.py, tests/test_rp_vars.py
Remove the Ansys PyPI upload, which will now happen from [pyfluent-dev](https://github.com/ansys/pyfluent-dev) repo.
The internal package (with the 24.1 API files) will be uploaded to Ansys internal PyPI.
The public package (without the 24.1 API files) will be uploaded to public PyPI.
=> Bump version 0.17.1

.github/workflows/weekly-solvermode-test-run.yml, Makefile, pyproject.toml, tests/conftest.py, tests/test_flobject.py, tests/test_fluent_fixes.py, tests/test_solvermode/test_boundaries.py, tests/test_solvermode/test_calculationactivities.py, tests/test_solvermode/test_controls.py, tests/test_solvermode/test_general.py, tests/test_solvermode/test_initialization.py, tests/test_solvermode/test_materials.py, tests/test_solvermode/test_methods.py, tests/test_solvermode/test_models.py, tests/test_solvermode/test_named_expressions.py, tests/test_solvermode/test_post_vector.py
The tests within tests/test_solvermode directory will now be run weekly through the new `weekly-solvermode-test-run.yml`.
=> Fix nightly tests

src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/utils/setup_for_fluent.py, tests/test_session.py
Removing the solverworkflow object from the Python console as discussed with wf team. This object does not generally contribute well to the overall user experience, Command executions cause unpredictable side effects in the task tree.
=> rm solverworkflow

src/ansys/fluent/core/launcher/launcher.py, tests/test_fluent_session.py
Un-setting `APP_LAUNCHED_FROM_CLIENT` sets `fl-appname` in Fluent which fixes the interrupt behaviour.
This reverts #696, we need to investigate the performance issue separately. For now, the `fl-appname` setting in Fluent is the same as other remote infrastructures.
=> Fix interrupt from client

src/ansys/fluent/core/workflow.py
This removes the final warnings in this module. The warnings are gone now in the build for this branch: https://github.com/ansys/pyfluent/actions/runs/6297722171/job/17095248123?pr=2018
=> docstring changes

tests/conftest.py
Most of the solvermode tests were skipped in the weekly solvermode CI (https://github.com/ansys/pyfluent/actions/runs/6294700178/job/17086910227#step:13:393). This should fix the issue. Now the marker `fluent_version("latest")` is correctly resolved to `fluent_version(">=23.2")` for the solvermode CI
=> Most of the solvermode tests were skipped

.github/workflows/ci.yml, .github/workflows/compare-flobject.yml, .github/workflows/nightly-dev-doc-build.yml, .github/workflows/nightly-test-run.yml, .github/workflows/release-doc-build.yml, .github/workflows/run-custom-tests.yml, .github/workflows/test-run-wo-codegen.yml, .github/workflows/weekly-solvermode-test-run.yml
This will possibly fix the ghcr login issue in CI run for external users by eliminating the github username.
=> Use ansys-bot for docker login

.github/workflows/nightly-dev-doc-build.yml, .github/workflows/release-doc-build.yml
Continuation of #2024. This pull-request fixes the name of the documentation artifacts as per the failures in https://github.com/ansys/pyfluent/actions/runs/6321215095/job/17166203692
=> fix: doc-artifact name when uploading doc index

examples/README.txt
— Added a section in example section as “Miscellaneous Examples”, which links to the Miscellaneous examples repositories example documentation landing page.
— Removed existing repository link
=> Added section to Example Page

.github/workflows/ci.yml, .pre-commit-config.yaml, src/ansys/fluent/core/services/datamodel_se.py
docfromatter will be run only on CI (similar to vale) with a specific Python version. Locally it can still be run as `pre-commit run --hook-stage manual --all-files docformatter` if needed. Note that, the manual run will give wrong report for Python version < 3.11.
=> Run docformatter only on CI

.github/workflows/ci.yml, .github/workflows/run-custom-tests.yml, README.rst, doc/source/getting_started/faqs.rst, doc/source/getting_started/installation.rst, setup.py
We are dropping python 3.8 as of now and later we can include 3.12
=> Drop support for python 3.8

.github/styles/Vocab/ANSYS/accept.txt, .vale.ini, tests/test_rp_vars.py, tests/test_search.py
These warnings started appearing in multiple PRs - https://github.com/ansys/pyfluent/actions/runs/6505185628/job/17668355789?pr=2136#step:6:63
Some of these warnings seem false-positive. Why does `Import geometry` raise a warning, but `Describe geometry` does not?
=> Fix vale warnings

.github/workflows/nightly-dev-doc-build.yml, .github/workflows/release-doc-build.yml, tests/test_rp_vars.py
Cherry-picking #2136 for release 0.18 branch to fix the release doc index. We don't need to create a release as there is no code change.
I'll run the release doc CI manually after merging the PR.
=> fix: decompress artifact for doc indexing (#2136)

.github/dependabot.yml
Closes https://github.com/ansys/pyfluent/issues/2133
Changes:
- Dependabot should now group minor and patch (not major) dependency updates into a single PR
- Reduced frequency of dependency updates from daily to weekly
- GitHub actions dependency updates will all be grouped into a single weekly PR 
- Added `Maintenance` label to GitHub actions dependabot PRs
All of this should hopefully make dependabot dependency updates less annoying and more convenient to work with.
=> Multiple dependency updates per dependabot PR

src/ansys/fluent/core/systemcoupling.py
For System Coupling FSI case, when setting up the Fluent problem, the tensor type for the displacement variable was mistakenly set to `Scalar`.
=> fix tensor type for displacement variable

.github/dependabot.yml
- As discussed in the team meeting, let's try monthly dependabot PRs rather than weekly or daily.
- Removed unnecessary ignores: `vtk` as `pyfluent` core does not depend on `vtk`, that dependency is in `pyfluent-visualization`; and `grpcio` as that one is in the `setup.py` file which is not managed by dependabot.
=> Monthly dependency bot updates

MANIFEST.in, src/ansys/fluent/core/launcher/watchdog.py, src/ansys/fluent/core/launcher/watchdog_exec, src/ansys/fluent/core/launcher/watchdog_exec.pyw, tests/test_launcher.py
- New test that fails when Watchdog launch errors occur: `test_watchdog_launch`
- Now using no file extension for the script of the Watchdog process (code script was simply moved from `watchdog.py` to `watchdog_exec` file, no significant changes, see below). Changing the file extension makes no difference on Linux, but can circumvent inappropriately configured user environments on Windows (e.g., when for some reason a Windows code editor is configured to interfere with the execution of `.py` files).
- Few minor watchdog updates.
- Added docstrings and a bit of code documentation (note this shouldn't show up anywhere in the online documentation to users).
Diff between original `watchdog.py` and new `watchdog_exec` (as of `c427e2f`):
=> Test to catch Watchdog launch errors, and improved Watchdog behavior on Windows

src/ansys/fluent/core/launcher/watchdog.py
Attempting to make the command as explicit as possible, to see if this error, that only occurs in some systems, and that I have been unable to reproduce, is finally resolved without requiring the user to change anything about their system
Changing from command list, which seems to have behavior that can be system dependent on Windows, to a command string, which should be more robust
=> More robust Windows launch command for Watchdog

requirements/requirements_tests.txt, setup.py, src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/filereader/data_file.py
Addresses remaining vulnerability in https://github.com/ansys/pyfluent/issues/1552
To be superseded by https://github.com/ansys/pyfluent/issues/2096 when the `pyfluent-reader` package is published
By default, `pip install ansys-fluent-core` or installing from a pre-built wheel file won't install `h5py` anymore.
To get data and case file reader functionality, users will need to: 
- `pip install ansys-fluent-core[reader]`
- `pip install -e .[reader]` for development
- `pip install ansys_fluent_core-0.19.dev0-py3-none-any.whl[reader]` from a wheel file
=> Making h5py an optional dependency, not installed by default

src/ansys/fluent/core/session_solver.py
```
>>> import ansys.fluent.core as pf
>>> solver = pf.launch_fluent(...)
>>> solver()
```
Solver object is callable now.
=> Expose settings root like in pyconsole.

pyproject.toml, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/launcher.py, tests/conftest.py, tests/test_session.py
~trying to understand the impact~
Looking at how we are launching Fluent from PyFluent, the timeout loop in `FluentConnection` is unnecessary. I have replaced it with a `check_health` call which will fail only if there is some issue at grpc communication level and it will expose the grpc error message in that case. Exposing the grpc error message here will help us to triage issues in user's system.
The `start_timeout` is used only when we wait for the server to finish writing the server-info file.
Tested by hardcoding a port in `FluentConnection`, so grpc connection will fail due to port-mismatch:
Old behaviour (fails after 60 s):
```
>>> solver = pyfluent.launch_fluent()
pyfluent.launcher ERROR: Exception caught - RuntimeError: The connection to the Fluent server could not be established …
```
=> Remove timeout loop in FluentConnection

src/ansys/fluent/core/systemcoupling.py
To correct issue https://github.com/ansys/pyfluent/issues/2179
Obtains Fluent's working directory using the `cortex_pwd` variable and prepends that to the `.scp` file name in `get_scp_string()`.
=> Prepend working dir to .scp file name

src/ansys/fluent/core/streaming_services/monitor_streaming.py, tests/test_fluent_fixes.py
```
import ansys.fluent.core as pyfluent 
from ansys.fluent.core import examples
import_case = examples.download_file(
file_name="exhaust_system.cas.h5", directory="pyfluent/exhaust_system"
)
import_data = examples.download_file(
file_name="exhaust_system.dat.h5", directory="pyfluent/exhaust_system"
)                    
solver_session = pyfluent.launch_fluent(                                        
precision="double", processor_count=2, start_transcript=False, mode="solver",
show_gui=True, cleanup_on_exit=False
)
solver_session.tui.file.read_case(import_case)
solver_session.tui.file.read_data(import_data)
solver_session.tui.solve.set.number_of_iterations(15)
solver_session.tui.solve.iterate()
solver_session.monitors_manager.get_monitor_set_names()
mp = …
```
=> Fix for #974 and #1744

src/ansys/fluent/core/streaming_services/monitor_streaming.py, tests/test_fluent_fixes.py
```
>>> import ansys.fluent.core as pyfluent
>>> from ansys.fluent.core import examples
>>> import_case = examples.download_file(file_name="exhaust_system.cas.h5", directory="pyfluent/exhaust_system")
Checking if specified file already exists...
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.cas.h5
>>> import_data = examples.download_file(file_name="exhaust_system.dat.h5", directory="pyfluent/exhaust_system")
Checking if specified file already exists...
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.dat.h5
>>> solver_session = pyfluent.launch_fluent(precision="double", processor_count=2, start_transcript=False, mode="solver", show_gui=True)         
>>> …
```
=> Fix for #2188

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/streaming_services/field_data_streaming.py, src/ansys/fluent/core/streaming_services/streaming.py
Closes https://github.com/ansys/pyfluent/issues/2223, see that tracker for more details
Tested in CDC, and the user tested in OTTC, confirmed to solve the issues
Two issues fixed:
- PyFluent was freezing due to streaming thread locked up by `.join` with no timeout
- Watchdog was being launched even though Fluent is remote, and it shouldn't be
=> Fixing Slurm/HPC issues

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/watchdog.py
Closes https://github.com/ansys/pyfluent/issues/2187
Two things were causing issues for custom shell environments on Windows and are fixed here:
- Unnecessary empty spaces between arguments
- Using quotes when they are not needed
Tested with Command Prompt, PowerShell and Cmder, this should not cause any regressions (famous last words)
Just to make sure no additional issues introduced, it would be helpful if some reviewers could test this branch on their own Windows systems: just `launch_fluent` and then see if any obvious issues occur, and if PyFluent and the Watchdog were launched correctly.
=> Fixing launch behavior for various Windows shell environments

setup.py, src/ansys/fluent/core/examples/downloads.py
Closes https://github.com/ansys/pyfluent/issues/2233
Fixes issues that were occurring on Red Hat and CentOS machines (and HPC environments), I was able to reproduce the issues and test the changes locally as well.
Also removed redundant `print`s and replaced them with logging.
Confirmed with @millerj97 that this branch solves the issues on their machines as well
=> Removing deprecated `urlretrieve` to fix `download_file` issue

tests/test_solvermode/boundaries_periodic_expDict, tests/test_solvermode/test_boundaries.py, tests/test_solvermode/test_general.py, tests/test_solvermode/test_initialization.py, tests/test_solvermode/test_methods.py
Fix the following failing tests:
- ```tests\test_solvermode\test_boundaries.py```
-  update json comparison file
- change boundary_type for valid .items() calls
- ```tests\test_solvermode\test_general.py```
- ```tests\test_solvermode\test_initialization.py```
- general command updates
- ```tests\test_solvermode\test_methods.py```
- first_to_second_order_blending limit of 0 - 1
- general commands
=> Fix skipped solvermode tests

setup.py
Fixes this badge: 
Should now look similar to:
And the metadata on PyPI:
After new release, should look like:
(without Python 3.12 as we don't fully support it yet)
=> Updating project metadata

doc/source/api/general/sessions/Solver/index.rst
solver_lite.rst was removed but it's info was not removed from solver.rst. 
It's removed now.
=> Remove solver lite from solver.rst

doc/source/api/general/launcher/index.rst, doc/source/api/general/launcher/slurm.rst, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/fluent_launcher_options.json, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, tests/test_slurm_future.py
```
>>> slurm = pyfluent.launch_fluent(scheduler_options={"scheduler": "slurm"})
>>> slurm
<ansys.fluent.core.launcher.launcher.SlurmFuture object at 0x2b9238af63b0>
>>> slurm.pending(), slurm.running(), slurm.done()
(True, False, False)  # before Fluent is launched
>>>  slurm.pending(), slurm.running(), slurm.done()
(False, True, False) # after Fluent is launched
>>> session = slurm.result()
>>> session.exit()
>>> slurm.pending(), slurm.running(), slurm.done()
(False, False, True)
```
=> Support Slurm options in launch_fluent

tests/test_solvermode/test_initialization.py
Currently, the `test_initialize`  solver mode test changes the initialization settings, but never actually calls `hybrid_initialize` as that line is commented out.
This PR changes the name of the test to `test_initialization_settings` and removes the commented-out calls to `root.solution.initialization.hybrid_initialize()` and to `root.exit()` for clarity.
=> Change name of test_initialize

codegen/datamodelgen.py, src/ansys/fluent/core/services/datamodel_se.py, tests/test_datamodel_service.py
For background, please see the draft PR #2220 and the corresponding Fluent side PR. The primary idea is to have a class wrapping the datamodel_se grpc calls. The class will pass pure Python types (instead of Protobuf types) and will be re-implemented on PyConsole side through local Python function calls.
=> datamodel_se refactoring for pyconsole implementation

setup.py, src/ansys/fluent/core/services/datamodel_se.py, tests/test_datamodel_service.py
New methods like 'get_object_names', 'rename', 'delete_child_objects', 'delete_all_child_objects' and 'fix_state' has been implemented in the server side for pyconsole integration (migrating these methods to datamodel instead of PyStateEngine).
This PR contains client side updates to expose those methods as well as test cases to check the implementation.
=> feat: Expose new methods in datamodel service.

src/ansys/fluent/core/workflow.py, tests/test_meshing_workflow.py
1. Emulated the settings dict-style version (example shown in test.)
2. Display name attached to tasks.
=> feat: Update container level operations.

src/ansys/fluent/core/workflow.py
Just commenting out the "_wait_on_refresh" method from the workflow.py code and running all the related tests suggest that it is running fine. So, we can get rid of this method with some level of confidence. What are your view?
Got rid of all instances of sleep.
cc @seanpearsonuk , @mkundu1
=> refactor: Remove wait_on_refresh

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/services/__init__.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session.py
Required for PyConsole development (moved the `add_on_*` methods at `DatamodelService` level which will be overwritten on PyConsole side)
=> feat: Some refactoring of datamodel events registration code

src/ansys/fluent/core/services/__init__.py, src/ansys/fluent/core/services/api_upgrade.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/services/datamodel_tui.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/streaming_services/monitor_streaming.py
1. datamodel_tui refactoring for pyconsole work (extract a pure python service class to overwrite from pyconsole)
2. A small change so that flobject.get_root can be overwritten in pyconsole (to avoid the hash comparison for pyconsole as that will always fail as it compares the local static-info and static-info over grpc)
3. Refactoring required for monitor service implementation in PyConsole.
=> feat: datamodel_tui refactoring

src/ansys/fluent/core/services/__init__.py, src/ansys/fluent/core/session_solver.py
Refactoring required for svar service implementation in PyConsole.
=> refactor: svar refactoring

doc/source/user_guide/launching_ansys_fluent.rst, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/slurm_launcher.py
`scheduler_options` argument of `launch_fluent`:
`Launch or connect to Fluent` section of User guide:
=> docs: Document additional slurm options

setup.py
The `AutoPauseEvent` included in the new version can be used to implement #2361 - execute a Python callback in PyFluent at the end of each time-step. Following is a working code which can be expanded into a PyFluent feature.
```
solver.tui.solve.execute_commands.add_edit(
"command-1",
"no",
1,
"time-step",
"\"(events/transmit 'auto-pause (cons 2 (rpgetvar 'time-step)))(grpcserver/auto-pause (is-server-running?) 'pyfluent)\""
)
indices = []
def on_pause(session_id, event_info):
indices.append(event_info.index)
solver.scheme_eval.scheme_eval('(grpcserver/auto-resume (is-server-running?) "pyfluent")')
solver.events_manager.register_callback("AutoPauseEvent", on_pause)
```
=> build: upgrade ansys-api-version

src/ansys/fluent/core/solver/flobject.py
If a field x is located at active paths a.b.x and a.b.c.x and the user queries a.x, The paths should be a.b.x and a.b.c.x.
Incorrect path (existing output) - 
`-------------------------------------`
Corrected path - 
`-------------------------------------`
=> refactor: Correct attribute access path

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/session_solver_icing.py
This task solves the issue in https://github.com/ansys/pyfluent/issues/2313.
The root cause of the issue was that some redundant arguments were being passed to the launcher (when called internally). So, this PR contains a total clean up of the launcher code that helps debug these issues easily later.
1. FluentMode (enum class) is cleaned up. The local variable "meshing_mode" has been completely removed as it was confusing with earlier launch mode named same.
2. All "meshing_mode" checks are replaced with mode (enum class)
3. "_get_session_info" and "_get_argvals" are removed and in place a simple "_get_mode" only returns the mode in enum form.
4. For icing, the additional argument value has been put in.
=> refactor: Clean up the launcher code.

doc/source/user_guide/tui_commands.rst
Added examples of how to use `dir()` and `help()` for development using TUI commands to the documentation.
=> docs: Added example of `__dir__` and `__help__` usage for TUI menus to doc

src/ansys/fluent/core/solver/flobject.py, tests/parametric/test_parametric_workflow.py, tests/test_flobject.py
Please note:
Along with this there should be a couple of minor style fixes in the server side to have the 2 files completely in sync.
There has been some changes in the rename method to support backwards compatibility. 
Tests have been added to check the earlier and latest behavior of 'rename' method. Server-side flobject.py will be updated accordingly.
=> refactor: Make flobject consistent wrt server.

src/ansys/fluent/core/services/datamodel_se.py, tests/test_datamodel_service.py
The class variable `_full_static_info` at `PyCommand` stores static info for all datamodels, starting from root.
The instance variable `_static_info` at `PyCommand` stores the static-info at command level.
The instance variable `static_info` at `PyCommandArguments` stores the static-info at command arguments level.
=> fix: Fix an issue in command creation inside singleton

doc/source/user_guide/launching_ansys_fluent.rst
The detail about `slurm.result()` was only available in a [separate page](https://fluent.docs.pyansys.com/version/stable/api/general/launcher/slurm.html#module-ansys.fluent.core.launcher.slurm_launcher)
=> docs: Minor improvement suggested by user

.github/workflows/nightly-test-run-develop-branch.yml, .github/workflows/nightly-test-run.yml
This separates the nightly test runs for 24.2 from the other versions.
We can catch the connection error in python and re-run that test only???
=> build: Separate 24.2 nightly tests.

src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/workflow.py, tests/test_meshing_workflow.py
This PR fixes a warning that can be seen in case reader while reading project files. Alongside, this also makes the meshing taskobject arguments non read-only. So, we can set it's values. It also has tests for the same.
=> fix: issues in workflow and case reader

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, tests/test_launcher.py
Fluent GPU Solver is only supported for 3D. Now we are raising `GPUSolverSupportError` exception if `gpu=True` and version is not "3d".
`------------------------------------------`
=> refactor: Fluent GPU Solver is only supported for 3D.

.pre-commit-config.yaml, src/ansys/fluent/core/streaming_services/datamodel_streaming.py
This will catch any Python >3.9 code during pre-commit.
=> style: Add --target-version=py39 to black

.github/workflows/ci.yml, src/ansys/fluent/core/_version.py
We need to publish the 24.2 API files to Ansys Python distribution. I've made some changes in ci.yml in this PR:
1. The dev package will always contain the 24.2 (or the current development) API files.
2. The dev package will be published only to private PyPi.
=> build: Bump version 0.20.dev3

Makefile, codegen/settingsgen.py, doc/settings_rstgen.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py, tests/test_settings_api.py
This PR adds the backward compatbility support in PyFluent settings API using the `child-aliases`/`command-aliases`/`query-aliases` attributes in settings API.
A tree of alias-objects mimicking the original object tree is constructed on-access basis during runtime. For an object hierarchy `A -> B -> C`, If `A1` is an alias of `A`, `A1.B` and `A1.C` are also aliases and the backward compatibility message for set_state is shown at all levels. The `_Alias` base class prints the backward compatibility message on various journaling points using the scheme_eval function which is passed through the `get_root()` function.
Please see the Fluent side PR for more details on flobject.py change.
I'm also incorporating changes from #2428 which simplifies some code requiring access to original settings …
=> feat: Backward compatibility for settings API

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/utils/file_transfer_service.py, tests/test_launcher_remote.py
1. Removed `RemoteFileHandler` wrapper.
2. Added `file_transfer_service` parameter to `launch_fluent`, `launch_remote_fluent` and Standalone, Container, PIM launchers.
3. Moved `TransferRecorderService` to `test_launcher_remote.py`.
=> refactor: Remove RemoteFileHandler wrapper

setup.py, src/ansys/fluent/core/launcher/launcher_utils.py, tests/test_launcher.py
This feature is now supported in beartype version 0.17.
=> feat: Throw standard Python error on beartype violation

.pre-commit-config.yaml
https://github.com/compilerla/conventional-pre-commit
To install the pre-commit hook locally: `pre-commit install --hook-type commit-msg`
Note that, this will validate the commit message of each local commit.
=> style: Add a precommit hook for conventional commit

setup.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/flunits.py, tests/test_flobject.py
- **Follow-up on initial units integration into PyFluent.**
- upgrade ansys-units dependency
- enable a temporarily disabled test step due to this upgrade
- extend the testing
- fix an flobject assignment issue where exceptions were inadvertently hidden
- treat None value for units-quantity to indicate dimensionless
- implement exception handling
- rename `get_state_as_quantity()` (too long) as `as_quantity()`
- make the generation of the table data stricter
=> feat:                   units follow-up with testing

requirements/requirements_tests.txt, setup.py
After installing `ansys-fluent-core[tests]`, it should be possible to execute `pytest <site-packages>/ansys/fluent/tests` to run pyfluent unittests.
=> build: Include tests directory in package

src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/flunits.py, tests/test_flobject.py
- **Add `RealList` to units support**.
- Generalize the implementations for `Real` and `RealList` in a shared mixin base class.
- Change the behaviour of method `real_with_units`. Previously it returned None if the units were undefined or if the value were not `float` (or `int`). That would be particularly unsatisfactory for nested state, so we construct the tuple unconditionally now.
- Added test steps for the `RealList`.
- ansys.units update is required, as commented in test code.
- added code and test for **nested** state with units. **This means a lot more changes since the approvals!**
=> feat: state with units

src/ansys/fluent/core/session_solver.py, tests/test_flobject.py, tests/test_session.py
Expose get_state() and set_state() at solver level.
Activate failing test with new fluent image.
=> fix: Failing test for 24.2 is fixed.

codegen/settingsgen.py, src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py, tests/test_settings_api.py
Suppress return value for a command if its `return-type` attribute in settings API is not specified.
=> feat: Do not return boolean from settings API commands

codegen/settingsgen.py
It was not caught in my PR because the codegen was not rerun after the docker image update. The unittests ran with the dynamically generated classes from the new image due to the updated static-info.
=> fix: settingsgen

src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/flunits.py, tests/test_flobject.py
- Extend units coverage by massaging the Fluent table a bit more.
- Fix an issue for setting quantities at `x` where `x.value` is a `Real`*. WARNING: this is a hack.
=> feat: units percent and ohms and handling nested quantities

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/session_solver_icing.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/utils/data_transfer.py, tests/test_launcher_remote.py
Renamed `remote_file_handler` to `file_transfer_service`.
=> refactor: rename remote_file_handler to file_transfer_service

codegen/settingsgen.py
Fixes an issue from the following code with the latest Fluent. The code is used in PyConsole implementation.
```
>>> import ansys.fluent.core.solver.settings_242
File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\settings_242\__init__.py", line 9, in <module>
from .root import root
File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\settings_242\root.py", line 20, in <module>
from .setup import setup as setup_cls
File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\settings_242\setup.py", line 18, in <module>
from .models_1 import models as models_cls
File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\settings_242\models_1.py", line 28, in <module>
from …
```
=> fix: Fix a settingsgen issue

codegen/allapigen.py, codegen/datamodelgen.py, codegen/print_fluent_version.py, codegen/settingsgen.py, codegen/tuigen.py, tests/test_codegen.py
Reducing number of times Fluent is launched from 8 to 3 while running allapigen.py. The session instances  for each mode (solver, meshing and solver-icing) are stored in a dictionary which is reused accross all *gen.py files.
=> feat: Minimize number of fluent launches during codegen

doc/source/getting_started/faqs.rst, doc/source/getting_started/installation.rst, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/warnings.py, tests/test_flobject.py, tests/test_launcher.py
Two new arguments `ui` and `graphics_driver` are added to `launch_fluent`. They accepts the values of `FluentUI` and `FluentWindowsGraphicsDriver | FluentLinuxGraphicsDriver` enums respectively. The default value of `ui` is `FluentUI.HIDDEN_GUI` (`-hidden`) in windows (no change) and `FluentUI.NO_GUI` (`-gu`) in linux. I haven't made the default value `FluentUI.NO_GUI` in windows as it shows Fluent output in the current cmd. The default value of `graphics_driver` is `AUTO`.
The `launch_fluent` argument `show_gui` has been made deprected.
TODO: Record `ui` and `graphics_driver` Python joural saved from Fluent.
=> feat: Launcher argument for Fluent exposure and graphics driver

src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/services/solution_variables.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, tests/test_field_data.py, tests/test_flobject.py, tests/test_pure_mesh_vs_mesh_workflow.py, tests/test_session.py, tests/test_solution_variables.py, tests/test_solvermode/test_general.py
Refactoring the methods exposed in session level.
=> refactor: session

src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
Storing alias objects within parent object instead of the parent class so that aliasing of named object children works correctly.
=> fix: Store alias objects at objects instead of classes

src/ansys/fluent/core/services/datamodel_se.py
This will fix the error seen from `EventScubscription.__del__` in recent code. I'm not able to write a unittest as pytest doesn't seem to detect the error (or the warning which is converted from the error).
Note: this error will not be present in PyConsole
=> fix: Fix EventSubscription when an event cannot be subscribed.

src/ansys/fluent/core/services/settings.py, tests/test_flobject.py
This is temporay fix so that exisiting PRs can go in. I'll look into the actual issue separately.
Although I'm removing the problematic parameters at the static-info level, still there is a hash-mismatch during pyfluent runtime. But the current fix will be good enough for pyconsole integration where only the generated classes are used.
Update: the hash-mismatch issue is present also in main branch - will be fixed in #2602
=> fix: temporary fix for a settingsgen issue

codegen/settingsgen.py, src/ansys/fluent/core/services/settings.py, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
The `icing` setting has children `fensapice-drop-vrh?` and `fensapice-drop-vrh` which yield same python name. This PR fixes an issue in the generated settigs code and reverts the temporary fix #2601
=> fix: Fix a settingsgen issue when multiple children under same parent have identical python name

pyproject.toml, src/ansys/fluent/core/_version.py, tests/parametric/test_parametric_workflow.py, tests/test_new_meshing_workflow.py, tests/test_settings_api.py
I have also pushed a tag as we need a build for optislang with the `session.parameters.output_parameters.list()` Fluent fix.
=> build: Bump version 0.21.dev0

tests/test_meshing_queries_fdl.py
Closes https://github.com/ansys/pyfluent/issues/2634
Failing part has commented out.
This type of failure is due to periodic difference in output data from Fluent therefore we will be commenting out such failures in future as well.
=> fix: Fix test_meshing_utilities

src/ansys/fluent/core/launcher/__init__.py
closes https://github.com/ansys/pyfluent/issues/2622
Prior to this change - 
```
>>> import ansys.fluent.core as pyfluent
>>> dir(pyfluent.launcher) 
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'container_launcher', 'error_handler', 'fluent_container', 'launcher', 'launcher_utils', 'pim_launcher', 'process_launch_string', 'pyfluent_enums', 'server_info', 'slurm_launcher', 'standalone_launcher', 'watchdog']
```
Now -
```
>>> import ansys.fluent.core as pyfluent
>>> dir(pyfluent.launcher)               
['LaunchMode', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'check_docker_support', 'configure_container_dict', 'container_launcher', 'create_launcher', 'error
_handler', …
```
=> fix: Organize public objects and functions under launcher

src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py
For commands with no arguments, argument_names attribute returns an empty list instead of throwing an attribute error.
=> fix: Add default for argument_names in commands.

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/session_solver_icing.py, src/ansys/fluent/core/session_solver_lite.py, src/ansys/fluent/core/utils/setup_for_fluent.py, tests/test_launcher_remote.py, tests/test_session.py
Pass scheme eval as an argument to session instead of taking it directly from FluentConnection.
=> refactor: Pass scheme eval as argument to session.

src/ansys/fluent/core/file_session.py, src/ansys/fluent/core/services/field_data.py
Fixes Fluent bug 1014887. The boundary values default is True in Fluent.
=> fix: Set boundary values default to True

src/ansys/fluent/core/workflow.py, tests/test_new_meshing_workflow.py
Fix for some enhanced meshing workflow issues, one of which is reported on the Fluent side.
1. When an invalid task argument is set, an exception is not immediately triggered because the relevant server code does not do rules validation at the key-value level of dictionary parameters. The invalidity only becomes apparent at the command level. So, with this change, I ensure that when the task arguments are changed, the command arguments are also updated. That way the exception is triggered right away upon the relevant call. Also, the state is repaired within the same assignment implementation.
2. Code like `my_task.some_arg = 1` did not follow the same path through the code as `my_task.arguments.update_dict(dict(some_arg = 1))`, which is now rectified. I suspect that there could be similar …
=> fix: workflow validation

tests/test_session.py
tests/test_session.py -> test_get_set_state_on_solver is failing which is causing other PRs to not get merged. A github issue has been created for this and this test has been temporarily skipped.
=> refactor: Skip failing test.

.github/workflows/ci.yml, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py, tests/test_datamodel_service.py, tests/test_settings_api.py
There is a corresponding Fluent side PR fixing some issues in the datamodel event tags.
All corresponding datamodel subscription objects are unsubscribed while deleting the datamodel object. Subscription objects which are not of on-deleted type are unsubscribed just before the datamodel object is deleted. On-deleted type subscripton objects are unsubscribed through a final on-deleted callback after the datamodel object is deleted.
=> fix: Unsubscribe datamodel subscriptions on object deletion.

src/ansys/fluent/core/utils/file_transfer_service.py
closes https://github.com/ansys/pyfluent/issues/2706
Fluent is now able to read file without `cwd` argument properly.
=> fix: file transfer refactor

Makefile, src/ansys/fluent/core/data_model_cache.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/workflow.py, tests/conftest.py, tests/test_data_model_cache.py
Each session should have its own datamodel cache.
=> fix: cache per session

src/ansys/fluent/core/examples/downloads.py, src/ansys/fluent/core/utils/file_transfer_service.py
closes https://github.com/ansys/pyfluent/issues/2735
Do not upload file if it's already exists on remote.
=> fix: avoid gRPC FTS file modification

doc/datamodel_rstgen.py
closes https://github.com/ansys/pyfluent/issues/2746
`MeshingUtilities` is available for >= 24R2 only. 
We have handled this condition now.
Nightly dev doc is working fine now.
=> fix: nightly dev doc import fix

src/ansys/fluent/core/rpvars.py, tests/test_rp_vars.py
Correct the argument checks in rp-var service.
=> fix: rpvar fix for bool etc

src/ansys/fluent/core/data_model_cache.py
Added a lock per rules for better performance.
=> fix: Make datamodel cache thread-safe

src/ansys/fluent/core/workflow.py
Closes #2750
Renamed from `NewCommandError` to the more detailed but verbose `CommandInstanceCreationError`
Can now be imported as `from ansys.fluent.core.workflow import CommandInstanceCreationError` if a client wants to handle it
Slightly reworded the docstring as well
=> refactor: Exposing custom workflow exception

src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/standalone_launcher.py
closes https://github.com/ansys/pyfluent/issues/2753, https://github.com/ansys/pyfluent/issues/2754
Disable local FTS for standalone launcher.
This is due to specific case of `read_case_data` where we specify single file path but we need to move 2 files to Fluent's cwd.
`ui_mode` argument is fixed now.
=> fix: Disable Local FTS for Standalone Launcher and fix for `ui_mode` argument

src/ansys/fluent/core/launcher/pyfluent_enums.py
closes https://github.com/ansys/pyfluent/issues/2773 https://github.com/ansys/pyfluent/issues/2754
`show_gui` and `ui_mode` values were swapping. It's resolved now.
=> fix:  `show_gui` and `ui_mode` value swap

src/ansys/fluent/core/systemcoupling.py
Variable was mistakenly named `lortentz-force`. In practice, this section of the code should never be reached, but it is there to guard against missing information in the SCP file.
=> fix a typo in variable name

src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session_pure_meshing.py, tests/test_meshing_workflow.py
Contains datamodel_se related set_state() updates.
=> fix: expose meshing attrs at session level

doc/datamodel_rstgen.py, doc/tui_rstgen.py, tests/test_file_transfer_service.py
Closes https://github.com/ansys/pyfluent/issues/2786, https://github.com/ansys/pyfluent/issues/2788
1. Fix for Nightly Dev Doc.
2. `test_remote_grpc_fts_container` was failing in Nightly Dev Test, it's fixed now.
=> fix: Fix for `test_remote_grpc_fts_container` and nightly dev doc

src/ansys/fluent/core/services/datamodel_se.py, tests/test_meshing_workflow.py
'set_state' method was updated to work with arguments but actually set_state() should also work and this behaviour is also there in flobject -> Group class's set_state()
The earlier changes are reverted.
=> refactor: Revert datamodel set_state changes.

tests/test_flobject.py, tests/test_type_stub.py
closes https://github.com/ansys/pyfluent/issues/2792
1. Skip `test_settings_matching_names` due to socket closed issue.
2. Add 24R1 marker to `test_settings_stub`
=> fix: Skip `test_settings_matching_names` and add 24R1 marker to `test_settings_stub`

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/standalone_launcher.py, src/ansys/fluent/core/utils/deprecate_args.py
Remove the ''show_gui'' argument and put a mechanism for migrating older scripts.
=> refactor: Remove 'show_gui' from launch_fluent arguments.

src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, tests/test_launcher.py
`additional_arguments` was being evaluated in two different places: `_build_fluent_launch_args_string` and `_generate_launch_string`, and wasn't being passed properly to the container launcher
`additional_arguments` is also repeated inside `self.argvals` and `self.additional_arguments` in the launchers, not sure why, not changed in this PR
The suggestion in this PR is to evaluate `additional_arguments` only in `_build_fluent_launch_args_string`, so that it is also applicable to container launchers and not only launchers that call `_generate_launch_string` (slurm and standalone launchers currently)
=> fix: launcher additional arguments

codegen/allapigen.py, src/ansys/fluent/core/codegen/datamodelgen.py, src/ansys/fluent/core/codegen/settingsgen.py, src/ansys/fluent/core/codegen/tuigen.py, tests/test_codegen.py
The code changes are removal of some assumptions about availability of settings-info.
=> test: Add unittests for codegen

src/ansys/fluent/core/systemcoupling.py, tests/test_systemcoupling.py
Adding a simple test to check System Coupling related settings. It's probably worth adding a few more, but that can be done separately.
=> test: Add a test for System Coupling related settings

src/ansys/fluent/core/launcher/launcher.py
Suggestion for #2822, from https://github.com/ansys/pyfluent/pull/2822#discussion_r1601721601, merges into that PR
Additional benefit is that it becomes easier to be aware of which arguments exactly are _not_ supported by each launcher, just by looking at the code (work to be done to add support for some of these unsupported arguments?).
Edit: @hpohekar unintentionally exposed another reason to use this suggested approach instead of the current implementation, see: https://github.com/ansys/pyfluent/pull/2826#discussion_r1603013555, in addition to issues where `create_launcher()` isn't currently set up to be directly exposed to users (unrelated to these changes, issue tracker: https://github.com/ansys/pyfluent/issues/2827).
=> refactor: using blacklist approach instead of whitelist for launch args

src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_base_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/utils/search.py, tests/test_search.py
This fixes the issue with search_root introduced due to the dynamic path of the generated API. Now the modules imported from the dynamic path will be qualified with mode and version information in their names, so we won't loose any information for the search function.
=> fix: Support search_root properly with dynamic-path module import

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/standalone_launcher.py
closes https://github.com/ansys/pyfluent/issues/2833, https://github.com/ansys/pyfluent/issues/2827
Refactor _generate_launch_string() - pass only argals instead of argvals and mode
=> refactor: `_generate_launch_string()` and callable launchers

tests/test_launcher.py
Forgot to include this additional test in https://github.com/ansys/pyfluent/pull/2807
Test fails in `main` @ cbab7df3853aa870b65e629774a3457ef01fe077 with `AssertionError: assert '-ws -ws-port=5000 -i test.jou' in ' 3ddp -t4'`
Passes after merge dcb2f69f181a0c9f68ac6515cf2b8aa8e97d167f
=> test: additional arguments from _build_fluent_launch_args_string

pyproject.toml, tests/test_launcher_remote.py, tests/test_tests_util.py, tests/util/__init__.py
Running unittests in parallel using pytest-xdist. The test test_launch_remote_instance has been adjusted as it was modifying the original downloaded file which was causing issue in another test test_field_data_objects_3d.
The 24.2 unittests runtime is reduced from ~56 min to ~31 min.
=> test: run unittests in parallel with pytest-xdist

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/examples/downloads.py, src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/services/solution_variables.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/utils/deprecate_args.py, src/ansys/fluent/core/utils/file_transfer_service.py, src/ansys/fluent/core/warnings.py, src/ansys/fluent/core/workflow.py, tests/test_session.py
Derive all current PyFluent warnings from either `PyFluentDeprecationWarning` or `PyFluentUserWarning`. User can disable all PyFluent warnings by calling `pyfluent.warning.disable()`.
=> feat: Derive all PyFluent warnings from common base classes.

src/ansys/fluent/core/meshing/meshing_workflow.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/workflow.py
Distinguishing between `initialize` and `reinitialize`:
`initialize` - A different workflow is created, root affected callback is cleared.
`reinitialize` - The same workflow is reinitialized, root affected callback is not cleared.
=> fix: root affected level

src/ansys/fluent/core/utils/search.py
closes https://github.com/ansys/pyfluent/issues/2871
Resolves ssl certificate error for `nltk.download()` on Linux.
=> fix: ssl certificate fix for nltk.download() on Linux

src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py
closes https://github.com/ansys/pyfluent/issues/2872
Set `start_timeout = -1` for Slurm launcher.
Thank you very much @millerj97 for testing this in Slurm environment quickly.
using `create_launcher`
```
>>> from ansys.fluent.core.launcher import create_launcher
>>> from ansys.fluent.core.launcher.pyfluent_enums import LaunchMode
>>> launcher = create_launcher(LaunchMode.SLURM,scheduler_options={"scheduler": "slurm"})
>>> slurm=launcher()
>>> type(slurm) # <class 'ansys.fluent.core.launcher.slurm_launcher.SlurmFuture'>
<class 'ansys.fluent.core.launcher.slurm_launcher.SlurmFuture'>
>>> slurm.pending(), slurm.running(), slurm.done() # (True, False, False)
(True, False, False)
>>> session = slurm.result()
>>> session # <ansys.fluent.core.session_solver.Solver object at 0x7f171eb40970> …
```
=> fix: set start_timeout = -1 for Slurm launcher

.github/workflows/ci.yml, Makefile, doc/source/getting_started/faqs.rst, pyproject.toml, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/logging.py, tests/test_fluent_session.py, tests/test_launcher.py, tests/test_launcher_remote.py, tests/test_logging.py
Please see the new FAQ entry to hide all PyFluent warnings from console.
=> fix: Add a method to set console loggers' level

src/ansys/fluent/core/solver/flunits.py
closes https://github.com/ansys/pyfluent/issues/2554
Do not filter out ' in string quantity type
=> fix: Do not filter out ' in string quantity type

doc/source/contributing.rst
closes https://github.com/ansys/pyfluent/issues/2883, https://github.com/ansys/pyfluent/issues/2894
1. Updated `Build documentation` instructions.
2. Renamed `_builds` -> `_build`
=> fix: Update contributing doc

.github/workflows/ci.yml, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, tests/test_launcher.py
`FluentVersion` can be constructed as:
```
FluentVersion.v242
FluentVersion("24.2.0")
FluentVersion("24.2")
FluentVersion(24.2)
FluentVersion(242)
```
Supporting all of them in `product_version`.
Also, `product_version` is given higher priority over the env var `PYFLUENT_FLUENT_ROOT`.
=> fix: user can input enum, str, float or int for product_version

codegen/allapigen.py, src/ansys/fluent/core/codegen/datamodelgen.py, src/ansys/fluent/core/codegen/tuigen.py, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, tests/test_launcher.py
MESHING_MODE -> MESHING
PURE_MESHING_MODE -> PURE_MESHING
=> refactor: Remove _MODE.

src/ansys/fluent/core/fluent_connection.py, src/ansys/fluent/core/launcher/watchdog_exec, tests/test_fluent_session.py
As the health-check service is now executed on main thread in FLuent, calling `session.health_check.is_serving` when Fluent's main thread is frozen will hang in client . Calling `session.health_check.is_serving` in `timeout_exec` to resolve the client hang.
=> test: fix test_fluent_freeze_kill

Makefile, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
For Fluent version < 24.2, commands will return the value of the settings API function call as before. For later Fluent versions, commands will return value only if the `return_type` attribute is specified for the command in settings API.
=> fix: command return type for old Fluent version

.github/workflows/ci.yml, .github/workflows/test-run-old-versions-weekly.yml, .github/workflows/test-run-wo-codegen-weekly.yml, tests/test_datamodel_service.py, tests/test_flobject.py, tests/test_reduction.py
The build step was successful in the previous run. 
I'll open an issue to remove the version pinning when the original twine issue is generally resolved.
=> ci: pin twine to older version

src/ansys/fluent/core/session_solver_icing.py
closes https://github.com/ansys/pyfluent/issues/2986
1. override `__dir__` of `SolverIcing`
```
>>> dir(solver_icing)
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__'
, '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_batch_ops_service', '_build_from_fluent_connection', '_create_fro
m_server_info_file', '_datamodel_events', '_datamodel_service_se', '_datamodel_service_tui', '_error_state', '_events_service', '_field_data_service', '_file_transfer_api_warning', '_file_transfer_service', …
```
=> fix: override __dir__ method of SolverIcing

src/ansys/fluent/core/examples/downloads.py
closes https://github.com/ansys/pyfluent/issues/2978
1. Update examples download file path.
2. Handle examples download path based on all scenarios of `host_mount_path`.
Current working directory is the default location to download files.
```
>>> from ansys.fluent.core.examples import download_file 
>>> import_file_name = download_file("mixing_elbow.msh.h5", "pyfluent/mixing_elbow")
Download successful. File path:
D:\pyfluent\mixing_elbow.msh.h5   # File downloaded to current working directory.
>>>
```
=> fix: Update examples download path

src/ansys/fluent/core/services/field_data.py
closes https://github.com/ansys/pyfluent/issues/2976
Update `field_name` error allowed values.
**Now** 
```
>>> add_scalar_fields(field_name='absolute-pressur', surface_names=add_scalar_fields.surface_names.allowed_values())
File "D:\pyfluent\tests\debug.py", line 145, in <module>
add_scalar_fields(field_name='absolute-pressur', surface_names=add_scalar_fields.surface_names.allowed_values())
File "D:\pyfluent\src\ansys\fluent\core\services\field_data.py", line 355, in __call__
return self._field_data_accessor(*args, **kwargs)
File "D:\pyfluent\src\ansys\fluent\core\services\field_data.py", line 509, in add_scalar_fields_request
[
File "D:\pyfluent\src\ansys\fluent\core\services\field_data.py", line 512, in <listcomp> …
```
=> fix: Update field_name error allowed values

src/ansys/fluent/core/launcher/pyfluent_enums.py, tests/test_cad_to_post_wtm.py
@seanpearsonuk, we can have a discussion whether we want to support "2" or "2d" as well. I think that dimension=2 (as an integer) or enum is clean and without any confusion. version="2d" is still supported, with a deprecation warning. dimension="2d" seems a bit redundant. dimension="2" as string can be supported but with a warning??
What do you think?
=> refactor: update error message for Dimension enum.

CODEOWNERS
No issue tracker for this, as this suggestion is based on my anecdotal experience with codeowners and notifications. 
I believe we should only have the core and most active PyFluent developers, that can actually keep track of all the notifications, listed as `CODEOWNERS` with general ownership of the codebase.
For others like myself, and I believe @ajain-work, @dnwillia-work and @h-krishnan, we only want notifications to be sent to them when their attention is actually needed here. I do not believe we want to spam their emails with notifications from code ownership, which will drown out notifications that may be actually important and would then be missed.
In the future, if considered worthwhile, we can add ownership for specific files or folders in the codebase, so that review from these …
=> chore: Revising `CODEOWNERS` file

src/ansys/fluent/core/utils/search.py
closes https://github.com/ansys/pyfluent/issues/3002
Localize following imports.
```
from nltk.corpus import wordnet as wn
from ansys.fluent.core.services.datamodel_se import PyMenu, PyNamedObjectContainer
from ansys.fluent.core.session_pure_meshing import PureMeshing
```
=> fix: Localize imports in search.py

src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py, tests/test_settings_api.py
`create()` is available as a command in Fluent 25.1. This PR contains PyFluent side change.
`CreatableNamedObjectMixinOld` - mixin with create method for Fluent < 25.1.
`CreatableNamedObjectMixin` - mixin without create method for Fluent >= 25.1 as create is available as a command.
Please see the changed test_wildcard_fnmatch for the currently supported usage (backward compatibility is provided).
=> feat: Create as command in Fluent 25.1

src/ansys/fluent/core/workflow.py, tests/test_new_meshing_workflow.py
Compound child task_names() should have a format of the parent name followed by child number. Please see the test for details.
=> fix: name for compound child tasks

devel/scripts/copy_to_fluent.py, src/ansys/fluent/core/codegen/settingsgen.py
1. Do not create type-stub files when we create zip archive for settings API.
2. Remove some unnecessary data files.
This reduced the total size of the copied files by ~4 MB, down to 16.3 MB.
=> feat: Reduce size of the copied files to Fluent.

doc/source/user_guide/make_container_image.rst
closes https://github.com/ansys/pyfluent/issues/3046
Remove use of 'We'.
=> fix: Resolve vale warnings

src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/slurm_launcher.py
```
>>> import ansys.fluent.core as pyfluent
>>> slurm = pyfluent.launch_fluent(scheduler_options={"scheduler": "slurm", "scheduler_queue": "xyz"})  
File "/home/mkundu/devel/pyfluent/src/ansys/fluent/core/utils/deprecate.py", line 49, in wrapper
return func(*args, **kwargs)
File "/home/mkundu/devel/pyfluent/src/ansys/fluent/core/utils/deprecate.py", line 49, in wrapper
return func(*args, **kwargs)
File "/home/mkundu/devel/pyfluent/src/ansys/fluent/core/launcher/launcher.py", line 284, in launch_fluent
launcher = launcher_type(**launcher_argvals)
File "/home/mkundu/devel/pyfluent/src/ansys/fluent/core/launcher/slurm_launcher.py", line 394, in __init__
raise InvalidArgument(
ansys.fluent.core.exceptions.InvalidArgument: …
```
=> feat: Check valid Slurm queues

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/streaming_services/events_streaming.py, tests/test_events_manager.py
- Expose `Event` at package level.
- Enforce the `weakref.proxy` relationship between session and `EventsManager` from the top.
=> feat: event tweaks

.github/workflows/doc-build-release.yml, pyproject.toml, src/ansys/fluent/core/_version.py
Bump version to 0.22.0 due to recent project dependencies update.
=> build: Bump version to 0.22.0

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/session.py, src/ansys/fluent/core/session_meshing.py, src/ansys/fluent/core/session_pure_meshing.py, src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/streaming_services/events_streaming.py, tests/test_events_manager.py, tests/test_meshingmode/test_meshing_launch.py, tests/test_session.py
Don't allow `monitors` in `Meshing` session objects. #3082
The `events` object will be handled separately as it won't be a pure extraction.
=> fix: meshing session foreign objects

doc/source/user_guide/monitors.rst, tests/test_solver_monitors.py
- Test and doc for monitors.
- Met a few issues in usage.
- Maybe they are surmountable but it's hard to tell because of the documentation.
1. Have to load data **AND** initialize to get monitor set info through `monitors` service. The same info is in settings API after case read.
2. Cannot see how to register callback for a specific monitor set name. Get `N` callback calls per iteration for `N` monitor sets in the case.
3. The signature of the callback is not checked at registration. This signature is undocumented.
4. The callback interface could be extended to contain more contextual information, similar to the event callbacks.
=> docs: monitor

.github/workflows/ci.yml
In the previous code, the matrix parameter was dynamic turning the status checks for branch protection dynamic.
=> ci: Avoid dynamic status check

.github/workflows/test-run-custom.yml, Makefile, tests/integration/test_optislang/test_optislang_integration.py, tests/parametric/test_local_parametric_run.py
This fixes the crash observed in nightly test run. The following tests are still failing in the [branch run](https://github.com/ansys/pyfluent/actions/runs/10146333416) of nightly dev unittests:
```
2024-07-29T15:18:20.9219050Z FAILED tests/test_new_meshing_workflow.py::test_new_watertight_workflow - AssertionError: assert 1.0 == 0.41831
2024-07-29T15:18:20.9226433Z FAILED tests/parametric/test_local_parametric_run.py::test_local_parametric_run - assert None
2024-07-29T15:18:20.9227717Z FAILED tests/integration/test_optislang/test_optislang_integration.py::test_parametric_project - AssertionError: assert {'outlet_temp...3360076327903} == {'outlet_temp-op': 322.336008}
2024-07-29T15:18:20.9230681Z FAILED tests/test_new_meshing_workflow.py::test_new_fault_tolerant_workflow - TypeError: …
```
=> test: cleanup examples path before running unittests CI

src/ansys/fluent/core/solver/flobject.py, tests/parametric/test_parametric_workflow.py
Adding this temporary fix in PyFluent side, till Fluent code is fixed. The fix can be disabled by setting the env var `PYFLUENT_NO_FIX_PARAMETER_LIST_RETURN` to `1`.
=> fix: Temporary fix for parameter list() method

.github/workflows/ci.yml, src/ansys/fluent/core/launcher/standalone_launcher.py
If 'dry_run' is set to True in standalone mode: will not launch Fluent, and will instead print configuration information that would be used as if Fluent was being launched.
=> refactor: Update dry_run for stand-alone launcher.

tests/test_solver_monitors.py
closes https://github.com/ansys/pyfluent/issues/3179
Use timeout loop for `test_solver_monitors` (Fix for nightly dev test run)
=> fix: Use timeout loop for test_solver_monitors

tests/test_meshing_utilities.py
Activate this test once the fluent side changes are available.
=> refactor: Skip meshing utilities test.

doc/api_rstgen.py
Correct rst file generation path
@prmukherj This change should be part of patch release if 0.24.0 tag pushed already. I will create patch release if needed.
Tracking nightly doc build[ here](https://github.com/ansys/pyfluent/actions/runs/10440697186).
Correct API docs -
=> fix: Correct rst file generation path

src/ansys/fluent/core/post_objects/post_helper.py, tests/test_solver_monitors.py
The monitors was defined before the root was available. This current design solves that issue.
=> fix: Bug in visualization.

src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/settings_external.py
closes https://github.com/ansys/pyfluent/issues/3116
Handle the error message according to Fluent version.
1. Use `_search` if Fluent version and latest api_tree pickle file version is same.
Earlier -
```
>>> import os
>>> os.environ["PYFLUENT_FLUENT_ROOT"] = r"D:\Installations\Ansys\v222_07082024\ANSYS Inc\v222\fluent"
>>> import ansys.fluent.core as pf
>>> solver = pf.launch_fluent(ui_mode="gui")
>>> solver.file.read_case
AttributeError: 'file' object has no attribute 'read_case'.
The most similar API names are:
file.read_case (Command)
file.read_case_data (Command)
file.read_case_setting (Command)
```
Now -
=> fix: Correct error message for Fluent versions

codegen/allapigen.py
Maintain a single fluent session for codegen. Close one session before starting a new one. It will solve issue with users haing Ansys student version where multiple sessions are not supported.
=> refactor: Maintain a single fluent session for codegen.

src/ansys/fluent/core/workflow.py, tests/test_new_meshing_workflow.py
Fix for both PyConsole and PyFluent.
Please refer to test for more details: "tests/test_new_meshing_workflow\test_duplicate_children_of_compound_task"
=> fix: Compound child creation and naming.

doc/source/user_guide/legacy/tui.rst
Example was removed in https://github.com/ansys/pyfluent/pull/3048, but this reference to it remains
=> docs: Remove reference to example that doesn't exist anymore

src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/services/reduction.py, tests/test_reduction.py
Earlier solver.fields.reduction.<any Point type> was returning a protobuf message. Currently they are wrapped as a python class.
For instance:
Earlier behavior:
```Python
>>> x = solver.fields.reduction.force(locations=["wall"])
>>> x
x: 2.862068334485282
y: -2.5299803741481259
z: -0.0014375438414745349
>>> type(x)
<class 'ansys.api.fluent.v0.common_api_pb2.Point'>
```
Current behavior:
```Python
>>> x = s.fields.reduction.force(locations=["wall"])
>>> x                                                
(2.600005424922768e-31, -1.080374020897745e-24, 3.302743550728087e-17)
>>> type(x) 
<class 'tuple'>
>>> type(x[0]) 
<class 'float'>
```
=> fix: Convert protobuf Point to python Vector.

src/ansys/fluent/core/launcher/error_handler.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, tests/test_launcher.py
We don't need to compare 'FluentEnums' for greater than or less than the other now. Only '==' should be supported and that is there by default.
~For UIMode, the other operations should be supported as well.~
=> refactor: Clean-up PyFluent Enums.

src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/launcher/error_handler.py, tests/test_casereader.py
1. Case reader to support operations for reading mesh files.
2. The attributes not relevant to a mesh file returns None type container.
3. The below usage is supported now:
>>> mesh_reader_2d.get_mesh().get_mesh_type() == MeshType.SURFACE
=> feat: Add mesh reading capability to case reader.

src/ansys/fluent/core/workflow.py, tests/test_new_meshing_workflow.py
Deprecate the way we used to access tasks in the enhanced meshing workflow using display names.
For example:
>>> watertight.task("Import Geometry")  -->> is now deprecated
Alternate usage:
>>> watertight.import_geometry
Further:
Provide verbose deprecation warning suggesting the alternate usages.
Still ongoing:
Update tests.
=> refactor: Deprecate 'task' from enhanced meshing workflow.

src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
Earlier: 
While populating the python names, the special characters were converted to '_'.
Now:
Only skip '..' pattern.
=> fix: Handle special characters in child aliases.

src/ansys/fluent/core/launcher/error_handler.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/systemcoupling.py, src/ansys/fluent/core/utils/fluent_version.py, tests/test_flobject.py, tests/test_fluent_version.py
1. '<session>.setup.models' should be '<session>.settings.setup.models' from versions 25.1 and above.
2. solver.settings.setup.models.viscous.model.set_state("k-epsilon"), etc. were returning some values in PyConsole. This has been rectified.
3. FluentVersion enum's string representation has been updated as follows:
>>> str(FluentVersion.v241) -> 'Fluent version 2024 R1'
=> fix: fix minor issues in settings and fluent version.

src/ansys/fluent/core/workflow.py
There is an issue with pre-created compound child tasks where the parent name is missing.
=> fix: Issue with pre-created compound child tasks in ftm workflow.

src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
Remove 'exit' from solver.settings in PyFluent exposure since we have a well documented way of exiting in PyFluent: solver.exit(). It solves a bug arising from solver.settings.exit() as well.
Earlier:
>>> solver.settings.exit()
Now:
"exit" not present in dir(solver.settings) and using it raises an attribute error.
=> fix: Remove exit from settings.

src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py
Support some edge cases - those won't affect 25.1 settings API aliasing behaviour.
=> test: Add test for _combine_set_states

src/ansys/fluent/core/codegen/settingsgen.py, src/ansys/fluent/core/data_model_cache.py, src/ansys/fluent/core/solver/flobject.py, tests/test_codegen.py, tests/test_flobject.py
`flproxy._scheme_eval` was not available in PyConsole (it has been made temporarily available which will be removed). I have added a static `version` attribute to the generated classes.
=> fix: Avoid flproxy._scheme_eval in pyfluent code

src/ansys/fluent/core/examples/downloads.py
closes https://github.com/ansys/pyfluent/issues/3110
Remove `PyFluentUserWarning` on example download.
```
>>> from ansys.fluent.core import examples
>>> import_case = examples.download_file(file_name="exhaust_system.cas.h5", directory="pyfluent/exhaust_system")
>>> import_case = examples.download_file(file_name="exhaust_system.cas.h5", directory="pyfluent/exhaust_system")
>>>
```
=> feat: Remove PyFluentUserWarning on example download

src/ansys/fluent/core/session_solver.py, src/ansys/fluent/core/solver/flobject.py, tests/test_fluent_session.py
After settings access, solver session object was not getting garbage collected due to the cyclic reference: solver_session -> settings objects -> solver_session._interrupt.
=> fix: Session was not garbage collected after settings access

src/ansys/fluent/core/filereader/case_file.py
Update Mesh class docstring to clarify its scope of usability.
=> docs: mesh

src/ansys/fluent/core/streaming_services/events_streaming.py, tests/test_events_manager.py
Implemented sync events for IterationEnded and TimestepEnded to execute PyFluent-side callbacks synchronously. Fluent's solution monitoring mechanism has been used for the implementation. On every solution event, Fluent streams an auto-pause event and then goes to a paused state. Upon receiving the auto-pause event, the client executes the PyFluent-side callback and then remotely resumes Fluent.
Any exception thrown in the callback is converted to a logging error to ensure Fluent resumes at the end of callback execution. Those exceptions are raised in a secondary thread, the user's script cannot react in any way to those exceptions from the primary thread. There could still be some edge cases like calling `solver.exit()` within the callback which will indefinitely hang Fluent.
=> feat: Implement IterationEndedSyncEvent and TimestepEndedSyncEvent

src/ansys/fluent/core/solver/flobject.py
Small refactoring of command classes, so `Command` and `CommandWithPositionalArgs` behave almost similarly. The only difference between these 2 classes is the call signature.
=> refactor: small refactoring of command classes

src/ansys/fluent/core/session_solver.py
=> fix: Add missing event_type argument to BaseSession._build_from_fluent_connection

.github/workflows/ci.yml, .vale.ini
PyAnsys code-style checker has been introduced in place of a custom one.
Later we can shift to PyAnsys checkers to reduce manual effort in maintaining (for doc-style checking as well).
=> ci: use PyAnsys doc formattor and code-style checker.

src/ansys/fluent/core/services/datamodel_tui.py, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py, tests/test_tui_api.py
ADO Fluent PR 530389
GitHub fluids-webui PR 398
Changes
- Hiding switch-to-meshing-mode command from solver.tui and solver.settings
- Adding tests to make sure this command does not appear in either location as we will most likely never want it in those locations, in my understanding
=> fix: Hiding switch-to-meshing-mode command from tui and settings

.ci/fluent_test_runner.py, .github/workflows/test-fluent-journals.yml, .github/workflows/test-fluent-tests.yml, pyproject.toml, tests/fluent/test_assert/test.py, tests/fluent/test_meshing_workflow/test.py, tests/fluent/test_meshing_workflow/test.yaml, tests/fluent/test_settings_api/test.py, tests/fluent/test_version/test.py
A new CI has been added to run Python test journals in the Fluent docker container. During the test run, the PyFluent library within the docker container is replaced with the library built from the current PyFluent branch. The primary goal is to test the impact of PyFluent changes in Fluent's PyConsole before adding those changes in Fluent.
=> ci: Infrastructure to run PyConsole tests in GitHub with Fluent docker image

src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py, tests/test_settings_api.py
The `argument-aliases` attribute is queried at runtime as it is not part of the static-info yet (this wll be changed in 25.2).
=> feat: Support argument aliases in PyFluent

src/ansys/fluent/core/solver/flobject.py, tests/parametric/test_parametric_workflow.py
Update `baseCommand._fix_parameter_list_return()` to handle units more robustly.
=> fix: Handle unitless parameters

src/ansys/fluent/core/solver/flobject.py
Additional change over #3427 to handle PyConsole's case where the symbols are not stripped in the command return value.
=> fix: unitless parameter for pyconsole

src/ansys/fluent/core/solver/flobject.py, tests/test_flobject.py
This PR removes settings API hash comparison and runtime generation of settings API classes. This is not required anymore because:
- In PyConsole, we don't use this mechanism. The latest settings API classes are always generated while building Fluent.
- In released versions of PyFluent, the settings API classes generated from the latest Fluent images are up-to-date.
- This was useful only during the local development of PyFluent to avoid running settingsgen after updating the Fluent code. However, it is better to run settingsgen in this case so the generated files are used and tested during local development. Note that, we can run just settingsgen as `python src\ansys\fluent\core\codegen\settingsgen.py` which takes much less time than full codegen.
This PR saves 4s during the first …
=> fix: Remove settings API hash comparison and runtime generation of settings API classes

src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/utils/networking.py, src/ansys/fluent/core/workflow.py
PyFluent side fix for the Fluent defect 1027129
=> fix: Remove _get_child_object_display_names which is via get_specs

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/launcher_utils.py
Related Fluent bug - 1160401
Adding option to clear some environment variables related to parallel Fluent before launch_fluent(). These env vars control number of processors of Fluent process launched from meshing PyConsole.
=> fix: Option to clear Fluent parallel env vars

src/ansys/fluent/core/fluent_connection.py
"othermethods" to "other methods"
=> fix: missing space in fluent_connection.py

tests/test_flobject.py, tests/test_reduction.py
The fixed tests have been kept disabled so that the PR CI passes. I'll enable them after the stable image version is updated.
=> ci: Fix nightly tests for the latest Fluent image

doc/source/contributing/environment_variables.rst, doc/source/contributing/index.rst, doc/source/index.rst
The documentation is intended for developers.
=> docs: Document all environment variable usage in PyFluent

examples/00-fluent/DOE_ML.py, examples/00-fluent/ahmed_body_workflow.py, examples/00-fluent/brake.py, examples/00-fluent/conjugate_heat_transfer.py, examples/00-fluent/exhaust_system_settings_api.py, examples/00-fluent/external_compressible_flow.py, examples/00-fluent/lunar_lander_thermal.py, examples/00-fluent/mixing_elbow_settings_api.py, examples/00-fluent/modeling_ablation.py, examples/00-fluent/modeling_cavitation.py, examples/00-fluent/parametric_static_mixer_1.py, examples/00-fluent/radiation_headlamp.py, examples/00-fluent/tyler_sofrin_modes.py
1. Print Fluent version in examples.
2. Avoid setting `solver.solution.monitor.residual.options.plot` which is not necessary.
3. I've also removed `<session>.health_check.status()` calls as user doesn't need to execute them.
=> docs: Print Fluent version in examples

src/ansys/fluent/core/codegen/builtin_settingsgen.py, src/ansys/fluent/core/solver/settings_builtin_bases.py, src/ansys/fluent/core/solver/settings_builtin_data.py, tests/test_builtin_settings.py
Example of multiple named object parents:
```
assert (
DesignPoint(
settings_source=solver,
parametric_studies="mixing_elbow-Solve",
name="Base DP",
)
== solver.parametric_studies["mixing_elbow-Solve"].design_points["Base DP"]
```
=> feat: Handle names in parent path for direct settings objects

src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/systemcoupling.py, tests/test_systemcoupling.py
Use Fluent settings APIs to query System Coupling information instead of writing and reading SCP files.
=> feat: use settings apis for system coupling

doc/source/user_guide/legacy/tui.rst
Documenting the missing TUI commands in PyFluent. These commands can be accessed only interactively in Fluent TUI.
=> docs: Document missing TUI commands

.github/workflows/ci.yml, .github/workflows/test-run-dev-version-nightly.yml, doc/source/contributing/environment_variables.rst, doc/styles/config/vocabularies/ANSYS/accept.txt, src/ansys/fluent/core/codegen/__init__.py, src/ansys/fluent/core/codegen/allapigen.py, src/ansys/fluent/core/codegen/builtin_settingsgen.py, tests/conftest.py
1. Run unittests with Fluent 25.2 image in the main CI. I have kept the job separate as we cannot yet package 25.2 API code.
2. Run unittests with Fluent 25.2 image in the nightly dev CI. `FLUENT_STABLE_IMAGE_DEV` will be updated from there.
3. Relax some conditions such that the direct settings classes can be generated from any Fluent version.
=> ci: Run unittests with 25.2 Fluent image in CIs

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/process_launch_string.py, tests/test_launcher.py
Added new module variable `FLUENT_AUTOMATIC_TRANSCRIPT` which is `False` by default.
=> fix: Skip Fluent's automatic transcript by default

pyproject.toml
closes https://github.com/ansys/pyfluent/issues/3494
We need following dependencies for local PyFluent cheat sheet generation.
1. quarto-cli
2. pdf2image
3. poppler 
**poppler on windows** 
1. Download latest release from [here](https://github.com/oschwartz10612/poppler-windows/releases/).
2. Extract zip.
3. Add <Release-24.08.0-0\poppler-24.08.0\Library\bin> to path.
**poppler on Linux**
1. Follow steps described in the ci.yml.
=> fix: Cheat sheet dependencies

codegen/allapigen.py, src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/search.py, src/ansys/fluent/core/solver/flobject.py, src/ansys/fluent/core/solver/settings_external.py, src/ansys/fluent/core/utils/__init__.py, tests/test_search.py
closes https://github.com/ansys/pyfluent/issues/3496, https://github.com/ansys/pyfluent/issues/3498, https://github.com/ansys/pyfluent/issues/3500https://github.com/ansys/pyfluent/issues/3499
**Improve synset handling**
1. Removed empty synset lists.
2. Removed duplicate values from synset list.
3. Store synset names.
**Remove duplicate data and dependency on `api_tree_version.pickle` file**
1. Removed need of the  `api_tree_<version>.pickle` file.
**Refactor flobject.py for search function**
1. Refactored `_search`.
2. Added module level variable to return or print results as per the requirement.
4. Refactored flobject.py
5. Refactored `test_search.py` and removed tests related to legacy search function.
6. Refactored `settings_extrenal.py`
**Reorder search function**
1. Changed the …
=> feat: search module improvements

doc/source/user_guide/fields/field_data.rst, doc/source/user_guide/fields/reduction.rst, doc/source/user_guide/index.rst, doc/source/user_guide/offline/file_session.rst, doc/source/user_guide/session/session.rst, pyproject.toml, src/ansys/fluent/core/solver/function/reduction.py, tests/test_reduction.py
Update the reduction docs to highlight the functional usage (particularly in cases with multiple solvers).
Correct and update the field_data docs as well.
Update reduction tests to highlight the functional behaviour.
=> docs: update reduction docs

src/ansys/fluent/core/codegen/settingsgen_old.py, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
This will be required after #3508 is realized in settings API. We do not have any other way to recover the original scheme names of aliases as they are not real classes in settings API.
I've avoided generation of explicit classes for aliases as it results into too much duplication of class hierarchy at various levels. We need to support a different journaling behaviour for alias classes and their descendents.
=> feat: Store the original scheme name of aliases

examples/00-fluent/brake.py, examples/00-fluent/parametric_static_mixer_1.py, examples/00-fluent/radiation_headlamp.py
closes https://github.com/ansys/pyfluent/issues/3469
As title says
=> fix: Update example scripts for 25R1

doc/source/user_guide/fields/field_data.rst
Update documentation of field_data:
1. Better description with inline comments.
2. Using converged data.
=> docs: Update field_data docs.

src/ansys/fluent/core/__init__.py, src/ansys/fluent/core/launcher/launcher_utils.py, src/ansys/fluent/core/launcher/standalone_launcher.py
Requested by @PyPablo 
We cannot expose this as a full feature due to the limitations mentioned in #3436. Exposing a hidden way to access Fluent's stdout/stderr.
```
import subprocess
pyfluent.LAUNCH_FLUENT_STDOUT = subprocess.PIPE
solver = pyfluent.launch_fluent()
for line in iter(solver._process.stdout.readline, b''):
decoded_line = line.decode('utf-8')
print(decoded_line, end='')
if decoded_line.startswith("Cleanup script file"):  # Any other termination condition, e.g. break after 10 lines
break
```
Note that, this doesn't work in `ui_mode="gui"` as mentioned in #3436.
=> feat: Add a hidden way to access Fluent's stdout/stderr

src/ansys/fluent/core/search.py
closes https://github.com/ansys/pyfluent/issues/3502
Settings results are at the top.
TUI results are at the end.
=> fix: Show search results in a particular order

src/ansys/fluent/core/solver/flobject.py
Empty group and named-object should return an empty dictionary as state.
Empty list-object should return an empty list as state.
Scheme doesn't distinguish between empty list and empty dictionary, so we cannot fix it in the server side.
=> fix: Correct type for empty states

src/ansys/fluent/core/post_objects/post_helper.py
closes https://github.com/ansys/pyfluent/issues/3512
Replaced scheme call in `get_vector_fields()`
=> feat: Replace scheme call in get_vector_fields

src/ansys/fluent/core/data_model_cache.py
closes https://github.com/ansys/pyfluent/issues/1772
1. Updated _update_cache_from_variant_state & update_cache
2. Renamed updaterFn -> updater_fn
=> refactor: Data model cache refactoring

.github/workflows/ci.yml, .github/workflows/doc-build-dev-nightly.yml, .github/workflows/doc-build-release.yml, doc/source/conf.py, doc/source/contributing/environment_variables.rst, doc/source/user_guide/events.rst, src/ansys/fluent/core/streaming_services/events_streaming.py, tests/test_events_manager.py
Add documentation of event streaming callback.
I think the signature
```
def cb(session, event_info, x, y):  # additional arguments at end
```
would be preferred over 
```
def cb(x, y, session, event_info)  # additional arguments at start
```
The current implementation supports both.
=> docs: event streaming callback

.github/workflows/ci.yml, .github/workflows/doc-build-dev-nightly.yml, .github/workflows/doc-build-release.yml, doc/api_rstgen.py, doc/source/api/index.rst, doc/source/cheatsheet/cheat_sheet.qmd, doc/source/user_guide/solver_settings/solution.rst
closes https://github.com/ansys/pyfluent/issues/3562, https://github.com/ansys/pyfluent/issues/3563
=> docs: Update API reference and cheat sheet

src/ansys/fluent/core/launcher/fluent_container.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py, tests/conftest.py, tests/test_datamodel_api.py, tests/test_datamodel_service.py, tests/test_mapped_api.py, tests/util/__init__.py
Adding StateEngine unittests corresponding to the new datamodel API. 
Added test_datamodel_api.py for testDataModelApi.cpp and testMappedApi.cpp. I've skipped testMFWMappedApi.cpp as this seems to be at workflow level - we can add it after updating the workflow classes based on the new API.
Some issues found are mentoned in TODO comments in the test code - will address them in separate PRs.
=> test: Add tests for new datamodel API

src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, src/ansys/fluent/core/launcher/server_info.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py, tests/test_launcher.py
Use case of the `dry_run` argument of the `launch_fluent()` to use with external launcher for launching Fluent in a different machine.
1. Assume a shared directory between the server machine (where Fluent is launched) and client machine (where PyFluent is run) is available at path `/mnt/shared` in the server machine and `\\server\shared` in the client machine.
2. Set the environment variable `SERVER_INFO_DIR` to `/mnt/shared` in the server machine and `\\server\shared` in the client machine.
3. In client, `launch_fluent(fluent_path=<path to fluent exe as in the server machine>, dry_run=True)` will return a tuple containing Fluent launch string and the absolute path of the server info file in client.
4. Fluent is launched by the external launcher using the Fluent launch string returned …
=> feat: Return launch and connection info from standalone launcher dry-run

.github/workflows/ci.yml, tests/test_datamodel_service.py, tests/test_flobject.py
This will fix the current CI failure which is due to not using `FLUENT_STABLE_IMAGE_DEV` for 25.2 test run.
`FLUENT_STABLE_IMAGE_DEV` has not been used for 25.2 till now as we didn't have a passing 25.2 nightly build which would update a 25.2 image version to `FLUENT_STABLE_IMAGE_DEV` when the 25.2 CI was added.
=> ci: Use stable image version for 25.2

pyproject.toml, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/services/interceptors.py, tests/test_error_handling.py
=> feat: Python error via grpc

pyproject.toml, src/ansys/fluent/core/services/field_data.py, tests/test_field_data.py
```
import pyvista as pv
import numpy as np
from ansys.fluent.core.services.field_data import CellElementType
def convert_fluent_element_type_to_pv_cell_type(element_type):
if element_type == CellElementType.TETRAHEDRON:
return pv.CellType.TETRA
if element_type == CellElementType.HEXAHEDRON:
return pv.CellType.HEXAHEDRON
raise ValueError(f"Unknown element type {element_type}")
solver = pyfluent.launch_fluent(processor_count=4)
solver.settings.file.read_case(file_name="d:/work/elbow.cas.h5")
mesh = solver.fields.field_data.get_mesh(zone_id=2)
points = np.array([(node.x, node.y, node.z) for node in mesh.nodes])
cells = np.array([[len(element.node_indices)] + element.node_indices for element in mesh.elements]).ravel()
cell_types = …
```
=> feat: Retrieve mesh data in solution mode

src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/streaming_services/datamodel_event_streaming.py, tests/test_datamodel_api.py, tests/test_mapped_api.py
=> feat: Datamodel cb signature for various events

pyproject.toml, src/ansys/fluent/core/services/field_data.py, tests/test_field_data.py
```
import pyvista as pv
from ansys.fluent.core.services.field_data import CellElementType
def convert_fluent_element_type_to_pv_cell_type(element_type):
if element_type == CellElementType.POLYHEDRON:
return pv.CellType.POLYHEDRON
raise ValueError(f"Unknown element type {element_type}")
solver = pyfluent.launch_fluent(processor_count=4)
solver.settings.file.read_case(file_name="d:/work/Static_Mixer_main.cas.h5")
mesh = solver.fields.field_data.get_mesh(zone_id=97)
points = [(node.x, node.y, node.z) for node in mesh.nodes]
cells = []
for element in mesh.elements:
connectivity = []
connectivity.append(len(element.facets))
for facet in element.facets:
connectivity.append(len(facet.node_indices))
connectivity.extend(facet.node_indices) …
```
=> feat: Polyhedral connectivity

.github/workflows/ci.yml, .github/workflows/test-run-nightly.yml, doc/source/contributing/index.rst, doc/source/getting_started/faqs.rst, doc/source/getting_started/installation.rst, doc/source/user_guide/index.rst, doc/source/user_guide/session/launching_ansys_fluent.rst, examples/00-fluent/conjugate_heat_transfer.py, examples/00-fluent/lunar_lander_thermal.py, examples/00-fluent/modeling_ablation.py, examples/00-fluent/tyler_sofrin_modes.py, src/ansys/fluent/core/_version.py, src/ansys/fluent/core/codegen/tuigen.py, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/pim_launcher.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/launcher/standalone_launcher.py
Change doc and CI to reflect Fluent 25.1 as the primary release version.
This PR doesn't incude changes in cheatsheet and docker build instructions.
=> chore: Doc/CI update for 25.1 release

pyproject.toml, src/ansys/fluent/core/services/field_data.py, tests/test_field_data.py
Please see Fluent PR 554907 for details.
Needs some performance investigation in terms of both speed and memory. The Python side processing is 10X slower than fetching the data from server.
=> feat: Avoid serialization of mesh data response

.github/workflows/ci.yml, .github/workflows/doc-build-dev-nightly.yml, .github/workflows/doc-build-release.yml, doc/Makefile, doc/changelog.d/3671.dependencies.md, doc/make.bat, doc/source/contributing/index.rst
closes https://github.com/ansys/pyfluent/issues/3480
No need to execute following scripts manually to build all docs locally.
```
python doc/api_rstgen.py
python doc/datamodel_rstgen.py
python doc/tui_rstgen.py
python doc/settings_rstgen.py
```
Just execute the following commands to build all docs locally.
```
pip install ansys-fluent-core[docs]
cd doc
set BUILD_ALL_DOCS=1
set FLUENT_IMAGE_TAG=v0.25.1
make html
```
=> build: Update local doc build instructions

doc/changelog.d/3673.fixed.md, src/ansys/fluent/core/launcher/pim_launcher.py
closes https://github.com/ansys/pyfluent/issues/3672
Earlier - 
Now -
=> fix: Dimensionality correction in PIM launcher

doc/changelog.d/3684.miscellaneous.md, src/ansys/fluent/core/journaling.py
closes https://github.com/ansys/pyfluent/issues/3059
Python journaling is available in Fluent version 2023 R1 or later. 
**Earlier**
```
>>> import os
>>> os.environ["PYFLUENT_FLUENT_ROOT"] = r"D:\Installations\Ansys\v222_07082024\ANSYS Inc\v222\fluent"
>>> import ansys.fluent.core as ppf
>>> solver = ppf.launch_fluent()
>>> solver.journal.start("test_222_jou.py") 
Error: eval: unbound variable
Error Object: api-start-python-journal
File "D:\pyfluent\src\ansys\fluent\core\journaling.py", line 13, in start
self._app_utilities.start_python_journal(journal_name=file_name)
File "D:\pyfluent\src\ansys\fluent\core\services\app_utilities.py", line 189, in start_python_journal
self.scheme_eval.exec([f'(api-start-python-journal …
```
=> refactor: Raise an exception for Python journaling in 22R2

doc/changelog.d/3691.added.md, pyproject.toml, src/ansys/fluent/core/services/app_utilities.py, src/ansys/fluent/core/session.py, tests/test_session.py
closes https://github.com/ansys/pyfluent/issues/2945
```
D:\pyfluent>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ansys.fluent.core import launch_fluent
>>> solver = launch_fluent()
>>> solver._app_utilities.get_controller_process_info()
{'hostname': 'AAPQ13pUvWxQtxN', 'process_id': 339960, 'working_directory': 'D:\\pyfluent'}
>>> solver._app_utilities.get_solver_process_info()     
{'hostname': 'AAPQ13pUvWxQtxN.win.ansys.com', 'process_id': 350440, 'working_directory': 'D:/pyfluent'}
>>> solver.chdir("D:\pyfluent\codegen")
>>> solver._app_utilities.get_controller_process_info()
{'hostname': 'AAPQ13pUvWxQtxN', 'process_id': 339960, …
```
=> feat: Change working directory

.github/workflows/ci.yml, .github/workflows/doc-build-dev-nightly.yml, doc/changelog.d/3699.documentation.md, doc/source/conf.py, pyproject.toml
closes https://github.com/ansys/pyfluent/issues/3693
=> docs: Fix examples gallery [skip tests]

.ci/get_hanging_tests.py, doc/changelog.d/3711.miscellaneous.md, doc/changelog.d/3714.maintenance.md
closes https://github.com/ansys/pyfluent/issues/3305
```
PS D:\pyfluent> python .\.ci\get_hanging_tests.py -logfile D:\github_logs.txt
Hanging tests detected.
tests/test_fluent_session.py::test_exit_fluent_when_connected_to_running_fluent
tests/test_utils.py::test_timeout_loop
PS D:\pyfluent> 
```
=> chore: Get hanging test names by parsing the GitHub logs [skip tests]

.ci/get_hanging_tests.py, doc/changelog.d/3711.miscellaneous.md, doc/changelog.d/3712.documentation.md, doc/changelog.d/3713.added.md, doc/changelog.d/3714.maintenance.md, doc/source/user_guide/fields/field_data.rst, doc/source/user_guide/fields/reduction.rst, src/ansys/fluent/core/services/datamodel_se.py, tests/conftest.py, tests/test_mapped_api.py, tests/test_search.py
The mapping of datamodel to API is now happening in a more encapsulated way in the server and we simply require the name of the mapped datamodel API to be passed as the `rules` argument in each call.
=> feat: remove application of mapped metadata

doc/changelog.d/3721.documentation.md, doc/source/user_guide/session/launching_ansys_fluent.rst
closes https://github.com/ansys/pyfluent/issues/229
=> docs: Update docs to connect Fluent launched on Linux [skip tests]

.github/workflows/execute-examples-weekly.yml, doc/changelog.d/3730.maintenance.md
closes https://github.com/ansys/pyfluent/issues/3729
=> ci: Add workflow for examples [skip tests]

doc/changelog.d/3742.miscellaneous.md, src/ansys/fluent/core/launcher/launcher_utils.py
Revert the new dm api as default. 
There will be a separate branch with this change so that no PyFluent version is released with this as of now.
=> refactor: Revert the new dm api as default.

README.rst, doc/changelog.d/3772.documentation.md
closes https://github.com/ansys/pyfluent/issues/3771
Current link points to https://cheatsheets.docs.pyansys.com/pyfluent_cheat_sheet.png and https://cheatsheets.docs.pyansys.com/pyfluent_cheat_sheet.pdf
Now it will point to https://fluent.docs.pyansys.com/version/stable/_static/cheat_sheet.pdf.
=> docs: Update cheat sheet link [skip tests]

src/ansys/fluent/core/__init__.py
Bump version to v0.30.dev3.
This will test the PyConsole locally and will lead into v0.30.0 to be integrated with PyConsole.
=> build: Bump version to v0.30.dev3

doc/changelog.d/3792.fixed.md, src/ansys/fluent/core/services/datamodel_tui.py, tests/test_tui_api.py
Keep `solver.tui.switch_to_meshing_mode` as hidden as it is expected in Fluent journals.
Fluent bug id - 1218147
=> fix: Keep switch-to-meshing as hidden to fix Fluent journal replay.

doc/changelog.d/3797.fixed.md, doc/changelog.d/changelog_template.jinja, doc/source/contributing/environment_variables.rst, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
Runtime Python classes for settings API are still supported in Fluent's Python console behind an environment variable. This PR fixes an issue with python-name in the runtime classes.
=> fix: Fix python_name issue in runtime python classes

doc/changelog.d/3807.documentation.md, doc/source/user_guide/solver_settings/solver_settings_contents.rst
closes https://github.com/ansys/pyfluent/issues/3806
```
>>> energy = pyfluent.solver.Energy(settings_source=solver)
>>> energy()             
{'enabled': True, 'viscous_dissipation': False, 'pressure_work': False, 'kinetic_energy': False, 'inlet_diffusion': True}
>>> dir(energy)
['__call__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_add_units_to_state', '_check_stable', '_child_alias_objs', '_child_aliases', …
```
=> docs: Fix built in settings doc [skip tests]

doc/changelog.d/3832.added.md, pyproject.toml, src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/filereader/data_file.py, src/ansys/fluent/core/report.py
Replace use of a module, `lxml` with `xml` from the standard library. The `lxml` package has a known vulnerability.
=> feat: Remove lxml

.github/workflows/label.yml, doc/changelog.d/3840.maintenance.md
closes https://github.com/ansys/pyfluent/issues/3839.
This prevents the action from removing labels that no longer match the configuration file or changes in the pull request.
=> chore: Do not sync labels [skip tests]

doc/api_rstgen.py, doc/changelog.d/3861.fixed.md, doc/source/cheatsheet/cheat_sheet.qmd, src/ansys/fluent/core/launcher/watchdog_exec
closes https://github.com/ansys/pyfluent/issues/3860
Avoid file name as native Python package, it creates conflicts during imports.
=> fix: Avoid file name as native Python package

doc/changelog.d/3853.added.md, doc/source/user_guide/session/launching_ansys_fluent.rst, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/pyfluent_enums.py, tests/test_pre_post_session.py
closes https://github.com/ansys/pyfluent/issues/3852
Support new PRE_POST launch mode.
```
>>> pre_post = pyfluent.launch_fluent(ui_mode="gui", mode=pyfluent.FluentMode.PRE_POST) 
>>> from ansys.fluent.core import examples
>>> file_name = examples.download_file("mixing_elbow.cas.h5", "pyfluent/mixing_elbow")
>>> pre_post.settings.file.read_case(file_name=file_name)
Fast-loading "D:\ANSYSDev\vNNN\fluent\fluent25.2\\addons\afd\lib\hdfio.bin"
Done.
Multicore SMT processors detected. Processor affinity set!
>>> pre_post.settings.solution.initialization.hybrid_initialize()     
Hybrid initialization is done.
>>> pre_post.settings.solution.run_calculation.iterate(iter_count=10)
File …
```
=> feat: Support PRE_POST mode

.github/workflows/ci.yml, doc/api_rstgen.py, doc/changelog.d/3865.added.md, doc/source/api/api_contents.rst, doc/source/contributing/contributing_contents.rst, src/ansys/fluent/core/codegen/datamodelgen.py, src/ansys/fluent/core/meshing/meshing_workflow.py, src/ansys/fluent/core/services/datamodel_se.py, src/ansys/fluent/core/session_base_meshing.py, src/ansys/fluent/core/session_shared.py, src/ansys/fluent/core/workflow.py, tests/test_codegen.py, tests/test_datamodel_service.py, tests/test_new_meshing_workflow.py
Generate the derived classes of the following types in the generated datamodel code:
`PyCommandArguments`
`PyTextualCommandArgumentsSubItem`
`PyNumericalCommandArgumentsSubItem`
`PyDictionaryCommandArgumentsSubItem`
`PyParameterCommandArgumentsSubItem`
`PySingletonCommandArgumentsSubItem`
=> feat: codegen for datamodel command arguments

doc/api_rstgen.py, doc/changelog.d/3879.fixed.md, src/ansys/fluent/core/codegen/datamodelgen.py, tests/test_datamodel_service.py
Ensure field-level is received from gRPC for all the following type of entities:
- Parameter
- Singleton/NamedObject (currently no Singleton/NamedObject contains field-level help)
- Command/Query
- Parameter-type command/query argument
- Singleton-type command/query argument
Corresponding Fluent PR - 574286
=> fix: Fix missing field-level help at various levels

.github/workflows/doc-build-dev-nightly.yml, .github/workflows/execute-examples-weekly.yml, .github/workflows/test-fluent-journals.yml, .github/workflows/test-run-dev-version-nightly.yml
Add CI_RUN env to all workflows using 25.2 image to provide a temporary fix for #3926
Related #3927
=> ci: Add CI_RUN env to all workflows using 25.2 image [skip tests]

doc/changelog.d/3939.fixed.md, tests/test_reduction.py
`test_reduction_does_not_modify_case` is failing for latest 25R2 image.
=> fix: Skip test_reduction_does_not_modify_case [skip tests]

doc/changelog.d/3943.fixed.md, src/ansys/fluent/core/workflow.py, tests/test_new_meshing_workflow.py
The refresh task accessor was needed to be called after inserting compound child task.
=> fix: Nightly meshing tests.

doc/changelog.d/3948.fixed.md, src/ansys/fluent/core/solver/flobject.py, tests/test_settings_api.py
For "deprecated" settings, we should hide the exposure, but not block the access. With the current PR changes, we get the following behaviour in both pyfluent and pyconsole:
```
>>> v1 = solver.settings.results.graphics.vector.create()
>>> v1.scale.scale_f = 4
>>> "scale" in dir(v1)
False
```
Nightly dev doc run - https://github.com/ansys/pyfluent/actions/runs/14606954687
=> fix: Fix deprecated behaviour

doc/changelog.d/3951.fixed.md, src/ansys/fluent/core/filereader/case_file.py, src/ansys/fluent/core/filereader/data_file.py, src/ansys/fluent/core/filereader/pre_processor.py, tests/test_casereader.py
XMLParser gives a ParseError if there are colons in the tag name. This PR pro-processes the XML content from FLuent's .flprj file to convert double colons to double underscores. E.g. the XML fragment
```
<ProjectStoragePolicy::FolderEnabled class="string" value="true"/>
```
will be converted to
```
<ProjectStoragePolicy__FolderEnabled class="string" value="true"/>
```
=> fix: Preprocess xml content before sending it to ElementTree parser

doc/changelog.d/3953.fixed.md, src/ansys/fluent/core/solver/flobject.py
In deprecated version check we did not consider the version can be less than 22.2 (minimum version form which we support PyFluent). However recently, a deprecated version was introduced as 21.1. That's why this fix.
=> fix: deprecated flag for flobject.py

doc/changelog.d/3963.added.md, src/ansys/fluent/core/services/scheme_eval.py
I could not find a suitable way of writing unittest for this feature. I'll check later if the defect journal can be included.
=> feat: Support unsuppressing prompts in scheme_eval

doc/changelog.d/3982.maintenance.md, src/ansys/fluent/core/session_solver.py
Update error message for attribute errors from Solver. If the attribute is not there in the settings-root, then we should raise the Attribute error from the same class only.
=> chore: Update error message for attribute errors from Solver.

doc/changelog.d/3996.fixed.md, src/ansys/fluent/core/solver/flobject.py, tests/test_builtin_settings.py
Fluent bug 1258060
Avoid server-side error by raising an early AttributeError on client-side when `settings_source` attribute of builtin settings object is overwritten.
Builtin settings objects are instantiated from builtin base classes (in settings_builtin_bases.py), and later morphed into instances  of flobject classes. We need to modify flobject class behaviour to get a custom `__setattr__` behaviour of builtin settings objects at runtime.
=> fix: Fix server-side error in builtin settings objects

doc/changelog.d/3994.fixed.md, src/ansys/fluent/core/fluent_connection.py
As explained in the code comment
=> fix: Handle exceptions from third-party libraries during docker call

doc/changelog.d/4021.fixed.md, src/ansys/fluent/core/utils/deprecate.py
closes https://github.com/ansys/pyfluent/issues/4020
Earlier:
```
>>> import ansys.fluent.core as pf
>>> solver = pf.launch_fluent()
<stdin>:1: PyFluentDeprecationWarning:
>>> solver.exit()
```
Corrected:
```
>>> import ansys.fluent.core as pf
>>> solver = pf.launch_fluent()
>>> solver.exit()
```
=> fix: Decorator warning message

doc/changelog.d/4025.documentation.md, doc/source/user_guide/physical_variables.rst, doc/source/user_guide/user_guide_contents.rst, doc/styles/config/vocabularies/ANSYS/accept.txt
Add PyFluent docs showing how to use `VariableCatalog` objects with its interfaces.
=> docs: use variable catalog

doc/changelog.d/4024.added.md, pyproject.toml, src/ansys/fluent/core/codegen/tuigen.py, src/ansys/fluent/core/launcher/launcher.py, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/utils/fluent_version.py, tests/test_fluent_version.py, tests/test_launcher.py
This is to handle the scenario when a later version of Ansys is installed without Fluent (#4023)
=> feat: Check if fluent exe exists in AWP_ROOT path while determining the Fluent version to launch

doc/changelog.d/4115.miscellaneous.md, tests/conftest.py
closes https://github.com/ansys/pyfluent/issues/915
Each test should create its own working directory. I think this will help to avoid hang issue.
All tests passed - https://github.com/ansys/pyfluent/actions/runs/15485733732
=> refactor: Run each test in its own directory

Makefile, doc/changelog.d/4148.fixed.md, pyproject.toml
Reported by @prmukherj as seen in https://github.com/ansys/pyfluent/actions/runs/15600856694/job/43940344673
The logs are mentioning it here:
Unexpected names under [project]: repository        W-flit_core.config
Unexpected names under [project]: repository        W-flit_core.config
The repository entry shouldn't be there. You already have a Source entry in [project.urls] which is what PyPI needs =)
=> fix: removing invalid pyproject.toml entry

.github/workflows/ci.yml, doc/changelog.d/4158.maintenance.md
GitHub caching for codegen is not working due to the following warning while saving the cache:
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
https://github.com/ansys/pyfluent/actions/runs/15606958362/job/43970126130#step:88:2
This PR fixes the paths included in cache.
=> chore: Fix github caching for codegen

doc/changelog.d/4177.fixed.md, src/ansys/fluent/core/services/scheme_eval.py, src/ansys/fluent/core/solver/flobject.py
We retrieve the Fluent unit strings via scheme calls from PyFluent at the end of the execution of `parameters.output_parameters.list()` command in PyFluent so we can populate Fluent unit strings in that command's return value. This PR prevents a Fluent-side error which was coming from those scheme calls.
`parameters.output_parameters.list()` will be fixed in 26.1 to contain the Fluent unit strings in the return value. The above PyFluent workaround will still be needed in Fluent versions <= 25.2.
=> fix: Fix an issue in returning parameter units

doc/changelog.d/4163.fixed.md, src/ansys/fluent/core/launcher/container_launcher.py, src/ansys/fluent/core/launcher/fluent_container.py, tests/conftest.py, tests/test_builtin_settings.py, tests/test_launcher.py, tests/test_session.py
There were issues running Fluent containers through PyFluent introduced at some point since version 0.30.5 (after which the `simba-plugin-fluent` tests started failing). The mount_source/mount_target/working_dir logic  was not working properly, see first commit below for test that was showing the failure: https://github.com/ansys/pyfluent/pull/4163/commits/270495dd0be9453e728699e14b017e401874fd6c
Notes:
- Main change: revised mount_source/mount_target logic, see code comments in `fluent_container.py` for more details
- Took the opportunity to do some refactoring:
- New `dict_to_str` utility function to provide "pretty printed" string for dicts, also aware of hide log secrets env var for CI runs
- Revised docstring for mount_source/mount_target
- New test, and test fixes related to this. …
=> fix: container launch issues

doc/changelog.d/4197.fixed.md, pyproject.toml, src/ansys/fluent/core/launcher/launch_options.py, tests/test_launcher.py
1. Remove tensorflow dependency as it is supported for Python version <= 3.10.
2. quarto-cli works fine after updating ansys-sphinx-theme.
3. Do not show a warning if graphics_drivers or ui_mode are None.
We will merge this PR before creating a release.
Earlier -
```
solver = launch_fluent(start_container=True, dry_run=True)
/home/hpohekar/pyfluent/src/ansys/fluent/core/launcher/launch_options.py:309: PyFluentUserWarning: User-specified value for graphics driver is ignored while launching Fluent without GUI or without graphics.
warnings.warn(
pyfluent.launcher WARNING: Configuring Fluent container to mount to /home/hpohekar/pyfluent, with this path available as /home/container/workdir for the Fluent session running inside the container.
```
Now - 
```
solver = …
```
=> fix: No warning for None values and remove a doc dependency

doc/changelog.d/4232.added.md, src/ansys/fluent/core/solver/flobject.py, tests/test_field_data.py, tests/test_flobject.py
The below is possible now:
```python
solver.settings.setup.boundary_conditions.velocity_inlet + solver.settings.setup.boundary_conditions.wall
```
Please see test for detailed usage.
=> feat: add settings named objects

doc/changelog.d/4190.added.md, src/ansys/fluent/core/codegen/settingsgen.py, src/ansys/fluent/core/services/settings.py, src/ansys/fluent/core/solver/flobject.py, tests/test_codegen.py, tests/test_settings_api.py
The enumerated values are exposed as constant attributes of the instance. Please see the unittest for usage.
There is already an attribute `allowed-values-with-display-text` in settings API to fetch all possible allowed values which has been added to the static-info (Fluent PR 599447).
Below is the fragment of generated class:
```
class model_2(String, AllowedValuesMixin):
"""
Viscous Model.
"""
_version = '261'
fluent_name = 'model'
_python_name = 'model'
LAMINAR = _FlConstant('laminar')
MIXING_LENGTH = _FlConstant('mixing-length')
KE1E = _FlConstant('ke1e')
INVISCID = _FlConstant('inviscid')
...
```
TODO: doc update
=> feat: Set string settings with allowed values via string constants

doc/changelog.d/4285.fixed.md, src/ansys/fluent/core/codegen/builtin_settingsgen.py, src/ansys/fluent/core/solver/settings_builtin_data.py, tests/test_builtin_settings.py
Following code will directly read the case:
```
with using(solver):
ReadCase(file_name=import_filename)
```
=> fix: Builtin commands should execute the command without any additional call.

doc/api_rstgen.py, doc/changelog.d/4286.miscellaneous.md, doc/source/api/api_contents.rst, doc/source/user_guide/fields/field_data.rst, src/ansys/fluent/core/services/field_data.py, tests/test_field_data.py
Current usage:
```python
>>> sorted(field_data.scalar_fields.allowed_values())
['abs-angular-coordinate', 'absolute-pressure', 'angular-coordinate',
'anisotropic-adaption-cells', 'aspect-ratio', 'axial-coordinate', 'axial-velocity',
'boundary-cell-dist', 'boundary-layer-cells', 'boundary-normal-dist', ...]
>>> field_data.vector_fields.allowed_values()
['velocity', 'relative-velocity']
>>> from ansys.units import VariableCatalog
>>> field_data.vector_fields.is_active(VariableCatalog.VELOCITY)
True
>>> field_data.vector_fields.is_active(VariableCatalog.VELOCITY_MAGNITUDE)
False
>>> field_data.scalar_fields.is_active(VariableCatalog.VELOCITY_MAGNITUDE)
True
>>> field_data.surfaces.allowed_values()
['in1', 'in2', 'in3', 'inlet', 'inlet1', 'inlet2', 'out1', 'outlet', 'solid_up:1', …
```
=> refactor: Update allowed_values interface for field_data.

.ci/pull_fluent_image.py, .github/workflows/ci.yml, doc/changelog.d/4305.maintenance.md, src/ansys/fluent/core/docker/utils.py
As a stable image revision at the new image path has now been pushed to the gh variables, reinstating the usage of that stable revision in CI.
=> ci: Use the stable image id in PR CI

doc/changelog.d/4327.miscellaneous.md, src/ansys/fluent/core/launcher/pim_launcher.py
This pull request introduces enhancements to the `pim_launcher.py` file in the `ansys.fluent.core.launcher` module. The changes improve version handling and gRPC channel configuration, ensuring better compatibility and performance.
* Updated the fallback logic in the `__call__` method to use the current release version when no product version is specified, ensuring a consistent and reliable default behavior.
* Modified the `launch_remote_fluent` function to set gRPC channel options for maximum send and receive message lengths using `_get_max_c_int_limit()`, enhancing the robustness of remote communication.
* Added `_get_max_c_int_limit` to the imports from `fluent_connection`, enabling its use for gRPC configuration.
Earlier:
Now:
=> refactor: set default version to latest release and use max grpc limit

doc/changelog.d/4333.miscellaneous.md, src/ansys/fluent/core/search.py, src/ansys/fluent/core/session_utilities.py, tests/test_search.py
This pull request introduces enhancements to the search functionality in `src/ansys/fluent/core/search.py` and adds a new parameter to the `from_pim` method in `src/ansys/fluent/core/session_utilities.py`. It also modifies the test suite to reflect these changes. The most significant updates include the addition of a `match_whole_word` parameter to improve search precision, adjustments to search logic, and the inclusion of a `ui_mode` parameter in session utilities.
* Added a `match_whole_word` parameter to `_print_search_results` and `_search_whole_word` functions, enabling exact match searches when set to `True`. If `False` or `None`, semantic search is performed. (`src/ansys/fluent/core/search.py`: [[1]](diffhunk://#diff-214c799312c66e60a7f59b81d50ecf539ae9e3739ee0d6cafcbd7c4422862664L1 …
=> refactor: Update search API results handling

doc/changelog.d/4345.fixed.md, src/ansys/fluent/core/file_session.py, src/ansys/fluent/core/services/field_data.py
Sometimes some surfaces might be created but field data on them might not be available. For example please refer the issue: https://github.com/ansys/pyfluent-visualization/issues/552
Now we are getting and returning the field data as empty array for these surfaces, just like Fluent does. We are additionally providing an warning that theses surfaces does not have field data.
We need to patch this with v0.34 to address an user bug.
=> fix: Unavaialble field data for some surfaces.

doc/changelog.d/4354.maintenance.md, doc/make.bat
This update addresses the issue of cleaning documentation-generated files. 
Previously, 'make clean' did not remove all content generated by 'make html'. 
Additionally, references to these files in flake8 during pre-commit checks have been removed as they are unnecessary and confusing.
=> chore: Minor update to Makefile to clean the example directory.

.github/workflows/ci.yml, doc/changelog.d/4423.fixed.md
Release CI is broken - https://github.com/ansys/pyfluent/actions/runs/17295108997/job/49117558886
```
Run actions/download-artifact@v4.3.0
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: ansys-fluent-core-artifacts
Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```
=> fix: Release CI [skip tests]

doc/changelog.d/4380.fixed.md, doc/source/user_guide/file_transfer.rst, doc/source/user_guide/session/launching_ansys_fluent.rst, src/ansys/fluent/core/examples/downloads.py, src/ansys/fluent/core/launcher/launch_options.py, src/ansys/fluent/core/launcher/process_launch_string.py, src/ansys/fluent/core/launcher/slurm_launcher.py, src/ansys/fluent/core/module_config.py, tests/conftest.py, tests/test_launcher.py
1. Remove the config equivalent to `PYFLUENT_FLUENT_ROOT` environment variable. That environment variable is only for development use.
2. Remove the mentions of the environment `PYFLUENT_LAUNCH_CONTAINER` from user documentation. That environment variable is only for CI use.
3. Fix a typo in slurm launcher.
=> fix: Some config and env var cleanup

doc/changelog.d/4470.fixed.md, doc/source/conf.py
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
doc\source\conf.py:307:1: E305 expected 2 blank lines after class or function definition, found 1
1     E305 expected 2 blank lines after class or function definition, found 1
1
```
=> fix: flake8 change needed for release [skip tests]

doc/changelog.d/4478.documentation.md, doc/source/user_guide/fields/field_data.rst
Update Field data queries -> Make allowed_values, is_active and range into separate sections.
=> docs: Update Field data queries [skip tests]

doc/changelog.d/4531.documentation.md, doc/source/user_guide/solver_settings/solver_settings_contents.rst
**Context**
The existing documentation for the “new style settings” approach in the solver settings section was outdated or inconsistent with recent API changes. In particular, the way code examples show how to instantiate and use settings objects needed updates (e.g. removal of legacy constructors, updating syntax, clarifying dictionary vs list usage). Without this update, users may be misled or encounter mismatches between docs and implementation.
**Change Summary**
Updated the solver_settings_contents.rst file to reflect the new style settings usage (≈ 28 additions, 26 deletions). 
[GitHub](https://github.com/ansys/pyfluent/pull/4531/files)
Added a new changelog file doc/changelog.d/4531.documentation.md summarizing the documentation update. …
=> docs: Update new style settings docs [skip tests]

doc/changelog.d/4530.fixed.md, tests/test_datamodel_service.py, tests/test_flobject.py, tests/test_new_meshing_workflow.py, tests/test_preferences.py, tests/test_reduction.py
Recent updates to the server-side datamodel-api and renaming of some entries in meshing FDL file have caused certain PyFluent tests to fail. These updates affected how some settings are exposed and validated through the API.
This PR updates the affected PyFluent tests to align with the latest server-side datamodel changes and FDL renaming.
The failures were due to changes in the server-side behavior rather than issues in the test logic itself.
- The introduction of the "exposed_state" in the datamodel altered the activation state of some objects, making certain earlier test scenarios invalid (for example, tests expecting inactive objects to be accessible). Those tests have been removed or adjusted accordingly.
- The fixes were verified through manual debugging to ensure the tests now …
=> fix: Meshing tests.

doc/changelog.d/4494.documentation.md, examples/00-fluent/modeling_ablation.py
Corrected a typo in Ablation example
=> docs: Corrected a typo in Ablation example [skip tests]
